/**
 * Copy for Body signals › Heart and recovery (design/screens/ring-pages.md §7.4; copy there is final). Plain words,
 * sentence case, lowercase engraved labels, a thin space between a number and its unit.
 */
import { THIN_SPACE as T } from '@/components/lib/format';
import type { PeriodKind } from '../models';

const PERIOD_WORD: Record<PeriodKind, string> = { day: 'day', week: 'week', month: 'month', year: 'year' };

export const HEART_COPY = {
  title: {
    hrDay: 'heart rate through the day',
    hrv: 'heart-rate variability last night',
    spo2Night: 'blood oxygen at night',
    tempNight: 'skin temperature at night',
    hrPerDay: 'heart rate per day',
    hrPerMonth: 'heart rate per month',
    resting: 'resting heart rate',
    hrvHistory: 'heart-rate variability · tier C',
    spo2PerNight: 'blood oxygen per night',
    spo2PerMonth: 'blood oxygen per month',
    tempPerNight: 'skin temperature per night',
    tempPerMonth: 'skin temperature per month',
    vendor: 'your ring says',
    zones: 'time in zones',
  },
  /* heart rate through the day (§7.4.2) */
  restingLine: (bpm: number) => `resting ${bpm}`,
  zoneEdge: (zone: number, bpm: number) => `zone ${zone} · ${bpm}`,
  asleep: 'asleep',
  noAge: 'Add your age in Your body to see effort zones.',
  hrDayEmpty: 'No heart-rate readings for this day.',
  resting: (bpm: string) => `resting ${bpm}${T}bpm`,
  lowest: (bpm: string, at: string) => `lowest ${bpm}${T}bpm (${at})`,
  highest: (bpm: string, at: string) => `highest ${bpm}${T}bpm (${at})`,
  readings: (n: string, count: number) => `${n} reading${count === 1 ? '' : 's'}`,
  bpm: (v: string) => `${v}${T}bpm`,
  at: (time: string, rest: string) => `${time} · ${rest}`,
  noReading: 'no readings',
  spotCheck: 'spot check',
  min: (m: number) => `${m}${T}min`,
  minutesFromStart: 'min',
  zoneMinutes: (zone: number, m: number) => `zone ${zone} · ${m}${T}min`,
  zoneTable: 'time in zones',
  zoneTableKey: (shown: boolean) => (shown ? 'hide time in zones table' : 'time in zones table'),
  zoneCols: ['zone', 'minutes', 'share'] as const,
  noZoneTime: 'no time in zones',
  dayTableCols: ['time', 'bpm', 'zone'] as const,
  daySummary: (parts: string[]) => `Heart rate through the day: ${parts.join(', ')}.`,
  daySummaryEmpty: 'Heart rate through the day: no readings.',
  zoneSummary: (parts: string[]) => `Time in zones: ${parts.join(', ')}.`,
  /* heart-rate variability last night (§7.4.3) */
  hrvLine: (v: string, delta: string, lo: string, hi: string) => `${v}${T}ms last night · ${delta}${T}ms from your normal (${lo}–${hi}${T}ms)`,
  hrvValue: (v: string) => `${v}${T}ms last night`,
  forming: (n: number) => `Building your normal: ${n} of 14 nights.`,
  hrvNone: 'No heart-rate variability recorded last night.',
  tier: 'tier C: shown as change from your own normal',
  /* night lines (§7.4.4) */
  spo2Readout: (avg: string, low: string, at: string) => `average ${avg}${T}% · lowest ${low}${T}% at ${at}`,
  tempReadout: (avg: string, unit: string, hi: string, at: string) => `average ${avg}${T}${unit} from your normal · highest ${hi}${T}${unit} at ${at}`,
  tempAbsReadout: (lo: string, hi: string, unit: string) => `${lo}–${hi}${T}${unit}`,
  yourNormal: 'your normal',
  fromNormal: (v: string, unit: string) => `${v}${T}${unit} from your normal`,
  spo2Empty: 'No blood-oxygen readings for this night.',
  tempEmpty: 'No skin-temperature readings for this night.',
  noNight: 'No night recorded.',
  nightTableCols: (unit: string) => ['time', unit] as const,
  tempTableCols: (unit: string) => ['time', unit, 'change from your normal'] as const,
  /* periods (§7.4.5–7.4.7) */
  emptyPeriod: (kind: PeriodKind) => `No heart rate recorded this ${PERIOD_WORD[kind]}.`,
  emptyNights: (kind: PeriodKind) => `No nights recorded this ${PERIOD_WORD[kind]}.`,
  emptyHistory: (what: string, kind: PeriodKind) => `No ${what.toLowerCase()} recorded this ${PERIOD_WORD[kind]}.`,
  rangeReadout: (avg: string, lo: string, hi: string) => `resting average ${avg}${T}bpm (recorded days) · range ${lo}–${hi}`,
  rangeReadoutNoRest: (lo: string, hi: string) => `range ${lo}–${hi}${T}bpm (recorded days)`,
  restingAvg: (avg: string, unit: string, what: 'days' | 'nights') => `average ${avg}${T}${unit} (recorded ${what})`,
  noData: 'no data',
  rangeTableCols: ['date', 'resting', 'lowest', 'highest', 'readings'] as const,
  monthTableCols: ['month', 'resting', 'lowest', 'highest', 'days recorded'] as const,
  slotReadout: (label: string, parts: string[]) => [label, ...parts].join(' · '),
  slotResting: (v: string) => `resting ${v}${T}bpm`,
  slotRestingMean: (v: string) => `resting ${v}${T}bpm (mean)`,
  slotRange: (lo: string, hi: string) => `${lo}–${hi}${T}bpm`,
  slotReadings: (n: string) => `${n} readings`,
  slotDays: (n: number) => `${n} day${n === 1 ? '' : 's'} recorded`,
  rangeSummary: (title: string, coverage: string, readout: string) => `${title}: ${coverage}; ${readout}.`,
  monthMean: (v: string, unit: string) => `${v}${T}${unit} (mean)`,
  meansTableCols: (unit: string) => ['month', `mean (${unit})`, 'nights recorded'] as const,
  spo2Slot: (avg: string, low: string | null) => (low ? `average ${avg}${T}% · lowest ${low}${T}%` : `average ${avg}${T}%`),
  spo2PeriodReadout: (avg: string) => `average ${avg}${T}% (recorded nights)`,
  spo2TableCols: ['date', 'average', 'lowest'] as const,
  tempSlot: (dev: string, unit: string) => `${dev}${T}${unit} from your normal`,
  tempAbs: (v: string, unit: string) => `${v}${T}${unit}`,
  tempPeriodReadout: (dev: string, unit: string) => `average ${dev}${T}${unit} from your normal (recorded nights)`,
  tempTableColsPeriod: (unit: string) => ['date', unit, 'change from your normal'] as const,
  /* your ring says (§7.4.8) */
  vendorItem: (word: string, value: string) => `${word} ${value} (their estimate)`,
  vendorWords: { stress: 'stress', readiness: 'readiness', sleep: 'sleep score', recovery: 'recovery', strain: 'strain', body_battery: 'body battery' } as const,
  vendorNone: 'Your ring gave no estimates for this period.',
  /* coverage */
  coverageDays: 'days',
  coverageNights: 'nights',
  newSource: 'new source',
} as const;
