/**
 * Catalogues (E8): exercise, equipment, food and supplement schemas, stimulus mapping, equivalence credit,
 * equipment-aware composition and the evidence policy helpers. Pure (tier P): no React, state, DOM, clock or randomness.
 * The seed data lives in `@/content/catalogues` (`SEED_CATALOGUE`). API guide: docs/CATALOGUES.md.
 */
export type * from './types';
export { createCatalogue, validateCatalogue, validateExercise, USER_SOURCE, type CatalogueInput, type CatalogueIssue } from './catalogue';
export {
  resolveDose,
  resolveSession,
  resolveStimulus,
  aggregateStimulus,
  toEngineDose,
  boutEnergy,
  stimulusTermsOf,
  implementOf,
  loadPctFromRepsToFailure,
  repsToFailureAt,
  fRir,
  fLoad,
  fRest,
  fLoadStrength,
  loadClassOf,
  memWeight,
  weeklyDose,
  type WeeklyDose,
  type StimulusContext,
  type ExerciseDose,
  type EnergyEstimate,
  type CardioPart,
  type ResolvedSession,
  type StimulusTerms,
  type EngineTrainingDose,
} from './stimulus';
export {
  stimulusEquivalence,
  sessionEquivalence,
  vectorOf,
  nutrientEquivalence,
  defaultIntent,
  intentFor,
  transferCoefficient,
  resolveUnknown,
  resolveUnknownSync,
  resolveUnknownEquipment,
  draftToRecord,
  validateDraft,
} from './equivalence';
export {
  composeSession,
  composeSessions,
  trainingEnvelope,
  shoppingList,
  swapOptions,
  isWilling,
  type ResistancePrescription,
  type CardioPrescription,
  type SessionPrescription,
  type ComposeOptions,
  type ConcreteItem,
  type ConcreteSession,
  type TrainingEnvelope,
  type ShoppingItem,
  type SwapOption,
} from './compose';
export {
  isIncludable,
  inclusionReason,
  bandFloor,
  inflateBand,
  inflationFactor,
  certaintyFromAnchor,
  similarityS,
  tauPrior,
  tauCdf,
  tauQuantile,
  triQuantile,
  mapIntervention,
  exerciseLabels,
  exerciseLabel,
  supplementLabels,
  supplementLabel,
  exerciseSimilarity,
  exerciseTau,
  exerciseMapping,
  catalogueEdges,
  hedge,
  evidenceClause,
  type MappingSpec,
  type MappedIntervention,
  type CatalogueEdge,
} from './evidence';
export { createFoodTable, mealTotals, netCarbPer100g, logBand, LOG_SIGMA, type LogInputKind } from './foods';
export { CATALOGUE_PARAMS, INTENT_DEFAULTS, ENGINE as ENGINE_CONSTANTS, cp as catalogueParam, type GoalClass } from './params';
export * from './vocab';
export {
  parseUserItems,
  personCatalogue,
  buildUserEquipment,
  buildUserExercise,
  buildUserFood,
  userItemKey,
  userItemId,
  USER_ITEM_KINDS,
  type UserItemKind,
  type UserItemDoc,
  type ParsedUserItems,
  type AddOutcome,
} from './user';
export { DEFAULT_TRAINING_PROFILE, trainingProfileFromIntake, prescriptionFromEngine, equipmentIdFor, type TrainingProfileResult } from './setup';
