/**
 * safety — the warning rule table (docs/MODEL_SPEC.md §7.2; dossier 17 §3).
 *
 * One entry per rule: id, severity, the direction in which "worse" runs (for `peakValue`), the driving quantity, the
 * user-facing message template (<= 200 characters INCLUDING placeholders; copied verbatim from 17 §3 except W-F04,
 * which carries the 20-corrected wording of spec §1.16) and the evidence the message rests on (`sources`).
 *
 * The messages of the 78 dossier rows were extracted programmatically from `research/17-safety-guardrails.md`; the
 * four engine-specific rules (W-13-ALPERT, W-05-KETO-FED, W-20-FAST-LEAN from spec §7.2, and W-01-FATFLOOR from review M9) are written in the same
 * voice (no moralising, no diagnosis, no guarantees; 17 §4.5).
 *
 * Placeholders: {EI} {floor} {d} {cap} {r} {EA} {x} {bmi} {bf} {n} {p} {f} {g} {fm} {102/88}; see `renderMessage` in index.ts.
 *
 * Evidence: what a user sees is the template (the message) and `sources` (rendered as "Safety limits › references 6, 7",
 * each part a link into the Evidence library; see `<SourceRefLinks/>` and `sourceRefsLabel`). `sources` are structured
 * `SourceRef`s: the topic, and the positions of the studies in that topic's numbered source list. Each carries the
 * maintainers' research-note pointer (e.g. "17 §3 [6][7]") in `legacy`, which is never rendered. The research note's
 * "[n]" numbers differ from the topic page's positions above 80 (sources left off the page); the positions here are
 * already converted (`topicRefPosition` in `@/content/evidence/sources`; `ruleSources.test.ts` checks every rule).
 */
import type { SourceRef } from '../../../content/evidence/schema';
import type { Severity, WarningRuleId } from '../../types/events';

export interface RuleDef {
  readonly id: WarningRuleId;
  readonly severity: Severity;
  /** Which extreme of the driving quantity is "worst" inside a merged run (peakValue). */
  readonly worst: 'min' | 'max';
  /** The driving quantity (documentation; unit in the text). */
  readonly driver: string;
  /** Message template, <= 200 characters with placeholders counted at their template length. */
  readonly template: string;
  /** The evidence behind the message: Evidence library topic and source positions. The only form a screen renders. */
  readonly sources: readonly SourceRef[];
}

/** Maximum message length (17 §3, "Message-length check (CI)"). */
export const MAX_MESSAGE_CHARS = 200;

/** Corrected W-F04 wording (supervised water-only fasting: >= grade 3 adverse events 20 % by day 5; SAE 2 of 768 stays). */
export const W_F04_TEXT =
  'Water fasts of 3–7 days are studied under medical supervision: about 20% of stays had a grade ≥3 adverse event by day 5; serious events were rare (2 of 768). Not to be attempted alone.';

const r = <I extends WarningRuleId>(
  id: I,
  severity: Severity,
  worst: 'min' | 'max',
  driver: string,
  template: string,
  sources: readonly SourceRef[],
): RuleDef & { readonly id: I } => ({ id, severity, worst, driver, template, sources });

export const RULES = [
  r(
    'W-E01',
    'caution',
    'min',
    'EI_7, kcal/d',
    'Your average intake ({EI} kcal/day) is below the {floor} kcal/day usually treated as the minimum without professional support. This is a simulation, not advice.',
    [{ topic: 'safety-limits', refs: [6, 7], legacy: '17 §3 [6][7]' }],
  ),
  r(
    'W-E02',
    'danger',
    'min',
    'EI_7, kcal/d',
    'Under 800 kcal/day is a very-low-energy diet: guidelines say medical supervision only, for up to 12 weeks. Serious heart-rhythm problems were reported with prolonged use.',
    [{ topic: 'safety-limits', refs: [6, 7, 38], legacy: '17 §3 [6][7][38]' }],
  ),
  r(
    'W-E03',
    'caution',
    'max',
    'deficit_pct_7, %',
    'Averaged over the last 7 days, your deficit is {d}% of maintenance (training included). Above about {cap}% the model shows more muscle loss and stronger hunger and hormone effects. Results vary.',
    [{ topic: 'safety-limits', refs: [6, 4, 26], legacy: '17 §3 [6][4][26]' }],
  ),
  r(
    'W-E04',
    'danger',
    'max',
    'deficit_pct_7, %',
    'Averaged over the last 7 days, your deficit is over 40% of maintenance (training included): beyond what is usually studied outside clinical or research supervision. Individual risk is higher.',
    [{ topic: 'safety-limits', refs: [54, 4], legacy: '17 §3 [54][4]' }],
  ),
  r(
    'W-E05',
    'caution',
    'max',
    'rate_14, %BW/wk',
    'You would lose about {r}% of body weight per week. Slower loss (about {cap}%/week) protects muscle and lowers the risk of gallstones, hair shedding and fatigue.',
    [{ topic: 'safety-limits', refs: [29, 5, 4, 35], legacy: '17 §3 [29][5][4][35]' }],
  ),
  r(
    'W-E06',
    'danger',
    'max',
    'rate_14, kg/wk',
    'Losing more than 1.5 kg (3.3 lb) a week sharply raises gallstone risk in studies, alongside faster muscle loss. Consider a slower pace or medical supervision.',
    [{ topic: 'safety-limits', refs: [29, 31], legacy: '17 §3 [29][31]' }],
  ),
  r(
    'W-E07',
    'caution',
    'min',
    'EA_7, kcal/kg FFM/d',
    'Energy left after exercise is about {EA} kcal/kg lean mass/day. Staying near 30 for weeks can disturb hormones, bone and recovery. Eat more or train less to move up.',
    [{ topic: 'safety-limits', refs: [1, 2, 3], legacy: '17 §3 [1][2][3]' }],
  ),
  r(
    'W-E08',
    'danger',
    'min',
    'EA_7, kcal/kg FFM/d',
    'Energy left after exercise is {EA} kcal/kg lean mass/day, below the ~30 level linked to reproductive-hormone and bone changes in lab studies. Not sustainable for health.',
    [{ topic: 'safety-limits', refs: [2, 3, 1], legacy: '17 §3 [2][3][1]' }],
  ),
  r(
    'W-E09',
    'info',
    'min',
    'EA_7, kcal/kg FFM/d',
    'Energy availability is {EA} kcal/kg lean mass/day. Values of 30–45 are "reduced": acceptable for a short fat-loss phase, not for months.',
    [{ topic: 'safety-limits', refs: [1], legacy: '17 §3 [1]' }],
  ),
  r(
    'W-E10',
    'caution',
    'max',
    'consecutive days with deficit >= 15 %',
    'You have been in a deficit of 15% or more for {n} weeks. A 1–2 week maintenance break is a common safeguard and did not reduce fat loss in trials.',
    [{ topic: 'safety-limits', refs: [25, 24, 7], legacy: '17 §3 [25][24][7]' }],
  ),
  r(
    'W-E11',
    'caution',
    'max',
    'cum_loss, %',
    'Total loss so far is {x}% of your starting weight. Losses above about 20–25% carry higher risk of gallstones, muscle loss and nutrient shortfalls.',
    [{ topic: 'safety-limits', refs: [31, 70], legacy: '17 §3 [31][70]' }],
  ),
  r(
    'W-E12',
    'danger',
    'max',
    'cum_loss, %',
    'Losing more than 24% of body weight is linked with gallstones and, in the Minnesota semi-starvation study, anaemia, weakness, oedema and low mood. Please involve a clinician.',
    [{ topic: 'safety-limits', refs: [31, 70], legacy: '17 §3 [31][70]' }],
  ),
  r(
    'W-E13',
    'caution',
    'min',
    'BMI, kg/m2',
    'This plan takes your BMI to {bmi}, close to the underweight range (below 18.5). Consider a goal at or above 20 and how your body-fat input may be off by a few points.',
    [{ topic: 'safety-limits', refs: [7, 77, 69], legacy: '17 §3 [7][77][69]' }],
  ),
  r(
    'W-E14',
    'danger',
    'min',
    'BMI, kg/m2',
    'A BMI below 18.5 is the underweight range, linked with bone, hormone and other health problems. If this is your real weight or goal, please speak with a clinician.',
    [{ topic: 'safety-limits', refs: [7, 1, 77], legacy: '17 §3 [7][1][77]' }],
  ),
  r(
    'W-E15',
    'caution',
    'min',
    'body fat, %',
    'Estimated body fat ({bf}%) is low. Very lean phases lowered hormones, mood and strength in studies; your body-fat input may also be off by about ±4 points.',
    [{ topic: 'safety-limits', refs: [66, 67, 69], legacy: '17 §3 [66][67][69]' }],
  ),
  r(
    'W-E16',
    'danger',
    'min',
    'body fat, %',
    'Estimated body fat ({bf}%) is in a range where studies show large hormone, heart-rate and mood changes. Sustained levels this low are not advised without medical support.',
    [{ topic: 'safety-limits', refs: [66, 67, 68], legacy: '17 §3 [66][67][68]' }],
  ),
  r(
    'W-E17',
    'info',
    'max',
    'rate_14, %BW/wk',
    'Fast weight loss can trigger temporary hair shedding a few months later (mean loss 15% at ~3.5 kg/month in one clinic series). It usually grows back.',
    [{ topic: 'safety-limits', refs: [35, 36, 7], legacy: '17 §3 [35][36][7]' }],
  ),
  r(
    'W-E18',
    'caution',
    'min',
    'EA_7, kcal/kg FFM/d',
    'Lighter, irregular or missing periods are an early sign intake is too low for your activity. If that happens, eat more and see a clinician; this simulator cannot assess it.',
    [{ topic: 'safety-limits', refs: [2, 67, 1], legacy: '17 §3 [2][67][1]' }],
  ),
  r(
    'W-E19',
    'info',
    'max',
    'days of prolonged restriction',
    'Prolonged calorie restriction lowers bone density slightly (hip −0.01 to −0.015 g/cm² in trials). Exercise helps limit the loss.',
    [{ topic: 'safety-limits', refs: [27, 26, 49], legacy: '17 §3 [27][26][49]' }],
  ),
  r(
    'W-E20',
    'caution',
    'min',
    'EA_7, kcal/kg FFM/d',
    'Low energy availability has been linked with more illness and lost training days in athletes. The model cannot predict your individual immune response.',
    [{ topic: 'safety-limits', refs: [1], legacy: '17 §3 [1]' }],
  ),
  r(
    'W-M01',
    'caution',
    'min',
    'protein, g/kg RW (7-d mean)',
    'Protein of {p} g/kg is below the 0.8 g/kg adult minimum (RDA). Muscle loss is likely over time.',
    [{ topic: 'safety-limits', refs: [53], legacy: '17 §3 [53]' }],
  ),
  r(
    'W-M02',
    'info',
    'min',
    'protein, g/kg RW (7-d mean)',
    'In a deficit, {p} g/kg protein is low for keeping muscle. Trials use 1.2–2.4 g/kg, higher when you are leaner or training hard.',
    [{ topic: 'safety-limits', refs: [54, 55, 57], legacy: '17 §3 [54][55][57]' }],
  ),
  r(
    'W-M03',
    'danger',
    'max',
    'protein, %E (7-d mean)',
    'Protein above 35% of energy risks nausea and excess ammonia and crowds out other nutrients. A suggested ceiling is about 25% of energy.',
    [{ topic: 'safety-limits', refs: [58], legacy: '17 §3 [58]' }],
  ),
  r(
    'W-M04',
    'caution',
    'max',
    'protein, g/kg FFM (7-d mean)',
    'Protein above 3.1 g/kg lean mass is beyond the range studied in lean dieting athletes; benefits beyond it are unproven.',
    [{ topic: 'safety-limits', refs: [55, 57], legacy: '17 §3 [55][57]' }],
  ),
  r(
    'W-M05',
    'danger',
    'max',
    'protein, g/kg RW (7-d mean)',
    'With kidney disease, guidelines advise about 0.8 g/kg and avoiding above 1.3 g/kg. Please check with your kidney team before a high-protein plan.',
    [{ topic: 'safety-limits', refs: [51], legacy: '17 §3 [51]' }],
  ),
  r(
    'W-M06',
    'caution',
    'min',
    'fat, g/d (7-d mean)',
    'Fat is {f} g/day. During faster weight loss, too little fat is linked to gallstones; include some fat at main meals (aim for at least 10 g).',
    [{ topic: 'safety-limits', refs: [33, 34, 31], legacy: '17 §3 [33][34][31]' }],
  ),
  r(
    'W-M07',
    'danger',
    'min',
    'fat, g/d',
    'Very low fat during rapid weight loss caused gallstones in 4 of 6 people in one trial, and essential fatty-acid needs go unmet. Add fat, or slow the loss.',
    [{ topic: 'safety-limits', refs: [33, 62], legacy: '17 §3 [33][62]' }],
  ),
  r(
    'W-M08',
    'info',
    'min',
    'net carbohydrate, g/d',
    'Below ~50 g net carbs the model enters ketosis. Expect 2–4 weeks of "keto flu" (tiredness, headache), more urination and salt loss; keep fluids and sodium up.',
    [{ topic: 'safety-limits', refs: [43, 21, 60], legacy: '17 §3 [43][21][60]' }],
  ),
  r(
    'W-M09',
    'caution',
    'min',
    'net carbohydrate, g/d',
    'After 4 weeks of very-low-carb, LDL cholesterol rose in all 17 healthy women in one trial (+1.8 mmol/L). Consider a lipid blood test after 8–12 weeks.',
    [{ topic: 'safety-limits', refs: [46], legacy: '17 §3 [46]' }],
  ),
  r(
    'W-M10',
    'danger',
    'min',
    'net carbohydrate, g/d',
    'Very-low-carb eating can be dangerous with insulin or SGLT2 drugs, pancreatitis, fat-metabolism disorders, porphyria, pregnancy or breastfeeding. Not without your clinician.',
    [{ topic: 'safety-limits', refs: [42, 43, 44, 45], legacy: '17 §3 [42][43][44][45]' }],
  ),
  r(
    'W-M11',
    'info',
    'min',
    'fibre, g per 1000 kcal (7-d mean)',
    'Fibre is {x} g per 1000 kcal (target 14+). Low fibre with low intake can mean constipation and missing micronutrients.',
    [{ topic: 'safety-limits', refs: [59], legacy: '17 §3 [113][59]' }],
  ),
  r(
    'W-M12',
    'caution',
    'min',
    'sodium, g/d',
    'Salt loss is greatest on days 1–4 of fasting or very-low-carb eating (up to ~2.3–3.4 g sodium/day). Too little sodium can cause dizziness, headache and fainting.',
    [{ topic: 'safety-limits', refs: [13, 21], legacy: '17 §3 [13][21]' }],
  ),
  r(
    'W-M13',
    'info',
    'max',
    'sodium, g/d',
    'Sodium above 2.3 g/day over months is linked with higher long-term cardiovascular risk in the national reference intakes.',
    [{ topic: 'safety-limits', refs: [60], legacy: '17 §3 [60]' }],
  ),
  r(
    'W-M14',
    'caution',
    'min',
    'fluid, L/d',
    'Your fluid intake looks low. Total water of about 2.0 L (women) or 2.5 L (men) a day, including food, is the EU adequate intake. Less can worsen headaches and dizziness.',
    [{ topic: 'safety-limits', refs: [59], legacy: '17 §3 [59]' }],
  ),
  r(
    'W-M15',
    'caution',
    'max',
    'fluid, L/d',
    'Very high fluid intake can dilute blood sodium (confusion, seizures). Drink to thirst. One supervised water-only fast ended in hospital this way.',
    [{ topic: 'safety-limits', refs: [65, 12], legacy: '17 §3 [65][12]' }],
  ),
  r(
    'W-M16',
    'caution',
    'max',
    'supplemental potassium, g/d',
    'High-dose potassium supplements can cause dangerous heart-rhythm problems, especially with kidney disease or some blood-pressure medicines. Do not use without medical advice.',
    [{ topic: 'safety-limits', refs: [60], legacy: '17 §3 [60]' }],
  ),
  r(
    'W-M17',
    'info',
    'max',
    'supplemental magnesium, mg/d',
    'Magnesium supplements above 350 mg/day commonly cause diarrhoea; that is the tolerable upper level for supplements.',
    [{ topic: 'safety-limits', refs: [61], legacy: '17 §3 [61]' }],
  ),
  r(
    'W-M18',
    'caution',
    'max',
    'alcohol, UK units in the trailing 7 d',
    'More than 14 units of alcohol a week is above UK low-risk guidance; WHO says no level of alcohol is completely safe.',
    [{ topic: 'safety-limits', refs: [93, 95], legacy: '17 §3 [97][99]' }],
  ),
  r(
    'W-M19',
    'danger',
    'max',
    'alcohol, g on the day',
    'Alcohol during fasting or very-low-energy eating adds risks (ketoacidosis with some diabetes drugs; refeeding problems after long fasts). Avoid it on these days.',
    [{ topic: 'safety-limits', refs: [44, 8], legacy: '17 §3 [44][8]' }],
  ),
  r(
    'W-M20',
    'caution',
    'max',
    'alcohol, g on the day',
    'More than 2 standard drinks on one occasion is linked with more injuries and other harms, whatever your weekly total.',
    [{ topic: 'safety-limits', refs: [94], legacy: '17 §3 [98]' }],
  ),
  r(
    'W-M21',
    'caution',
    'max',
    'caffeine, mg/d',
    'Caffeine above 400 mg/day (about 4 cups of coffee), or 200 mg at once, is beyond what EFSA and FDA consider safe for most adults.',
    [{ topic: 'safety-limits', refs: [90, 91], legacy: '17 §3 [94][95]' }],
  ),
  r(
    'W-M22',
    'info',
    'max',
    'caffeine within 6 h of bed, mg',
    'Even 100 mg of caffeine close to bedtime can shorten and disturb sleep in some adults.',
    [{ topic: 'safety-limits', refs: [90], legacy: '17 §3 [94]' }],
  ),
  r(
    'W-M23',
    'info',
    'max',
    'creatine, g/d',
    'Creatine maintenance is 3–5 g/day; loading (about 0.3 g/kg/day) is used for up to a week. If you have kidney disease, ask your clinician first.',
    [{ topic: 'safety-limits', refs: [92], legacy: '17 §3 [96]' }],
  ),
  r(
    'W-M24',
    'caution',
    'min',
    'net carbohydrate, g/d',
    'Ketogenic eating can raise kidney-stone risk (about 2.5–4% of children on medical ketogenic diets). Drink plenty of fluids, and ask a clinician first if you have had stones.',
    [{ topic: 'safety-limits', refs: [42, 43], legacy: '17 §3 [42][43]' }],
  ),
  r(
    'W-F01',
    'info',
    'max',
    'fast_h, h',
    'Fasts up to 24 h were well tolerated in healthy adults in trials. Skip fasting if you take diabetes or blood-pressure medicine, are pregnant, or have had an eating disorder.',
    [{ topic: 'safety-limits', refs: [17, 47, 43], legacy: '17 §3 [17][47][43]' }],
  ),
  r(
    'W-F02',
    'caution',
    'max',
    'fast_h, h',
    'Fasts of 24–48 h can cause lightheadedness, headache and low energy. Keep drinking, add salt, keep exercise light, and stop if you feel faint or unwell.',
    [{ topic: 'safety-limits', refs: [12, 13, 16], legacy: '17 §3 [12][13][16]' }],
  ),
  r(
    'W-F03',
    'caution',
    'max',
    'fast_h, h',
    'In medically supervised water-only fasts, near-fainting occurred in about 28% of stays and raised blood pressure in 29%. Plan salt and fluids, tell someone, and ease back into eating.',
    [{ topic: 'safety-limits', refs: [12], legacy: '17 §3 [12]' }],
  ),
  r('W-F04', 'danger', 'max', 'fast_h, h', W_F04_TEXT, [
    { topic: 'safety-limits', refs: [12, 11, 13], legacy: '17 §3 [12][11][13]' },
  ]),
  r(
    'W-F05',
    'danger',
    'max',
    'fast_h, h',
    'Fasts beyond 7 days carry serious risks, including low sodium and heart-rhythm problems; deaths were reported in historical prolonged-fasting programs. Medical supervision only.',
    [{ topic: 'safety-limits', refs: [12, 13], legacy: '17 §3 [12][13]' }],
  ),
  r(
    'W-F06',
    'caution',
    'max',
    'fast_h, h',
    'No salt or fluid plan for this fast. Sodium loss peaks around days 3–4 (about 2.3–3.4 g/day); plain water alone risks low blood sodium. Consider ~2–3 g sodium/day and 2–3 L fluid.',
    [{ topic: 'safety-limits', refs: [13, 12], legacy: '17 §3 [13][12]' }],
  ),
  r(
    'W-F07',
    'caution',
    'max',
    'fast_h, h',
    "These fasts are closer together than the model's recovery assumptions allow (glycogen, protein and salt balance). Results after this point are less reliable.",
    [{ topic: 'safety-limits', refs: [16], legacy: '17 §3 [16]' }],
  ),
  r(
    'W-F08',
    'danger',
    'max',
    'fast_h, h',
    'After fasting over 3 days, restart food gradually (about half your usual energy for the first 2 days). Big meals raise refeeding-syndrome risk (low phosphate, potassium, magnesium).',
    [{ topic: 'safety-limits', refs: [8, 9], legacy: '17 §3 [8][9]' }],
  ),
  r(
    'W-F09',
    'caution',
    'max',
    'fast_h at the hard session, h',
    'Hard exercise while fasting cut endurance and risked low blood sugar in studies; arm strength fell ~10% after 3.5 days. Keep long-fast days light.',
    [{ topic: 'safety-limits', refs: [20, 19], legacy: '17 §3 [20][19]' }],
  ),
  r(
    'W-F10',
    'caution',
    'max',
    'fast_h, h',
    'Long fasts have mostly been studied in people with excess body fat; leaner people lose more muscle and have less reserve.',
    [{ topic: 'safety-limits', refs: [13, 11], legacy: '17 §3 [13][11]' }],
  ),
  r(
    'W-F11',
    'info',
    'max',
    'fast_h, h',
    'Fasting raises blood uric acid (about +46% in a 4–21-day cohort), which can trigger gout attacks or kidney stones in people prone to them.',
    [{ topic: 'safety-limits', refs: [11, 13], legacy: '17 §3 [11][13]' }],
  ),
  r(
    'W-F12',
    'danger',
    'max',
    'consecutive PSMF-like days',
    'This is a very-low-energy "protein-sparing" pattern. Real programs add vitamins and minerals, drink 2+ L water, use supervision and stop within about 12 weeks.',
    [{ topic: 'safety-limits', refs: [41, 7, 38], legacy: '17 §3 [41][7][38]' }],
  ),
  r(
    'W-F13',
    'caution',
    'max',
    'fastH_7, h',
    'You are fasting most of the week. Studied alternate-day plans ran 4 weeks in healthy adults; longer or heavier patterns lack safety data.',
    [{ topic: 'safety-limits', refs: [16], legacy: '17 §3 [16]' }],
  ),
  r(
    'W-F14',
    'caution',
    'min',
    'eating window, h',
    'A daily eating window under 4 hours makes it hard to reach protein, fibre and micronutrient needs and can worsen dizziness or binge urges. Consider a longer window.',
    [{ topic: 'safety-limits', refs: [47, 17], legacy: '17 §3 [47][17]' }],
  ),
  r(
    'W-X01',
    'caution',
    'max',
    'weekly running load increase, %',
    'Weekly running distance rises {x}%. Beginners who added more than ~30% had higher injury rates (HR ≈ 1.6). Increase by less than 30% a week.',
    [{ topic: 'safety-limits', refs: [85], legacy: '17 §3 [89]' }],
  ),
  r(
    'W-X02',
    'info',
    'max',
    'weekly hard sets, worst muscle',
    'Big jump in weekly training sets. Guidelines suggest 2–3 sessions a week for beginners and load steps of 2–10%.',
    [{ topic: 'safety-limits', refs: [84], legacy: '17 §3 [88]' }],
  ),
  r(
    'W-X03',
    'info',
    'max',
    'days without a rest day',
    'No full rest day for {n} days. Plan at least one rest day a week; the model assumes recovery time.',
    [{ topic: 'safety-limits', legacy: '17 §3 PROPOSED' }],
  ),
  r(
    'W-X04',
    'caution',
    'max',
    'session intensity, frac VO2max',
    'Hot conditions raise heat-illness risk, especially if dehydrated, not acclimatised or on some medicines. Lower the intensity, drink to thirst, stop if dizzy or confused.',
    [{ topic: 'safety-limits', refs: [88, 65], legacy: '17 §3 [92][65]' }],
  ),
  r(
    'W-X05',
    'danger',
    'max',
    'session intensity, frac VO2max',
    'Your screening answers suggest getting clinician clearance before vigorous exercise. This simulation assumes an otherwise healthy adult.',
    [{ topic: 'safety-limits', refs: [83, 82], legacy: '17 §3 [87][86]' }],
  ),
  r(
    'W-S01',
    'caution',
    'max',
    'gain rate, %BW/wk',
    'Weight gain of {g}%/week is faster than the ~0.25–0.5%/week used for lean gain; the extra is mostly fat in the model.',
    [{ topic: 'safety-limits', refs: [64], legacy: '17 §3 [64]' }],
  ),
  r(
    'W-S02',
    'info',
    'max',
    'surplus, % of TDEE',
    'A surplus above ~20% for months mostly adds fat, not muscle, in the model.',
    [{ topic: 'safety-limits', refs: [64], legacy: '17 §3 [64]' }],
  ),
  r(
    'W-S03',
    'caution',
    'max',
    'waist, cm',
    'Waist above {102/88} cm (or over half your height) is linked with higher cardiometabolic risk. Gaining more is not advised; consider talking to a clinician.',
    [{ topic: 'safety-limits', refs: [6, 7], legacy: '17 §3 [6][7]' }],
  ),
  r(
    'W-P01',
    'danger',
    'max',
    'deficit_pct_7, %',
    'This tool is not designed for pregnancy or breastfeeding. Dieting, fasting and very-low-carb eating are not advised without your clinician.',
    [{ topic: 'safety-limits', refs: [43, 96, 45], legacy: '17 §3 [43][101][45]' }],
  ),
  r(
    'W-P02',
    'danger',
    'max',
    'deficit_pct_7, %',
    'You told us eating or weight can be a struggle. Restrictive plans can make that harder. Support is available (see the help card). You deserve care at any weight.',
    [{ topic: 'safety-limits', refs: [7, 74, 75], legacy: '17 §3 [7][74][75]' }],
  ),
  r(
    'W-P03',
    'caution',
    'max',
    'deficit_pct_7, %',
    'For adults over 65, faster loss costs more muscle and bone. Guidelines favour smaller deficits, ≥ 1.0–1.2 g/kg protein and strength training.',
    [{ topic: 'safety-limits', refs: [48, 49, 12], legacy: '17 §3 [48][49][12]' }],
  ),
  r(
    'W-P04',
    'danger',
    'max',
    'deficit_pct_7, %',
    'Diabetes medicines (insulin, sulfonylureas, SGLT2 inhibitors) can cause low blood sugar or ketoacidosis with fasting, low-carb eating or big deficits. Ask your clinician first.',
    [{ topic: 'safety-limits', refs: [44, 47], legacy: '17 §3 [44][47]' }],
  ),
  r(
    'W-P05',
    'caution',
    'max',
    'deficit_pct_7, %',
    'With heart, blood-pressure, kidney or liver conditions, fasting, big deficits and very-low-carb eating can be risky. Please speak with your clinician first.',
    [{ topic: 'safety-limits', refs: [43, 51, 12], legacy: '17 §3 [43][51][12]' }],
  ),
  r(
    'W-P06',
    'caution',
    'max',
    'deficit_pct_7, %',
    'Fasting, ketosis and rapid loss can raise uric acid and stone risk. If you have gout, kidney stones or gallstones, please check with your clinician first.',
    [{ topic: 'safety-limits', refs: [13, 11, 29, 43], legacy: '17 §3 [13][11][29][43]' }],
  ),
  r(
    'W-P07',
    'caution',
    'max',
    'deficit_pct_7, %',
    'Some medicines interact with fasting, dehydration and salt shifts (blood pressure, potassium, lithium levels). Ask your clinician or pharmacist before changing how you eat.',
    [{ topic: 'safety-limits', refs: [43, 8, 23, 22], legacy: '17 §3 [43][8][23][22]' }],
  ),
  r(
    'W-U01',
    'info',
    'max',
    '0 (flag)',
    'Projection for an average person with your inputs. Individual results vary widely, in either direction. Not medical advice.',
    [{ topic: 'safety-limits', legacy: '17 §3 [110][111]' }],
  ),
  r(
    'W-U02',
    'caution',
    'max',
    'BMI, kg/m2',
    'Your inputs are outside the ranges studied to build this model, so the projection is an extrapolation with low confidence.',
    [{ topic: 'safety-limits', legacy: '17 §3 [110]' }],
  ),
  r(
    'W-U03',
    'info',
    'max',
    '0 (flag)',
    'Body-fat and muscle inputs from sliders can be off by about ±4 percentage points; outputs that depend on them inherit that error.',
    [{ topic: 'safety-limits', refs: [69], legacy: '17 §3 [69]' }],
  ),
  r(
    'W-U04',
    'info',
    'max',
    '0 (flag)',
    'Blood-marker curves are model trends for an average person, not lab predictions. They cannot diagnose or rule out any condition.',
    [{ topic: 'safety-limits', legacy: '17 §3 [103]' }],
  ),
  r(
    'W-U05',
    'info',
    'max',
    '0 (flag)',
    'Autophagy and longevity-signal curves are exploratory: human evidence is limited. Please do not treat them as proven health benefits.',
    [{ topic: 'safety-limits', legacy: '17 §3 [107]' }],
  ),
  r(
    'W-13-ALPERT',
    'caution',
    'max',
    'deficit, kcal/d',
    'Averaged over the last 7 days your deficit ({d} kcal/day) is above about {cap} kcal/day, ¾ of the most energy body fat is thought to supply. Beyond that the model draws more from lean tissue.',
    [{ topic: 'transitions-periodisation', refs: [73], legacy: '13 §4.16, §9 (Alpert 2005 PMID 15615615)' }],
  ),
  r(
    'W-05-KETO-FED',
    'danger',
    'max',
    'BHB, mmol/L',
    'Ketones ({x} mmol/L) above 3.0 while eating are a warning sign in people with diabetes or on some diabetes drugs (ketoacidosis). Please speak with a clinician; this simulator cannot diagnose.',
    [{ topic: 'fat-oxidation-ketosis', refs: [71, 72], legacy: '05 §9 (Umpierrez 2024; Kitabchi 2009)' }],
  ),
  r(
    'W-20-FAST-LEAN',
    'caution',
    'min',
    'body fat, %',
    'Leaner people lose about 1.5-2.5 times more protein tissue in long fasts than people with more body fat. At {bf}% body fat, a fast past 48 hours costs more lean tissue than average.',
    [{ topic: 'extended-water-fasting', legacy: '20 §9 (lean users lose 1.5-2.5x more protein)' }],
  ),
  r(
    'W-01-FATFLOOR',
    'danger',
    'min',
    'fat mass, kg',
    "Fat mass ({fm} kg) has reached the model's floor, so any further energy deficit now comes from lean tissue. This is beyond what the model was built for and is not safe without medical care.",
    [{ topic: 'body-weight-models', legacy: '01 §4.6; MODEL_SPEC_REVIEW M9 (smooth fat floor engaged)' }],
  ),
] satisfies readonly RuleDef[];

export type RuleId = (typeof RULES)[number]['id'];
export const N_RULES = RULES.length;

/**
 * id -> index into `RULES` (and row of the hit matrix). An explicit literal (not built at run time) so that the hot
 * evaluation reads constant fields of a fast-mode object; `safety.rules.test.ts` checks it against `RULES`.
 */
export const RULE_INDEX = {
  'W-E01': 0,
  'W-E02': 1,
  'W-E03': 2,
  'W-E04': 3,
  'W-E05': 4,
  'W-E06': 5,
  'W-E07': 6,
  'W-E08': 7,
  'W-E09': 8,
  'W-E10': 9,
  'W-E11': 10,
  'W-E12': 11,
  'W-E13': 12,
  'W-E14': 13,
  'W-E15': 14,
  'W-E16': 15,
  'W-E17': 16,
  'W-E18': 17,
  'W-E19': 18,
  'W-E20': 19,
  'W-M01': 20,
  'W-M02': 21,
  'W-M03': 22,
  'W-M04': 23,
  'W-M05': 24,
  'W-M06': 25,
  'W-M07': 26,
  'W-M08': 27,
  'W-M09': 28,
  'W-M10': 29,
  'W-M11': 30,
  'W-M12': 31,
  'W-M13': 32,
  'W-M14': 33,
  'W-M15': 34,
  'W-M16': 35,
  'W-M17': 36,
  'W-M18': 37,
  'W-M19': 38,
  'W-M20': 39,
  'W-M21': 40,
  'W-M22': 41,
  'W-M23': 42,
  'W-M24': 43,
  'W-F01': 44,
  'W-F02': 45,
  'W-F03': 46,
  'W-F04': 47,
  'W-F05': 48,
  'W-F06': 49,
  'W-F07': 50,
  'W-F08': 51,
  'W-F09': 52,
  'W-F10': 53,
  'W-F11': 54,
  'W-F12': 55,
  'W-F13': 56,
  'W-F14': 57,
  'W-X01': 58,
  'W-X02': 59,
  'W-X03': 60,
  'W-X04': 61,
  'W-X05': 62,
  'W-S01': 63,
  'W-S02': 64,
  'W-S03': 65,
  'W-P01': 66,
  'W-P02': 67,
  'W-P03': 68,
  'W-P04': 69,
  'W-P05': 70,
  'W-P06': 71,
  'W-P07': 72,
  'W-U01': 73,
  'W-U02': 74,
  'W-U03': 75,
  'W-U04': 76,
  'W-U05': 77,
  'W-13-ALPERT': 78,
  'W-05-KETO-FED': 79,
  'W-20-FAST-LEAN': 80,
  'W-01-FATFLOOR': 81,
} as const satisfies Readonly<Record<RuleId, number>>;
