/**
 * Copy for the Ring page's lower sections (design/screens/ring-pages.md §5.3 Check now, §5.4 Today from your ring,
 * §5.6 Sharing, §5.7 Ring settings). Copy from the design is final; lines the design leaves open follow its voice:
 * plain, short, sentence case, lowercase engraved labels, a thin space between a number and its unit.
 * No ring ever asks for a password, code or key, and nothing here names one (decision 13).
 */
import { THIN_SPACE } from '@/components/lib/format';
import type { CheckMetric } from './data';

const u = (v: string, unit: string) => `${v}${THIN_SPACE}${unit}`;

export const RING_SECTIONS_COPY = {
  check: {
    title: 'Check now',
    help: 'Hold still. Your ring measures for about 30 seconds.',
    bankLabel: 'What to measure',
    metric: { hr: 'heart rate', spo2: 'blood oxygen', hrv: 'heart-rate variability', skin_temp: 'skin temperature' } satisfies Record<CheckMetric, string>,
    start: 'Start',
    stop: 'Stop',
    tryAgain: 'Try again',
    last: (value: string, at: string) => `last check ${value} · ${at}`,
    measuring: (secondsLeft: number) => `measuring · ${u(String(secondsLeft), 's')} left`,
    finishing: 'measuring…',
    progress: 'Measuring',
    noLive: '—',
    saved: (at: string) => `saved · ${at}`,
    change: (signed: string) => `change from your normal: ${signed}`,
    noReading: 'No steady reading. Keep the ring snug and your hand still, then try again.',
    offFinger: 'Your ring isn’t touching your skin. Put it on snugly, then try again.',
    stopped: 'Stopped. Nothing was saved.',
    say: {
      measuring: (metric: string) => `Measuring ${metric}.`,
      result: (metric: string, value: string) => `${metric[0]!.toUpperCase()}${metric.slice(1)} ${value}. Saved.`,
    },
  },
  today: {
    title: 'Today from your ring',
    allSignals: 'All body signals ›',
    label: {
      sleep: 'sleep',
      heart: 'heart',
      hrv: 'heart-rate variability',
      spo2: 'blood oxygen',
      skin_temp: 'skin temperature',
      activity: 'activity',
      vendor: 'your ring says',
    },
    noData: 'no data yet today',
    reading: 'reading…',
    asleep: (dur: string) => `${dur} asleep`,
    inBed: (bed: string, up: string) => `in bed ${bed} – ${up}`,
    unknown: (dur: string) => `${dur} unknown`,
    resting: (bpm: string) => `resting ${u(bpm, 'bpm')}`,
    now: (bpm: string, at: string) => `now ${u(bpm, 'bpm')} · ${at}`,
    lastReading: (bpm: string, at: string) => `last reading ${u(bpm, 'bpm')} · ${at}`,
    restingMissing: 'resting not read yet',
    fromNormal: (signed: string, unit: string) => `${u(signed, unit)} from your normal`,
    lastNight: 'last night',
    valueLastNight: (v: string, unit: string) => `${u(v, unit)} last night`,
    tierC: 'best for trends',
    forming: (nights: number) => `building your normal: ${nights} of 14 nights`,
    spo2Night: (pct: string) => `${u(pct, '%')} at night`,
    spo2FromNormal: (signed: string) => `${u(signed, '%')} from your normal at night`,
    steps: (n: string) => `${n} steps`,
    activeMin: (n: string) => `${n} active min`,
    kcal: (n: string) => u(n, 'kcal'),
    meter: { steps: 'steps', activeMin: 'active minutes', activeKcal: 'active energy' },
    meterUnit: { steps: 'steps', activeMin: 'min', activeKcal: 'kcal' },
    sleepScore: (n: string) => `sleep score ${n}`,
    stress: (n: string) => `stress ${n}`,
    theirEstimate: '(their estimate)',
    ago: { hours: (h: number) => `${h} h ago`, yesterday: 'yesterday', days: (d: number) => `${d} days ago` },
  },
  sharing: {
    title: 'Sharing',
    switchLabel: 'Use my ring data in my plan and Coach',
    line: 'Your ring data is used for your plan and scores, and the Coach and your AI tools can see it. Turn it off here or per signal in Settings › Devices.',
    some: 'Some of it is shared.',
    chooseInSettings: 'Choose in Settings › Devices',
    nothingYet: 'Applies once your ring has been read.',
    notice: 'Your ring data is now shared with your plan and Coach. You can turn that off here.',
    ok: 'OK',
    turnedOn: 'Your ring data is shared with your plan and Coach.',
    turnedOff: 'Your ring data is no longer used in your plan or seen by the Coach.',
    undo: 'Undo',
    failed: 'Couldn’t change that. Try again.',
  },
  settings: {
    title: 'Ring settings',
    titleFor: (label: string) => `Ring settings · ${label}`,
    firmware: 'firmware',
    firmwareUnknown: 'read when connected',
    keepConnected: 'keep my ring connected',
    keepConnectedHelp: 'Stays connected in the background. Android shows a small notification while it is.',
    tray: 'keep running in the tray',
    trayLine: 'Vitals stays in the tray when you close the window.',
    measuring: 'how often your ring measures',
    allDayHr: 'all-day heart rate',
    every: 'every',
    minutes: 'min',
    measure: { spo2: 'blood oxygen', stress: 'stress', hrv: 'heart-rate variability', temp: 'temperature' },
    sent: 'sent to your ring',
    sentLater: 'sent when it next connects',
    battery: 'battery over time',
    batteryEmpty: 'Not enough readings yet.',
    batteryLow: 'low',
    batterySummary: (from: string, to: string, lo: string, hi: string, now: string) =>
      `Battery from ${from} to ${to}: between ${lo} and ${hi}, last ${now}. Breaks in the line are times with no readings.`,
    batteryCols: ['day', 'lowest', 'highest', 'readings'] as const,
    batteryTable: 'Battery per day',
    find: 'find my ring',
    vibrate: 'Vibrate',
    reset: 'reset the ring',
    resetKey: 'Reset the ring…',
    resetTitle: 'Reset the ring?',
    resetBody: 'This erases everything stored on the ring itself. Vitals reads it first. You’ll connect it again afterwards.',
    resetConfirm: 'Reset ring',
    cancel: 'Cancel',
    failed: 'Couldn’t do that. Try again.',
  },
} as const;
