// Android brand resources for the Vitals app (Capacitor shell, minSdk 26). Run: node scripts/brand/android.mjs
// Every XML is built from the mark source (mark.mjs: readMark, PALETTE), so a change to public/brand/mark.svg or
// mark-small.svg flows through. Writes apps/android/brand/res/** (an Android res folder L-ANDROID copies or
// references), the Play Store icon and launcher-mask previews. apps/android/brand/README.md says how to wire them.
//
//   values(-night)/vitals_brand_colors.xml   launcher background (light in both modes), ink, signal, edge, splash ground
//   adaptive icon                            foreground + background + monochrome, mark inside the 66 dp safe circle
//   animated splash (Android 12+)            ring draws on (trim 0.05 → 1, 500 ms), then the dot pops in; ends by 640 ms
//   ic_stat_vitals                           white notification glyph from the small cut, inside the 20 dp live area
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import sharp from 'sharp';
import { GRID, PALETTE, ROOT, readMark } from './mark.mjs';

export const OUT_DIR = path.join(ROOT, 'apps', 'android', 'brand');
export const RES_DIR = path.join(OUT_DIR, 'res');

/** Adaptive icon: the mark's outer radius (33.5) × 0.76 ≈ 25.5 dp, well inside the 33 dp safe radius. Same as Lumen's mono. */
export const LAUNCHER_SCALE = 0.76;
/** Splash: 33.5 × 0.8 = 26.8 of the 36 viewport units that the 192 dp circle covers on the 288 dp icon. */
export const SPLASH_SCALE = 0.8;
/** Notification glyph (small cut, outer radius 35) × 1.2 = 42 of 108 units ≈ 9.3 dp, inside the 10 dp half live area. */
export const STAT_SCALE = 1.2;

export const SPLASH = { ringMs: 500, dotOffsetMs: 420, dotMs: 220, totalMs: 700, overshootTension: 1.2 };

const C = GRID / 2;
const NS = 'xmlns:android="http://schemas.android.com/apk/res/android"';
const HEAD = '<?xml version="1.0" encoding="utf-8"?>\n';
const fmt = (n) => String(Number(n.toFixed(3)));

/** A circle as path data (two arcs): Android vectors have no <circle>. */
export const circlePath = ({ cx, cy, r }) =>
  `M${fmt(cx - r)},${fmt(cy)} A${fmt(r)},${fmt(r)} 0,1 1,${fmt(cx + r)},${fmt(cy)} A${fmt(r)},${fmt(r)} 0,1 1,${fmt(cx - r)},${fmt(cy)} Z`;

const scaleGroup = (scale, body, name = '') =>
  `    <group${name ? ` android:name="${name}"` : ''} android:pivotX="${C}" android:pivotY="${C}" android:scaleX="${scale}" android:scaleY="${scale}">\n${body}    </group>\n`;

const vector = (dp, body) =>
  `${HEAD}<vector ${NS}\n    android:width="${dp}dp" android:height="${dp}dp" android:viewportWidth="${GRID}" android:viewportHeight="${GRID}">\n${body}</vector>\n`;

const ringPath = (m, stroke, name = '') =>
  `        <path${name ? ` android:name="${name}"` : ''} android:fillColor="@android:color/transparent" android:strokeColor="${stroke}"\n` +
  `            android:strokeWidth="${m.stroke}" android:strokeLineCap="round" android:strokeLineJoin="round"\n` +
  `            android:pathData="${m.d}" />\n`;

const dotPath = (m, fill, edge, indent = '        ') =>
  `${indent}<path android:fillColor="${fill}"${edge ? ` android:strokeColor="${edge}" android:strokeWidth="${m.dot.edge}"` : ''}\n` +
  `${indent}    android:pathData="${circlePath(m.dot)}" />\n`;

/** Android colour value for a palette entry; null (no edge) becomes fully transparent. */
const androidColour = (hex) => (hex ?? '#00000000');

const colours = (tone) => {
  const p = PALETTE[tone];
  const rows = [
    ['vitals_launcher_background', PALETTE.light.ground, 'launcher icon ground: light in both modes'],
    ['vitals_mark_ink', p.ink, 'the ring'],
    ['vitals_mark_signal', p.signal, 'the dot'],
    ['vitals_mark_edge', androidColour(p.edge), 'thin edge round the dot (light grounds only)'],
    ['vitals_splash_background', p.ground, 'splash ground'],
  ];
  return (
    `${HEAD}<!-- Generated by scripts/brand/android.mjs from scripts/brand/mark.mjs (PALETTE.${tone}). Do not edit. -->\n<resources>\n` +
    rows.map(([name, hex, note]) => `    <!-- ${note} -->\n    <color name="${name}">${hex}</color>\n`).join('') +
    '</resources>\n'
  );
};

/** The resources, keyed by path under res/. */
export function androidResources() {
  const m = readMark('mark.svg');
  const small = readMark('mark-small.svg');
  const light = PALETTE.light;
  const dotPivot = `android:pivotX="${m.dot.cx}" android:pivotY="${m.dot.cy}"`;

  return {
    'values/vitals_brand_colors.xml': colours('light'),
    'values-night/vitals_brand_colors.xml': colours('dark'),

    // Fixed colours: the launcher background is light in both modes, so the foreground never follows night mode.
    'drawable/vitals_launcher_foreground.xml': vector(
      108,
      scaleGroup(LAUNCHER_SCALE, ringPath(m, light.ink) + dotPath(m, light.signal, light.edge)),
    ),
    'drawable/vitals_launcher_background.xml': vector(
      108,
      `    <path android:fillColor="@color/vitals_launcher_background" android:pathData="M0,0 H${GRID} V${GRID} H0 Z" />\n`,
    ),
    // Themed icons (Android 13+): the launcher tints this; only white, the dot filled, no edge.
    'drawable/vitals_launcher_monochrome.xml': vector(
      108,
      scaleGroup(LAUNCHER_SCALE, ringPath(m, '#ffffff') + dotPath(m, '#ffffff', null)),
    ),
    ...Object.fromEntries(
      ['ic_launcher', 'ic_launcher_round'].map((name) => [
        `mipmap-anydpi-v26/${name}.xml`,
        `${HEAD}<adaptive-icon ${NS}>\n` +
          '    <background android:drawable="@drawable/vitals_launcher_background" />\n' +
          '    <foreground android:drawable="@drawable/vitals_launcher_foreground" />\n' +
          '    <monochrome android:drawable="@drawable/vitals_launcher_monochrome" />\n' +
          '</adaptive-icon>\n',
      ]),
    ),

    // Splash icon (no icon background): 288 dp, the content must fit the centre 192 dp circle.
    'drawable/vitals_splash_mark.xml': vector(
      288,
      scaleGroup(
        SPLASH_SCALE,
        ringPath(m, '@color/vitals_mark_ink', 'ring') +
          `        <group android:name="dot" ${dotPivot} android:scaleX="0" android:scaleY="0">\n` +
          dotPath(m, '@color/vitals_mark_signal', '@color/vitals_mark_edge', '            ') +
          '        </group>\n',
        'mark',
      ),
    ),
    'animator/vitals_splash_ring_draw.xml':
      `${HEAD}<objectAnimator ${NS}\n    android:propertyName="trimPathEnd" android:valueFrom="0.05" android:valueTo="1" android:valueType="floatType"\n` +
      `    android:duration="${SPLASH.ringMs}" android:interpolator="@android:interpolator/fast_out_slow_in" />\n`,
    'animator/vitals_splash_dot_pop.xml':
      `${HEAD}<set ${NS} android:ordering="together">\n` +
      ['scaleX', 'scaleY']
        .map(
          (prop) =>
            `    <objectAnimator android:propertyName="${prop}" android:valueFrom="0" android:valueTo="1" android:valueType="floatType"\n` +
            `        android:startOffset="${SPLASH.dotOffsetMs}" android:duration="${SPLASH.dotMs}" android:interpolator="@interpolator/vitals_splash_overshoot" />\n`,
        )
        .join('') +
      '</set>\n',
    // A small overshoot: the dot settles rather than bounces (the framework's overshoot uses tension 2).
    'interpolator/vitals_splash_overshoot.xml': `${HEAD}<overshootInterpolator ${NS} android:tension="${SPLASH.overshootTension}" />\n`,
    'drawable/vitals_splash_animated.xml':
      `${HEAD}<animated-vector ${NS}\n    android:drawable="@drawable/vitals_splash_mark">\n` +
      '    <target android:name="ring" android:animation="@animator/vitals_splash_ring_draw" />\n' +
      '    <target android:name="dot" android:animation="@animator/vitals_splash_dot_pop" />\n' +
      '</animated-vector>\n',

    // Status bar icon: Android tints it, so white only; the small cut stays open at 24 dp.
    'drawable/ic_stat_vitals.xml': vector(24, scaleGroup(STAT_SCALE, ringPath(small, '#ffffff') + dotPath(small, '#ffffff', null))),
  };
}

// ---------------------------------------------------------------------------------------------------------------
// A tiny XML reader and a vector-drawable → SVG converter, for the previews and the tests (no Android tooling here).

/**
 * @typedef {{ name: string, attrs: Record<string, string>, children: XmlNode[], text: string }} XmlNode
 */

/** Parses the subset of XML these resources use (declaration, comments, elements, attributes). Throws if malformed. */
export function parseXml(src) {
  const re = /<\?[\s\S]*?\?>|<!--[\s\S]*?-->|<\/([\w:.-]+)\s*>|<([\w:.-]+)((?:\s+[\w:.-]+\s*=\s*"[^"<]*")*)\s*(\/?)>|([^<]+)|(<)/g;
  /** @type {XmlNode} */
  const doc = { name: '#document', attrs: {}, children: [], text: '' };
  const stack = [doc];
  for (const t of src.matchAll(re)) {
    const [, close, open, attrSrc, selfClose, text, stray] = t;
    if (stray) throw new Error(`malformed XML near offset ${t.index}`);
    if (text !== undefined) {
      if (/&(?!(amp|lt|gt|quot|apos|#\d+);)/.test(text)) throw new Error(`stray & in "${text.trim().slice(0, 20)}"`);
      if (stack.length === 1 && text.trim()) throw new Error('text outside the root element');
      stack.at(-1).text += text.trim();
      continue;
    }
    if (close) {
      const top = stack.pop();
      if (!top || top.name !== close) throw new Error(`</${close}> closes <${top?.name}>`);
      continue;
    }
    if (!open) continue;
    /** @type {Record<string, string>} */
    const attrs = {};
    for (const [, k, v] of (attrSrc ?? '').matchAll(/([\w:.-]+)\s*=\s*"([^"]*)"/g)) {
      if (k in attrs) throw new Error(`duplicate attribute ${k}`);
      attrs[k] = v;
    }
    const node = { name: open, attrs, children: [], text: '' };
    stack.at(-1).children.push(node);
    if (!selfClose) stack.push(node);
  }
  if (stack.length !== 1) throw new Error(`unclosed <${stack.at(-1).name}>`);
  if (doc.children.length !== 1) throw new Error('expected one root element');
  return doc.children[0];
}

/** name → colour from a values XML. */
export function readColours(xml) {
  return Object.fromEntries(
    parseXml(xml)
      .children.filter((n) => n.name === 'color')
      .map((n) => [n.attrs.name, n.text]),
  );
}

/** Android colour (#RGB, #RRGGBB, #AARRGGBB, @color/x, @android:color/white|black|transparent) → SVG paint + opacity. */
function paint(value, colourMap) {
  if (!value) return null;
  let v = value;
  if (v.startsWith('@color/')) {
    v = colourMap[v.slice(7)];
    if (!v) throw new Error(`unknown colour ${value}`);
  }
  v = { '@android:color/white': '#ffffff', '@android:color/black': '#000000', '@android:color/transparent': '#00000000' }[v] ?? v;
  const hex = v.replace('#', '');
  if (hex.length === 8) {
    const alpha = parseInt(hex.slice(0, 2), 16) / 255;
    return alpha === 0 ? null : { colour: `#${hex.slice(2)}`, alpha };
  }
  if (hex.length === 6 || hex.length === 3) return { colour: `#${hex}`, alpha: 1 };
  throw new Error(`unsupported colour ${value}`);
}

const A = (n, k) => n.attrs[`android:${k}`];
const num = (n, k, d) => (A(n, k) === undefined ? d : Number(A(n, k)));

/** Android's group matrix: translate(-pivot), scale, rotate, translate(translate + pivot). */
const groupTransform = (g) => {
  const [px, py] = [num(g, 'pivotX', 0), num(g, 'pivotY', 0)];
  return (
    `translate(${num(g, 'translateX', 0) + px} ${num(g, 'translateY', 0) + py}) rotate(${num(g, 'rotation', 0)}) ` +
    `scale(${num(g, 'scaleX', 1)} ${num(g, 'scaleY', 1)}) translate(${-px} ${-py})`
  );
};

/** SVG elements (no <svg> wrapper) for a vector drawable's contents in its viewport coordinates. */
export function vectorBody(xml, colourMap = {}) {
  const root = parseXml(xml);
  if (root.name !== 'vector') throw new Error(`expected <vector>, got <${root.name}>`);
  const walk = (n) => {
    if (n.name === 'group') return `<g transform="${groupTransform(n)}">${n.children.map(walk).join('')}</g>`;
    if (n.name !== 'path') throw new Error(`unsupported element <${n.name}>`);
    const fill = paint(A(n, 'fillColor'), colourMap);
    const stroke = paint(A(n, 'strokeColor'), colourMap);
    const attrs = [`d="${A(n, 'pathData')}"`, `fill="${fill ? fill.colour : 'none'}"`];
    if (fill && fill.alpha * num(n, 'fillAlpha', 1) < 1) attrs.push(`fill-opacity="${fill.alpha * num(n, 'fillAlpha', 1)}"`);
    if (A(n, 'fillType') === 'evenOdd') attrs.push('fill-rule="evenodd"');
    if (stroke && num(n, 'strokeWidth', 0) > 0) {
      attrs.push(`stroke="${stroke.colour}"`, `stroke-width="${num(n, 'strokeWidth', 0)}"`);
      if (stroke.alpha * num(n, 'strokeAlpha', 1) < 1) attrs.push(`stroke-opacity="${stroke.alpha * num(n, 'strokeAlpha', 1)}"`);
      attrs.push(`stroke-linecap="${A(n, 'strokeLineCap') ?? 'butt'}"`, `stroke-linejoin="${A(n, 'strokeLineJoin') ?? 'miter'}"`);
    }
    return `<path ${attrs.join(' ')}/>`;
  };
  return { width: num(root, 'viewportWidth', GRID), height: num(root, 'viewportHeight', GRID), body: root.children.map(walk).join('') };
}

/** A vector drawable as a standalone SVG string (same viewport). */
export function vectorToSvg(xml, colourMap = {}) {
  const { width, height, body } = vectorBody(xml, colourMap);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">${body}</svg>`;
}

/** Common launcher masks (AOSP shape paths on a 100 box), applied to the visible 72 dp of the 108 dp layers. */
export const LAUNCHER_MASKS = {
  circle: 'M50,0 A50,50 0,1 1,50,100 A50,50 0,1 1,50,0 Z',
  squircle: 'M50,0 C10,0 0,10 0,50 C0,90 10,100 50,100 C90,100 100,90 100,50 C100,10 90,0 50,0 Z',
  'rounded-square':
    'M50,0 L92,0 C96.42,0 100,3.58 100,8 L100,92 C100,96.42 96.42,100 92,100 L8,100 C3.58,100 0,96.42 0,92 L0,8 C0,3.58 3.58,0 8,0 Z',
  teardrop: 'M50,0 A50,50 0,0 1 100,50 L100,85 A15,15 0,0 1 85,100 L50,100 A50,50 0,0 1 0,50 A50,50 0,0 1 50,0 Z',
};
/** The visible part of the adaptive layers: the centre 72 of 108 dp. */
const VISIBLE = 72;
const INSET = (GRID - VISIBLE) / 2;
const maskTransform = `translate(${INSET} ${INSET}) scale(${VISIBLE / 100})`;

/** A launcher mask on the 108 grid, filled black on transparent (for rasterising and comparing alpha). */
export const maskSvg = (name) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${GRID} ${GRID}"><path transform="${maskTransform}" d="${LAUNCHER_MASKS[name]}"/></svg>`;

/** Background + foreground through a mask, cropped to the visible 72 dp (or unmasked, full square, when mask is null). */
export function launcherSvg(backgroundXml, foregroundXml, colourMap, mask) {
  const bg = vectorBody(backgroundXml, colourMap).body;
  const fg = vectorBody(foregroundXml, colourMap).body;
  const clip = mask ? `<clipPath id="m"><path transform="${maskTransform}" d="${LAUNCHER_MASKS[mask]}"/></clipPath>` : '';
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${INSET} ${INSET} ${VISIBLE} ${VISIBLE}">${clip}` +
    `<g${mask ? ' clip-path="url(#m)"' : ''}>${bg}${fg}</g></svg>`
  );
}

/** Rasterises an SVG string to a size × size PNG buffer (librsvg through sharp). */
export const rasterise = (svg, size) => {
  const box = Number(svg.match(/viewBox="[\d.-]+ [\d.-]+ ([\d.]+)/)?.[1] ?? GRID);
  return sharp(Buffer.from(svg), { density: (72 * size) / box }).resize(size, size).png({ compressionLevel: 9 }).toBuffer();
};

const README = `# Vitals Android brand resources

Generated by \`node scripts/brand/android.mjs\` (also run by \`scripts/brand/generate.mjs\`) from
\`public/brand/mark.svg\` and \`mark-small.svg\`. Do not edit the files here by hand: change the source SVG and
regenerate.

## Wiring (for the Capacitor app)

1. Add \`apps/android/brand/res\` as a res folder of the app module (or copy its contents into
   \`app/src/main/res\`), e.g. in \`app/build.gradle\`:

   \`\`\`groovy
   android { sourceSets { main { res.srcDirs += ['../../brand/res'] } } }
   \`\`\`

   Remove Capacitor's default \`mipmap-*/ic_launcher*\` files and \`mipmap-anydpi-v26/ic_launcher*.xml\` so these win.

2. \`AndroidManifest.xml\`, on \`<application>\`:

   \`\`\`xml
   android:icon="@mipmap/ic_launcher"
   android:roundIcon="@mipmap/ic_launcher_round"
   \`\`\`

3. Splash (Android 12+, \`values-v31\` theme of the launch activity):

   \`\`\`xml
   <item name="android:windowSplashScreenBackground">@color/vitals_splash_background</item>
   <item name="android:windowSplashScreenAnimatedIcon">@drawable/vitals_splash_animated</item>
   <item name="android:windowSplashScreenAnimationDuration">${SPLASH.totalMs}</item>
   \`\`\`

   The ring draws on in ${SPLASH.ringMs} ms, the dot pops in from ${SPLASH.dotOffsetMs} ms and settles by
   ${SPLASH.dotOffsetMs + SPLASH.dotMs} ms; it plays once. Light and night grounds come from
   \`values(-night)/vitals_brand_colors.xml\`. With animations off Android shows the finished mark.

4. Notifications: \`setSmallIcon(R.drawable.ic_stat_vitals)\` (white only; Android tints it).

## Files

- \`res/mipmap-anydpi-v26/ic_launcher.xml\`, \`ic_launcher_round.xml\`: adaptive icon (background, foreground,
  monochrome for themed icons). The launcher ground stays light in night mode.
- \`res/drawable/vitals_launcher_{foreground,background,monochrome}.xml\`
- \`res/drawable/vitals_splash_mark.xml\`, \`vitals_splash_animated.xml\`, \`res/animator/vitals_splash_*.xml\`,
  \`res/interpolator/vitals_splash_overshoot.xml\`
- \`res/drawable/ic_stat_vitals.xml\`
- \`res/values/vitals_brand_colors.xml\`, \`res/values-night/vitals_brand_colors.xml\`
- \`playstore-512.png\`: Play Store icon (512 px, full bleed; Play applies its own corner mask).
- \`preview/launcher-*.png\`: how the adaptive icon looks through common launcher masks (documentation only).
`;

/** Writes the res folder, the Play Store icon, the previews and the README. Returns the written paths. */
export async function writeAndroid() {
  const res = androidResources();
  const written = [];
  const put = async (file, data) => {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, data);
    written.push(file);
  };
  for (const [rel, xml] of Object.entries(res)) await put(path.join(RES_DIR, rel), xml);

  const colourMap = readColours(res['values/vitals_brand_colors.xml']);
  const bg = res['drawable/vitals_launcher_background.xml'];
  const fg = res['drawable/vitals_launcher_foreground.xml'];
  await put(path.join(OUT_DIR, 'playstore-512.png'), await rasterise(launcherSvg(bg, fg, colourMap, null), 512));
  for (const mask of Object.keys(LAUNCHER_MASKS)) {
    await put(path.join(OUT_DIR, 'preview', `launcher-${mask}.png`), await rasterise(launcherSvg(bg, fg, colourMap, mask), 432));
  }
  await put(path.join(OUT_DIR, 'README.md'), README);
  return written;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const written = await writeAndroid();
  console.log(`${written.length} Android brand files written to`, path.relative(ROOT, OUT_DIR));
}
