// Vitals lockups, README header, social preview and OG image, composed from the mark (mark.mjs, which reads
// public/brand/mark.svg) and the outlined wordmark (public/brand/wordmark.svg). The tagline is an outline too
// (scripts/brand/tagline-outline.json), so no <text> element exists anywhere and renders never need an installed font.
// Run: node scripts/brand/lockup.mjs   (the extractor scripts/brand/wordmark-outline.py is not part of this run)
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import sharp from 'sharp';
import { BRAND_DIR, GRID, PALETTE, ROOT, markShapes, readMark } from './mark.mjs';

// ---- proportions (the lockup is drawn with its x-height = 100 units) -------------------------------------------------
const XH = 100;
const RING_D = 1.5 * XH; // outer diameter of the ring, in units: one and a half x-heights
const GAP = 0.42 * XH; // between the ring's outer edge and the "v"
const TAG_ALPHA = 0.74; // the tagline is the ink colour, softened

const fmt = (n) => String(Math.round(n * 100) / 100);

async function readWordmark() {
  const src = await readFile(path.join(BRAND_DIR, 'wordmark.svg'), 'utf8');
  const vb = src.match(/viewBox="([-\d.\s]+)"/)?.[1].trim().split(/\s+/).map(Number);
  const d = src.match(/<path id="wordmark" d="([^"]+)"/)?.[1];
  const xh = Number(src.match(/x-height is y=-(\d+)/)?.[1]);
  if (!vb || vb.length !== 4 || !d || !xh) throw new Error('wordmark.svg: viewBox, path or x-height missing');
  return { x0: vb[0], y0: vb[1], w: vb[2], h: vb[3], d, xh };
}

async function readTagline() {
  const t = JSON.parse(await readFile(path.join(ROOT, 'scripts', 'brand', 'tagline-outline.json'), 'utf8'));
  const [x0, y0, x1, y1] = t.bounds;
  return { d: t.d, upem: t.unitsPerEm, x0, y0, w: x1 - x0, h: y1 - y0 };
}

/**
 * The lockup in its own units: ring mark at the left, "vitals" after it. The ring's centre sits on the word's
 * x-height centre. Returns the SVG body and the tight box it occupies (top may be negative: y=0 is the baseline).
 * @param {'light' | 'dark' | 'mono'} tone
 */
async function lockupBody(tone) {
  const wm = await readWordmark();
  const k = XH / wm.xh; // font units -> lockup units
  const ring = readMark('mark.svg');
  const half = ring.stroke / 2;
  const s = RING_D / (2 * (30 + half)); // the grid's ring radius is 30; scale so the outer edge is RING_D wide
  const colour = tone === 'mono' ? 'currentColor' : PALETTE[tone].ink;
  const cy = -XH / 2;
  const left = -(GRID / 2 - 30 - half) * s; // grid x of the ring's left edge, moved to x=0
  const markX = left;
  const markY = cy - (GRID / 2) * s;
  const wordX = RING_D + GAP - wm.x0 * k;
  const top = Math.min(cy - RING_D / 2, wm.y0 * k);
  const bottom = Math.max(cy + RING_D / 2, (wm.y0 + wm.h) * k);
  const width = RING_D + GAP + wm.w * k;
  const body =
    `<g transform="translate(${fmt(markX)} ${fmt(markY)}) scale(${fmt(s)})">${markShapes({ tone, mono: 'currentColor' })}</g>` +
    `<path transform="translate(${fmt(wordX)} 0) scale(${fmt(k)})" fill="${colour}" d="${wm.d}"/>`;
  return { body, width, top, height: bottom - top };
}

/** A standalone lockup SVG (transparent), viewBox tight to the shapes. */
async function lockupSvg(tone) {
  const { body, width, top, height } = await lockupBody(tone);
  const w = fmt(width);
  const h = fmt(height);
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 ${fmt(top)} ${w} ${h}" width="${Math.round(width * 2)}" height="${Math.round(height * 2)}">\n` +
    `  <title>Vitals</title>\n` +
    `  <!-- Generated by scripts/brand/lockup.mjs: the mark, then "vitals" as outlines (no live text). Baseline at y=0. -->\n` +
    `  ${body}\n</svg>\n`
  );
}

/**
 * A card: ground, the lockup and the tagline under it, as one block (left edges aligned).
 * `xh` is the lockup's x-height in pixels; `tagPx` the tagline's font size in pixels.
 * align 'left' puts the block at `margin` from the left edge, 'center' centres it.
 */
async function cardSvg({ tone, width, height, xh, tagPx, margin, align }) {
  const p = PALETTE[tone];
  const lk = await lockupBody(tone);
  const tag = await readTagline();
  const u = xh / XH; // lockup units -> px
  const kt = tagPx / tag.upem; // tagline font units -> px
  const lockW = lk.width * u;
  const lockH = lk.height * u;
  const tagW = tag.w * kt;
  const gap = tagPx * 1.15; // lockup bottom to tagline cap top
  const tagH = (-tag.y0 + 0) * kt; // cap top to baseline (no descender counted; descenders hang into the margin)
  const blockW = Math.max(lockW, tagW);
  const blockH = lockH + gap + tagH;
  const x = align === 'center' ? (width - blockW) / 2 : margin;
  const y = (height - blockH) / 2;
  const lockTx = x;
  const lockTy = y - lk.top * u; // lk.top is negative: lift the baseline so the top lands on y
  const tagTx = x - tag.x0 * kt;
  const tagTy = y + lockH + gap + tagH;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">\n` +
    `  <title>Vitals: See what a plan does before you live it.</title>\n` +
    `  <rect width="${width}" height="${height}" fill="${p.ground}"/>\n` +
    `  <g transform="translate(${fmt(lockTx)} ${fmt(lockTy)}) scale(${fmt(u)})">${lk.body}</g>\n` +
    `  <path transform="translate(${fmt(tagTx)} ${fmt(tagTy)}) scale(${fmt(kt)})" fill="${p.ink}" fill-opacity="${TAG_ALPHA}" d="${tag.d}"/>\n` +
    `</svg>\n`
  );
}

const png = (svg, width, height) =>
  sharp(Buffer.from(svg), { density: 288 }).resize(width, height, { fit: 'fill' }).png({ compressionLevel: 9 }).toBuffer();

/** @returns {Promise<string[]>} the files written */
export async function writeLockups() {
  await mkdir(BRAND_DIR, { recursive: true });
  const out = [];
  const put = async (name, data) => {
    await writeFile(path.join(BRAND_DIR, name), data);
    out.push(path.join('public', 'brand', name));
  };

  for (const tone of ['light', 'dark', 'mono']) await put(`lockup-${tone}.svg`, await lockupSvg(tone));

  const lightLockup = await lockupSvg('light');
  const vb = lightLockup.match(/viewBox="0 [-\d.]+ ([\d.]+) ([\d.]+)"/);
  await put('lockup-light-512w.png', await png(lightLockup, 512, Math.round((512 * Number(vb[2])) / Number(vb[1]))));

  const header = { width: 1280, height: 320, xh: 62, tagPx: 30, margin: 96, align: 'left' };
  await put('readme-header.svg', await cardSvg({ tone: 'light', ...header }));
  await put('readme-header-dark.svg', await cardSvg({ tone: 'dark', ...header }));

  const social = { tone: 'light', width: 1280, height: 640, xh: 100, tagPx: 40, margin: 0, align: 'center' };
  await put('social-preview.png', await png(await cardSvg(social), 1280, 640));
  const og = { ...social, width: 1200, height: 630 };
  await put('og-image.png', await png(await cardSvg(og), 1200, 630));
  return out;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  for (const f of await writeLockups()) console.log(`wrote ${f}`);
}
