import fs from 'node:fs'; import path from 'node:path'; import { execFile } from 'node:child_process';
import { chromium, newPage, repo, shot } from './lib.mjs';
import { onboard } from '../j1/onboard.mjs';
const cfg = JSON.parse(fs.readFileSync(path.join(repo, 'qa', 'local.config.json'), 'utf8'));
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox', '--disable-features=LocalNetworkAccessChecks,LocalNetworkAccessPermissionPolicy,PrivateNetworkAccessSendPreflights,BlockInsecurePrivateNetworkRequests'] });
const { ctx, page } = await newPage(browser);
const log = (m) => console.log(String(m).split(cfg.serverUrl).join('<server>').slice(0, 300));
await ctx.route('https://localhost/**', async (route) => { const u = new URL(route.request().url()); const t = Date.now(); try { const r = await route.fetch({ url: 'http://127.0.0.1:4337' + u.pathname + u.search }); await route.fulfill({ response: r }); if (Date.now() - t > 3000) log('slow ' + u.pathname + ' ' + (Date.now() - t)); } catch (e) { log('route fail ' + u.pathname); await route.abort(); } });
page.on('response', (r) => { if (r.status() >= 400) log('HTTP ' + r.status() + ' ' + r.url().slice(0, 120)); });
page.on('requestfailed', (r) => log('reqfailed ' + r.url().slice(0, 100) + ' ' + r.failure()?.errorText));
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') log('console ' + m.text().slice(0, 200)); });
ctx.on('page', (p) => log('page')); page.on('worker', (w) => log('worker ' + w.url().slice(0, 100)));
await page.goto('https://localhost/', { waitUntil: 'load' });
await page.waitForFunction(() => document.querySelectorAll('button, a[href]').length > 0, null, { timeout: 90000 });
await onboard(page, () => {});
await page.goto('https://localhost/', { waitUntil: 'load' }); await page.waitForTimeout(5000);
console.log('COI', await page.evaluate(() => ({ coi: self.crossOriginIsolated, opfs: !!navigator.storage?.getDirectory, sw: self.SharedWorker !== undefined })));
const t = Date.now();
const r = await page.evaluate(async () => { const m = await import('/src/commands/index.ts'); const x = await m.dispatch('sync.status', {}); return x.ok ? x.output : x.error; });
console.log(JSON.stringify(r).slice(0, 200), Date.now() - t);
await browser.close();
