/** Settings › Sync copy. Plain and short, like the rest of Settings. */
export const SYNC_COPY = {
  intro: 'Your data stays on this device until you set up sync. Your sync server only ever holds encrypted data it cannot read.',
  lnaHint: 'Chrome may ask to “connect to devices on your local network”. Allow it so Vitals can reach your server.',
  serverLabel: 'sync server address',
  serverHelp: 'The address of your Vitals server, for example https://myserver.tailnet.ts.net',
  serverPlaceholder: 'https://myserver.tailnet.ts.net',
  setUp: 'Set up sync on this device',
  throughServer: 'On · through your server',
  serverSettings: 'Server settings',
  fromServer: 'The address of your paired server is filled in. Set up sync here if this is your first device, or join with the words or QR from another device.',
  test: 'Test',
  testing: 'Testing…',
  testOk: (version: string | null, ms: number) => `Reached the server${version ? ` · version ${version}` : ''} · ${ms} ms`,
  testNoAnswer: 'No answer from that address. Is the server running and is Tailscale on?',
  testNotRelay: "That address isn't a Vitals sync server.",
  testOffline: "Can't test now — you're offline.",
  join: 'Join with a pairing code',
  joinHelp: 'Paste the pairing code from your other device (it starts with vitals-sync:1?), or its 24 words.',
  joinWordsNeedServer: 'With the 24 words, also enter the sync server address above.',
  joinKey: 'Join',
  scan: 'Scan code',
  codeLabel: 'pairing code',
  existingTitle: 'This device already has data',
  existingBody: 'Merge it, or replace it with the synced data?',
  merge: 'Merge',
  replace: 'Replace with synced data',
  showCode: 'Show pairing code',
  hideCode: 'Hide',
  copyCode: 'Copy code',
  copied: 'Pairing code copied',
  codeWarning: 'Anyone with these words can read and change your Vitals data.',
  codeLoss: 'Lose every device and these 24 words, and the data is gone.',
  codeAutoHide: 'Hides itself after a minute.',
  savedWords: "I've saved the words",
  savedWordsNeeded: 'Write the 24 words down first, then tick the box.',
  saveAddress: 'Save address',
  serverKey: 'sync server',
  answersKey: 'answers now',
  answersChecking: 'checking…',
  answersYes: (ms?: number) => (ms === undefined ? 'yes' : `yes (${ms} ms)`),
  answersNo: 'no',
  serverVersionKey: 'server version',
  lastSyncKey: 'last sync',
  lastSyncNever: 'not yet',
  nameKey: 'name',
  checkServer: 'Check server',
  stop: 'Stop syncing on this device',
  stopTitle: 'Stop syncing on this device?',
  stopBody: 'This device stops syncing and forgets the pairing code. Your data stays here, and your other devices keep syncing.',
  stopConfirm: 'Stop syncing',
  syncNow: 'Sync now',
  syncing: 'Syncing…',
  syncOff: 'Sync is off on this device.',
  unreachable: "Can't reach your sync server. Is Tailscale on?",
  needsPermission: 'Your browser is blocking the connection to your sync server. Allow “devices on your local network” for this site in the site settings, then try again.',
  unavailable: "Sync isn't available in this version yet.",
  scanTitle: 'Scan the pairing code',
  scanHelp: 'Point the camera at the QR code on your other device.',
  cameraDenied: "Vitals can't use the camera. Allow camera access for this site in your browser settings, or paste the code instead.",
  noCamera: 'No camera found. Paste the code instead.',
  scanUnsupported: "This browser can't scan codes. Paste the code instead.",
  scanFailed: "The camera didn't start. Paste the code instead.",
} as const;

export const STATE_LABEL = {
  off: 'off',
  connecting: 'connecting',
  synced: 'synced',
  syncing: 'syncing',
  offline: 'offline',
  error: 'error',
  'needs-permission': 'blocked',
} as const;
