/** Words of the catalogue picker (plain words only; scanned by the picker's copy test). */
export const PICKER_COPY = {
  searchPlaceholder: (n: number) => `Search ${n} items`,
  searchLabel: (label: string) => `Search ${label.toLowerCase()}`,
  clearSearch: 'Clear search',
  matches: (n: number) => (n === 1 ? '1 match' : `${n} matches`),
  noMatch: (q: string) => `No match for '${q}'`,
  addOwn: 'Add it as your own item',
  selected: (n: number) => `${n} selected`,
  regionNote: (region: string) => `Pre-ticked: defaults for a ${region} kitchen. Untick what you don't have.`,
  noDefaults: "No defaults for your region; pick what you have.",
  regionOffer: (region: string) => `Nothing is pre-ticked. Tick what you have, or start from the usual items for a ${region} kitchen.`,
  tickDefaults: (region: string) => `Tick the usual items for a ${region} kitchen`,
  otherRegion: 'Use another region',
  clearDefaults: 'Clear defaults',
  defaultFor: (region: string) => `default for ${region}`,
  groupCount: (n: number, total: number) => `${n} of ${total}`,
  clear: 'clear',
  clearGroup: (group: string) => `Clear ${group}`,
  cleared: (group: string) => `Cleared ${group}`,
  undo: 'Undo',
  addedGroup: 'added by you',
  matching: 'matching…',
  matched: (label: string) => `matched: ${label}`,
  keptAsWritten: 'kept as you wrote it',
  remove: (label: string) => `Remove ${label}`,
  alsoHave: 'I also have…',
  alsoHavePlaceholder: { equipment: 'e.g. a waffle maker', cuisines: 'e.g. Bhojpuri home cooking', staples: 'e.g. hand-pounded rice', pantry: 'e.g. leftover dal, 2 mangoes' } as const,
  add: 'Add',
  paste: 'Paste a list',
  pasteLabel: 'Your list',
  pastePlaceholder: 'One item per line, or separated by commas',
  readList: 'Read the list',
  pasteSummary: (matched: number, kept: number) => `${matched} matched · ${kept} kept as written`,
  addItems: (n: number) => (n === 1 ? 'Add 1 item' : `Add ${n} items`),
  keptTag: 'kept as written',
  optional: "Optional. Skip this if you like — you can tell the Coach 'right now I have these at home' whenever you want.",
  loadError: "Couldn't load the list. Try again.",
  retry: 'Try again',
  loading: 'Loading the list',
  editNote: (label: string) => `Note for ${label}`,
  notePlaceholder: 'e.g. small OTG, 28 L',
  notePlaceholderPantry: 'e.g. about 1 kg',
  noteLabel: 'note',
  ownNotUsed: "I own it but don't use it",
  notUsed: 'not used',
  done: 'Done',
  rank: (n: number) => `number ${n} in your order`,
} as const;
