import { open, BASE, shot, text } from './lib.mjs';
const mobile = process.argv[2] === 'mobile';
const { browser, page, errors } = await open({ mobile, profile: 'p1' });
await page.clock.install({ time: new Date('2026-10-03T01:30:00') });
const T = async (n = 1800, from = 'Targets') => { const t = (await text(page, 14000)); const i = t.indexOf(from); return t.slice(Math.max(0, i), i + n).replace(/\n+/g, ' / '); };
await page.goto(BASE + '/food', { waitUntil: 'networkidle' }); await page.waitForTimeout(2500);
console.log('HEADER', (await text(page, 80)).replace(/\n+/g, ' / '));
await page.getByRole('button', { name: 'Plan my day' }).click();
await page.getByText('QA dal bowl').first().waitFor({ timeout: 60000 }); await page.waitForTimeout(1000);
await page.getByRole('button', { name: /^Accept .* for breakfast/ }).click(); await page.waitForTimeout(1000);
console.log('AFTER ACCEPT', (await T(900, 'Meals')));
await page.getByRole('button', { name: 'I ate this: breakfast as planned' }).click(); await page.waitForTimeout(2500);
console.log('AFTER ATE', await T(1500));
await shot(page, mobile ? '28-ate-this-m' : '27-ate-this');
await page.goto(BASE + '/today', { waitUntil: 'networkidle' }); await page.waitForTimeout(2500);
console.log('TODAY', (await text(page, 2500)).replace(/\n+/g, ' / ').slice(0, 1500));
await shot(page, mobile ? '29-today-after-m' : '28-today-after');
console.log('ERRORS', errors);
await browser.close();
