// @vitest-environment node
/**
 * The synthetic Indian-layout reports in qa/fixtures/markers (generated by generate.ts; every value is invented):
 * ≥ 95 % of the Tier A rows with the right value and unit, calculated rows handled, the sample date, textless pages.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { extractFromFile, type ExtractResult } from '../index';
import { extractTextItems, loadPdfjsLegacy } from '../pdf';
import { convert } from '../../units';
import type { MarkerId } from '../../types';

/** Same unit or an exact alias of it (µIU/mL = µU/mL for insulin). */
const sameUnit = (id: MarkerId, a: string | null, b: string): boolean => a === b || (a !== null && convert(id, 1, a, b) === 1);

const DIR = join(import.meta.dirname, '../../../../qa/fixtures/markers');

interface Expected {
  file: string;
  sampleDate: string;
  textlessPages: number[];
  patient: Record<string, string>;
  tierA: Array<{
    markerId: string;
    nameOnReport: string;
    value: number;
    unit: string;
    calculated: boolean;
    issue?: string;
  }>;
  imageOnly: Array<{ markerId: string }>;
  droppedCalculated: string[];
}

const PDFS = ['thyro-style', 'srl-style', 'fullbody-multipage', 'hospital-si'];
const load = (name: string) => ({
  bytes: new Uint8Array(readFileSync(join(DIR, `${name}.pdf`))),
  expected: JSON.parse(readFileSync(join(DIR, `${name}.expected.json`), 'utf8')) as Expected,
});

const textItems = (bytes: Uint8Array, o: { onPage?: (p: number, n: number) => void; signal?: AbortSignal }) =>
  extractTextItems(bytes, { ...o, load: loadPdfjsLegacy });

const results = new Map<string, ExtractResult>();
async function read(name: string): Promise<ExtractResult> {
  if (!results.has(name)) {
    const { bytes } = load(name);
    results.set(
      name,
      await extractFromFile({ bytes, mime: 'application/pdf', name: `${name}.pdf` }, { textItems }),
    );
  }
  return results.get(name)!;
}

describe('synthetic report PDFs (text layer)', () => {
  it.each(PDFS)('%s: Tier A rows with correct values and units', async (name) => {
    const { expected } = load(name);
    const x = await read(name);
    expect(x.route).toBe('textLayer');
    let hits = 0;
    const misses: string[] = [];
    for (const e of expected.tierA) {
      const row = x.rows.find((r) => r.markerId === e.markerId && r.nameOnReport === e.nameOnReport);
      if (
        row &&
        row.value !== null &&
        Math.abs(row.value - e.value) < 1e-9 &&
        sameUnit(e.markerId as MarkerId, row.unit, e.unit) &&
        row.calculated === e.calculated
      )
        hits++;
      else misses.push(`${e.markerId} ${e.nameOnReport}: ${JSON.stringify(row ?? null)}`);
    }
    expect(misses, misses.join('\n')).toEqual([]);
    expect(hits / expected.tierA.length).toBeGreaterThanOrEqual(0.95);
    // nothing confirmable that the report does not carry
    for (const r of x.rows)
      expect(
        expected.tierA.some((e) => e.markerId === r.markerId && e.nameOnReport === r.nameOnReport),
        r.nameOnReport,
      ).toBe(true);
  });

  it('finds ≥ 95 % of all Tier A rows across the four layouts', async () => {
    let total = 0;
    let found = 0;
    for (const name of PDFS) {
      const { expected } = load(name);
      const x = await read(name);
      for (const e of expected.tierA) {
        total++;
        if (x.rows.some((r) => r.markerId === e.markerId && r.value === e.value && r.unit === e.unit))
          found++;
      }
    }
    expect(total).toBeGreaterThanOrEqual(55);
    expect(found / total).toBeGreaterThanOrEqual(0.95);
  });

  it.each(PDFS)('%s: sample date is the collection date', async (name) => {
    const x = await read(name);
    expect(x.sampleDate).toBe(load(name).expected.sampleDate);
  });

  it.each(PDFS)('%s: calculated Tier A rows are shown, not offered', async (name) => {
    const { expected } = load(name);
    const x = await read(name);
    for (const n of expected.droppedCalculated) {
      expect(x.rows.some((r) => r.nameOnReport === n)).toBe(false);
      expect(x.displayOnly.some((d) => d.name === n)).toBe(true);
    }
  });

  it.each(PDFS)('%s: no patient details anywhere in the extraction', async (name) => {
    const { expected } = load(name);
    const json = JSON.stringify(await read(name));
    for (const v of Object.values(expected.patient)) expect(json).not.toContain(v);
  });

  it('thyro-style: the B12 unit slip is fixed and flagged; total T3 is shown only; high LDL is direct', async () => {
    const x = await read('thyro-style');
    const b12 = x.rows.find((r) => r.markerId === 'b12')!;
    expect(b12.unit).toBe('pg/mL');
    expect(b12.issues).toContain('"pq" read as pg; check this value');
    expect(b12.confidence).toBeLessThan(0.7);
    expect(x.rows.some((r) => r.markerId === 'ft3' && r.nameOnReport === 'FREE T3')).toBe(true);
    expect(x.displayOnly.some((d) => d.name === 'TOTAL TRIIODOTHYRONINE (T3)')).toBe(true);
    const ldl = x.rows.find((r) => r.markerId === 'ldl')!;
    expect(ldl).toMatchObject({
      value: 192,
      unit: 'mg/dL',
      method: 'direct',
      calculated: false,
      confidence: 1,
    });
    expect(x.displayOnly.find((d) => d.name === 'NON-HDL CHOLESTEROL')?.value).toBe('224');
    expect(x.notInReport).toContain('creatinine');
    expect(x.notInReport).not.toContain('nonHdl');
    expect(x.error).toBeUndefined();
  });

  it('srl-style: low eGFR, method lines under names, category ranges, the calculated LDL kept and marked', async () => {
    const x = await read('srl-style');
    expect(x.rows.find((r) => r.markerId === 'egfr')).toMatchObject({
      value: 47,
      unit: 'mL/min/1.73 m²',
      method: 'CKD-EPI 2021 equation',
      calculated: false,
    });
    expect(x.rows.find((r) => r.markerId === 'creatinine')?.method).toBe('Modified Jaffe, kinetic');
    const ldl = x.rows.find((r) => r.markerId === 'ldl')!;
    expect(ldl.calculated).toBe(true);
    expect(ldl.method).toBe('calculated');
    expect(ldl.issues[0]).toBe('calculated by the lab (Friedewald); a direct LDL is better');
    expect(ldl.confidence).toBeLessThanOrEqual(0.8);
    expect(ldl.labRange).toBe('Optimal : < 100; Near optimal : 100-129; Borderline High : 130-159');
    expect(x.rows.find((r) => r.markerId === 'uacr')).toMatchObject({
      value: 48,
      unit: 'mg/g',
      calculated: false,
    });
    expect(x.displayOnly.some((d) => d.name === 'A : G Ratio')).toBe(true);
    expect(x.displayOnly.some((d) => d.name === 'Bilirubin Total')).toBe(true);
  });

  it('fullbody: the calculated LDL goes to display when a direct LDL exists; CBC indices are display only', async () => {
    const x = await read('fullbody-multipage');
    expect(x.rows.filter((r) => r.markerId === 'ldl')).toHaveLength(1);
    expect(x.displayOnly.some((d) => d.name === 'LDL CHOLESTEROL (CALCULATED)')).toBe(true);
    for (const n of [
      'MCV',
      'MCHC',
      'PLATELET COUNT',
      'TOTAL LEUCOCYTE COUNT',
      'C-REACTIVE PROTEIN (CRP)',
      'IgE TOTAL',
    ])
      expect(
        x.displayOnly.some((d) => d.name === n),
        n,
      ).toBe(true);
    expect(x.rows.some((r) => r.markerId === 'hsCrp')).toBe(false);
    expect(x.displayOnly.find((d) => d.name === 'TOTAL LEUCOCYTE COUNT')?.value).toBe('7,240');
  });

  it('hospital-si: SI units, H/L flags, "<" values; the image-only page is reported unread', async () => {
    const x = await read('hospital-si');
    expect(x.rows.find((r) => r.markerId === 'creatinine')).toMatchObject({ value: 132, unit: 'µmol/L' });
    const b12 = x.rows.find((r) => r.markerId === 'b12')!;
    expect(b12.value).toBe(111);
    expect(b12.issues.join(' ')).toMatch(/printed as < 111/);
    expect(x.unreadPages).toEqual([2]);
    expect(x.error).toBe('partial');
    expect(x.message).toBe('1 page couldn’t be read.');
    for (const e of load('hospital-si').expected.imageOnly) expect(x.notInReport).toContain(e.markerId);
  });

  it('reports progress per page', async () => {
    const { bytes } = load('fullbody-multipage');
    const seen: string[] = [];
    await extractFromFile(
      { bytes, mime: 'application/pdf' },
      { textItems, onProgress: (p) => seen.push(`${p.stage} ${p.page}/${p.pages}`) },
    );
    expect(seen).toEqual(['reading 1/3', 'reading 2/3', 'reading 3/3', 'checking 3/3']);
  });
});
