/**
 * User-facing copy for the Coach (design/screens/living-mode.md, Coach section), its change cards and its composer.
 * Plain, specific, second person; the Coach relays, it never argues or moralises. No exclamation marks, no streaks.
 * Scanned by `src/features/living/__tests__/copy.test.ts`.
 */

export const COACH_COPY = {
  title: 'Coach',
  modelLine: (model: string, owner: string) => `${model} · ${owner}`,
  conversation: 'Conversation',
  logLabel: 'Conversation with the Coach',
  you: 'you',
  coach: 'coach',
  writing: 'The Coach is writing…',
  noProvider: {
    title: 'The Coach needs an AI provider.',
    body: 'Use your own OpenAI, Anthropic or other key, or a model on your computer.',
    setup: 'Set up a provider',
    byHand: 'You can log everything by hand on Today, Food and Train.',
  },
  /** A provider is configured but couldn't be set up (living-mode.md §7.5). */
  setupFailed: {
    title: 'The Coach couldn’t start with your AI provider.',
    reason: (problem: string) => `What went wrong: ${problem}`,
    fix: 'Check the AI provider',
  },
  /** Settings › AI provider. */
  settingsTo: '/settings/coach',
  composerReason: 'Connect an AI provider in Settings to chat. You can still log everything by hand.',
  emptyReady: 'Tell the Coach what you ate or did, ask why your weight moved, or ask for a change to your plan. Every change it makes shows here, and you can undo it.',
  emptyPlanning: 'No plan is running. Ask about your body, a what-if, or how to choose a plan.',
  planningPrompts: ['help me choose a plan', 'what would a 16:8 window change?', 'how fast can I lose 5 kg?'],
  stopped: 'Stopped. Proposals already made are still waiting below.',
  keyRefused: (provider: string) => `Your key was refused by ${provider}. Check it in Settings › AI provider.`,
  outOfCredit: 'Your provider says you’re out of credit (or at your plan’s limit). Nothing was logged.',
  rateLimited: (seconds: number) => `The provider is busy — trying again in ${seconds} s.`,
  rateLimitedNow: 'The provider is busy — trying again now.',
  // a browser reports "server not running" and "server refuses web pages" (CORS) as the same failure: name both
  cors: (provider: string) => `No answer from ${provider}: it may not be running or reachable, or it may not accept requests from a web page.`,
  corsFix: 'How to fix',
  corsCompanion: 'or pick a provider that runs through your Vitals server.',
  offline: 'You’re offline. Your message is kept; send it when you’re back.',
  offlineReason: 'You’re offline.',
  sendNow: 'Send now',
  notSent: 'not sent yet',
  discardKept: 'Discard',
  noTools: 'This model can answer and suggest logs, but can’t change anything in Vitals. Logs it suggests appear as cards for you to confirm.',
  basic: 'This model can log and answer questions, but not change your plan or run simulations.',
  safetyNoPlanning: 'In your current safety mode, plans can’t be changed here. I can still log and explain.',
  segment: 'Earlier days are summarised for the Coach. You can still read and search them here.',
  quiet: 'Quiet mode is on: the Coach talks about portions, not calories or scores.',
  showNumbers: 'show numbers',
  hideNumbers: 'hide numbers',
  photoSent: (provider: string) => `Sent to ${provider} for this message only; the photo stays on this device.`,
  photoAlt: 'Your photo',
  unreachable: (provider: string) => `Couldn’t reach ${provider}. Your note is saved as ‘to review’ and counts as not logged yet, never as zero.`,
  tryAgain: 'Try again',
  settingsLink: 'Open Settings',
  proposalsWaiting: (n: number) => `${n} proposal${n === 1 ? '' : 's'} waiting`,
  briefingKey: 'what it knows',
  announceReply: (text: string) => `The Coach replied: ${text}`,
  announceCards: (n: number) => `${n} card${n === 1 ? '' : 's'} below.`,
  announceStopped: 'Stopped.',
  confirmTitle: (what: string) => `${what.charAt(0).toUpperCase()}${what.slice(1)}?`,
  typeToConfirm: (word: string) => `Type ${word} to confirm.`,
  ended: 'The plan ended. You can restore it for 7 days.',
  cantComplete: 'Only the plan screens can complete that confirmation.',
  adjustDraft: (what: string) => `Change the proposal “${what}”: `,
  unknownConversation: 'This conversation isn’t on this device.',
} as const;

/** "What the Coach knows" (standing briefing, visible). */
export const BRIEFING_COPY = {
  title: 'What the Coach knows',
  always: 'Always',
  alwaysLines: [
    'How Vitals works, its safety rules and how it asks before changing your plan.',
    'It can’t change your safety answers, fasting opt-ins, device sharing, sync or keys.',
  ],
  about: 'About you',
  trendWeight: (kg: string, range: string) => `trend weight ${kg} kg (likely ${range})`,
  trendWeightQuiet: 'trend weight: shared as a direction, not a number, in quiet mode',
  noTrend: 'trend weight: not enough weigh-ins yet',
  supplements: (list: string) => `supplements in today’s plan: ${list}`,
  setupAnswers: 'age band, height, safety mode, food rules and equipment from your setup answers',
  plan: 'Your plan',
  noPlan: 'No plan is running. It can help you choose one.',
  planLine: (name: string, rung: string, day: number, of: number) => `${name} · ${rung} · day ${day} of ${of}`,
  todayLine: (parts: string) => `today: ${parts}`,
  goalDate: (range: string) => `goal date likely ${range}`,
  drift: (state: string) => `against the forecast: ${state}`,
  adherence: (a7: string, a28: string) => `adherence: last 7 days ${a7} · last 28 days ${a28}`,
  adherenceQuiet: (a7: string) => `adherence: ${a7} (quiet mode: words only)`,
  proposals: (n: number) => `${n} proposal${n === 1 ? '' : 's'} waiting for you`,
  week: 'Last 7 days',
  weekLine: (day: string, score: string, n: number) => `${day} · ${score} · ${n} logged`,
  weekEmpty: 'Nothing from the last 7 days yet.',
  notLogged: 'not logged',
  signals: 'Body signals it can see',
  noSignals: 'No device data is shared with the Coach.',
  sleep: (hours: string) => `sleep: daily summaries · last night ${hours}`,
  restingHr: 'resting heart rate: daily value against your baseline',
  hrv: 'HRV: above, normal or below your baseline',
  changeSignals: 'Change what it can see',
  ask: 'Still to ask',
  askNone: 'Nothing waiting.',
  sentTo: 'Sent to',
  sentLine: (provider: string, model: string) =>
    `${provider} (${model}): this conversation and the results of what the Coach looks up. Not your name or email. Photos only in the message you attach them to.`,
  sentNone: 'Nothing is sent: no AI provider is connected.',
  drift3: { ahead: 'ahead', onTrack: 'on track', behind: 'behind' },
  fast: (h: number) => `fast ${h} h`,
  window: (from: string, to: string) => `eating ${from}–${to}`,
  meals: (n: number) => `${n} meal${n === 1 ? '' : 's'}`,
  strength: (at: string) => `strength session ${at}`,
  cardio: (at: string) => `cardio session ${at}`,
} as const;

/** Change cards (shared: Coach, Today, Plan details). */
export const CARD_COPY = {
  lookedAt: 'looked at',
  showLookups: 'Show what it looked at',
  needsConfirmation: 'Needs your confirmation',
  notAllowed: 'Not allowed by your safety settings',
  onlyYou: 'Only you can change that',
  stale: 'Something changed since this was proposed. Updated version:',
  expired: 'Expired — ask again',
  discarded: 'Discarded',
  undone: '(undone)',
  changesTo: 'changes to',
  apply: 'Apply',
  logIt: 'Log it',
  adjust: 'Adjust',
  discard: 'Discard',
  undo: 'Undo',
  redo: 'Redo',
  edit: 'Edit',
  done: 'Done',
  review: 'Review and confirm…',
  useUpdated: 'Use the updated version',
  notNow: 'Not now',
  leaveIt: 'Leave it',
  looksRight: 'Looks right',
  options: 'Options:',
  saw: 'saw',
  couldntSee: 'couldn’t see',
  total: 'total',
  notReached: 'not reached',
  grams: 'grams',
  gramsOf: (name: string) => `${name}, grams`,
  changeGrams: (name: string, amount: string) => `Change ${name}: ${amount}`,
  sure: (who: string, c: number) => `${who} was ${c >= 0.85 ? 'quite' : c >= 0.6 ? 'fairly' : 'not very'} sure: ${c.toFixed(2)}`,
  name: {
    apply: (o: string) => `Apply ${o}`,
    logIt: (o: string) => `Log ${o}`,
    adjust: (o: string) => `Adjust ${o}`,
    discard: (o: string) => `Discard ${o}`,
    undo: (o: string) => `Undo ${o}`,
    redo: (o: string) => `Redo ${o}`,
    edit: (o: string) => `Edit ${o}`,
    review: (o: string) => `Review and confirm: ${o}`,
    useUpdated: (o: string) => `Use the updated ${o}`,
    notNow: (o: string) => `Not now: ${o}`,
    leaveIt: (o: string) => `Leave it: ${o}`,
    looksRight: (o: string) => `Looks right: ${o}`,
  },
  announce: {
    applied: (t: string) => `${t}: applied.`,
    undone: (t: string) => `${t}: undone. Redo available.`,
    discarded: (t: string) => `${t}: discarded.`,
    expired: (t: string) => `${t}: expired.`,
    stale: (t: string) => `${t}: something changed. An updated version is shown.`,
  },
} as const;

/** The composer (Coach full, Today's log bar). */
export const COMPOSER_COPY = {
  placeholder: 'Tell the Coach what you did…',
  label: 'Message to the Coach',
  prompts: 'Suggestions',
  send: 'Send',
  stop: 'Stop',
  stopName: 'Stop the Coach',
  photo: 'Add a photo or PDF',
  pdf: 'Add a PDF report',
  removePhoto: 'Remove the photo',
  removePdf: 'Remove the PDF',
  photoAttached: 'photo attached',
  pdfAttached: (name: string) => `PDF attached · ${name}`,
  noVision: 'This model can’t see photos. Describe the meal in words, or choose a model with vision in Settings.',
  openSettings: 'Open Settings',
} as const;
