/**
 * Parameters of the fasting module (docs/MODEL_SPEC.md §1.4; dossier 20 §4B.2, the single source for ModelParams).
 * Every number is copied from dossier 20 (§4.1-§4.5, §4.9, §4B.2) or the spec. Where the dossier gives a formula with a
 * ± band (φ_AT, pr_late) the structural constants are `fixed` and the band is carried by one drawn shift/multiplier.
 */
import type { ParamDef } from '../../types/params';

// ---- sources (20 §11 reference list)
const HALL2010 = 'Hall 2010 PMID 19934407';
const ZAUNER = 'Zauner 2000 PMID 10837292';
const WEBBER = 'Webber & Macdonald 1994 PMID 8172872';
const MANSELL = 'Mansell 1990 PMID 2405717';
const NAIR = 'Nair 1987 PMID 3661473';
const BROWNING = 'Browning 2012 PMID 22140269';
const DAI22 = 'Dai 2022 PMID 36145236';
const DAI24 = 'Dai 2024 PMID 39557965';
const KOLNES = 'Kolnes 2025 PMID 39747857';
const PIETZNER = 'Pietzner 2024 PMID 38429390';
const LAURENS = 'Laurens 2021 PMID 34668663';
const BENEDICT = 'Benedict 1915 (Carnegie Inst. Publ. 203)';
const GOSCHKE = 'Göschke 1975 PMID 1177405';
const OWEN98 = 'Owen 1998 PMID 9665093';
const HENRY = 'Henry 1988 PMID 3066619';
const FORBES = 'Forbes & Drenick 1979 PMID 463798';
const SPEAKMAN = 'Speakman & Westerterp 2013 PMID 22864023';
const MATHIESON = 'Mathieson 1986 PMID 3702673';
const VAZQUEZ = 'Vazquez 1995 PMID 7598072';
const SAPIR72 = 'Sapir 1972 PMID 5054466';
const SHERWIN81 = 'Sherwin 1981 PMID 6947662';
const SHERWIN78 = 'Sherwin 1978 PMID 659610';
const TEMPLEMAN = 'Templeman 2021 PMID 34135111';
const GABRIEL = 'Gabriel 2025 PMID 40765844';
const COMMISSATI = 'Commissati 2025 PMID 40268190';
const MCDOUGAL = 'McDougal 2018 PMID 29931424';

export const FASTING_PARAMS: readonly ParamDef[] = [
  // ------------------------------------------------------------------ overlay criteria (20 §4.1, §2; MODEL_SPEC §1.4 step 1)
  {
    id: 'fasting.fastKcalFrac',
    value: 0.1,
    unit: '1 (of maintenance)',
    low: 0.1,
    high: 0.1,
    grade: 'C',
    status: 'proposed-fit',
    source: KOLNES,
    dossier: '20 §4.1, §4B.1',
    label: 'Water-only criterion: 24-h energy < fraction of maintenance',
  },
  {
    id: 'fasting.fastProteinMaxG',
    value: 5,
    unit: 'g/24 h',
    low: 5,
    high: 5,
    grade: 'C',
    status: 'proposed-fit',
    source: KOLNES,
    dossier: '20 §4.1, §4B.1',
    label: 'Fast criterion: 24-h protein below',
  },
  {
    id: 'fasting.fastCarbMaxG',
    value: 10,
    unit: 'g/24 h',
    low: 10,
    high: 10,
    grade: 'C',
    status: 'proposed-fit',
    source: KOLNES,
    dossier: '20 §4.1, §4B.1',
    label: 'Water-only criterion: 24-h digestible carbohydrate below',
  },
  {
    id: 'fasting.modKcalFrac',
    value: 0.15,
    unit: '1 (of maintenance)',
    low: 0.15,
    high: 0.15,
    grade: 'C',
    status: 'proposed-fit',
    source: LAURENS,
    dossier: '20 §4.1, §4B.1',
    label: 'Modified (Buchinger-type) fast: 24-h energy < fraction of maintenance',
  },
  {
    id: 'fasting.eventProteinG',
    value: 5,
    unit: 'g/h',
    low: 5,
    high: 5,
    grade: 'C',
    status: 'proposed-fit',
    source: KOLNES,
    dossier: '20 §2 (tFast)',
    label: 'Intake event resetting the fasting clock: protein above',
    note: 'energy part of the event rule is 17 §2.5 ZERO_INTAKE_KCAL (core/defaults)',
  },
  {
    id: 'fasting.plannedMinSpanH',
    value: 24,
    unit: 'h',
    low: 24,
    high: 24,
    grade: 'C',
    status: 'proposed-fit',
    source: 'MODEL_SPEC_DECISIONS 2026-09-30 (review M7)',
    dossier: '20 §4.1, §4B.1',
    draw: 'fixed',
    label:
      'A planned zero-intake span activates the overlay from its first hour only when at least this long',
    note: "Shorter planned spans use the 24-h intake criteria (a 16-h FastEvent must not get 20's peak N rate).",
  },
  {
    id: 'fasting.eventCarbG',
    value: 5,
    unit: 'g/h',
    low: 5,
    high: 5,
    grade: 'C',
    status: 'proposed-fit',
    source: KOLNES,
    dossier: '20 §2 (tFast)',
    label: 'Intake event resetting the fasting clock: digestible carbohydrate above',
  },

  // ------------------------------------------------------------------ resting EE (20 §4.2; MODEL_SPEC §1.4 step 2)
  {
    id: 'fasting.aSNS',
    value: 0.05,
    unit: '1',
    low: -0.08,
    high: 0.14,
    grade: 'C',
    status: 'proposed-fit',
    source: `${ZAUNER}; ${WEBBER}; ${MANSELL}; ${NAIR}; ${BROWNING}; ${DAI22}; ${KOLNES}; ${DAI24}`,
    dossier: '20 §4.2, §4B.2',
    label: 'Early sympathetic RMR rise, peak fraction a_SNS',
  },
  {
    id: 'fasting.tP',
    value: 2.0,
    unit: 'd',
    low: 1.5,
    high: 3.0,
    grade: 'C',
    status: 'proposed-fit',
    source: `${ZAUNER}; ${WEBBER}; ${BROWNING}`,
    dossier: '20 §4.2, §4B.2',
    label: 'Time of the early RMR peak t_p',
  },
  {
    id: 'fasting.tLag',
    value: 2,
    unit: 'd',
    low: 1,
    high: 4,
    grade: 'C',
    status: 'proposed-fit',
    source: `${KOLNES}; ${DAI24}`,
    dossier: '20 §4.2, §4B.2',
    label: 'Lag before the fasting resting adaptation starts t_lag',
  },
  {
    id: 'fasting.tauAT',
    value: 9,
    unit: 'd',
    low: 6,
    high: 14,
    grade: 'C',
    status: 'proposed-fit',
    source: `${DAI24}; ${LAURENS}; ${BENEDICT}`,
    dossier: '20 §4.2, §4B.2',
    label: 'Fasting resting-adaptation time constant τ_AT (on)',
  },
  {
    id: 'fasting.tauATOff',
    value: 4,
    unit: 'd',
    low: 3,
    high: 7,
    grade: 'C',
    status: 'proposed-fit',
    source: `${DAI24}; ${MATHIESON}`,
    dossier: '20 §4.2, §4B.2',
    label: 'Resting-adaptation recovery time constant τ_AT,off',
  },
  {
    id: 'fasting.phiATIntercept',
    value: 0.25,
    unit: '1',
    low: 0.25,
    high: 0.25,
    grade: 'C',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${DAI24}; ${OWEN98}; ${SPEAKMAN}`,
    dossier: '20 §4.2, §4B.2',
    label: 'φ_AT = clamp(0.25 − 0.004·BF%, 0.05, 0.22): intercept',
  },
  {
    id: 'fasting.phiATSlope',
    value: 0.004,
    unit: '1 per %BF',
    low: 0.004,
    high: 0.004,
    grade: 'C',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${DAI24}; ${OWEN98}; ${SPEAKMAN}`,
    dossier: '20 §4.2, §4B.2',
    label: 'φ_AT slope per % body fat',
  },
  {
    id: 'fasting.phiATMin',
    value: 0.05,
    unit: '1',
    low: 0.05,
    high: 0.05,
    grade: 'C',
    status: 'proposed-fit',
    source: `${OWEN98}; ${SPEAKMAN}`,
    dossier: '20 §4.2, §4B.2',
    label: 'φ_AT lower clamp',
  },
  {
    id: 'fasting.phiATMax',
    value: 0.22,
    unit: '1',
    low: 0.22,
    high: 0.22,
    grade: 'C',
    status: 'proposed-fit',
    source: BENEDICT,
    dossier: '20 §4.2, §4B.2',
    label: 'φ_AT upper clamp',
  },
  {
    id: 'fasting.phiATShift',
    value: 0,
    unit: '1',
    low: -0.07,
    high: 0.07,
    grade: 'C',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${DAI24}; ${OWEN98}`,
    dossier: '20 §4.2, §4B.2',
    label: 'φ_AT uncertainty (±0.07, added after the clamp)',
  },
  {
    id: 'fasting.gammaP',
    value: 19,
    unit: 'kcal/kg hydrated protein tissue/d',
    low: 19,
    high: 19,
    grade: 'B',
    status: 'verified',
    source: HALL2010,
    dossier: '20 §4.2, §4B.2',
    draw: 'fixed',
    label: "20's RMR mass coefficient γ_P (documentation only; not used by the engine)",
    note: "Ruling R-RMRMASS: RMR mass terms are energy's (02 γ_L 22 / γ_F 3.2). Dossier range 13-30 kept here, not as low/high (MODEL_SPEC_DECISIONS M20: rejected alternatives are not ensemble draws).",
  },
  {
    id: 'fasting.gammaF',
    value: 4.5,
    unit: 'kcal/kg fat/d',
    low: 4.5,
    high: 4.5,
    grade: 'B',
    status: 'verified',
    source: HALL2010,
    dossier: '20 §4.2, §4B.2',
    draw: 'fixed',
    label: "20's RMR fat coefficient γ_F (documentation only; not used by the engine)",
    note: 'Ruling R-RMRMASS: alternative to energy.gammaF 3.2; dossier range 3-6 recorded here only (M20).',
  },

  // ------------------------------------------------------------------ muscle glycogen (20 §4.3.1; read by fuel)
  {
    id: 'fasting.kMf',
    value: 0.008,
    unit: '1/h',
    low: 0.005,
    high: 0.012,
    grade: 'B',
    status: 'proposed-fit',
    source: KOLNES,
    dossier: '20 §4.3.1, §4B.2',
    label: 'Fasting resting muscle glycogenolysis k_Mf (fuel: −k_Mf·(G_M − 0.35·G_M0))',
    note: 'dossier grade B/C; replaces 04 k_Mr while fastActive',
  },

  // ------------------------------------------------------------------ protein / N economy (20 §4.4.2, §4.4.4)
  {
    id: 'fasting.nPkLean',
    value: 0.25,
    unit: 'g N/kg FFM/d',
    low: 0.21,
    high: 0.28,
    grade: 'B',
    status: 'proposed-fit',
    source: `${GOSCHKE}; ${BENEDICT}; ${KOLNES}`,
    dossier: '20 §4.4.2, §4B.2',
    label: 'Early-peak urinary N per kg FFM (lean, FM ≤ 10 kg)',
  },
  {
    id: 'fasting.nPkObDrop',
    value: 0.06,
    unit: 'g N/kg FFM/d',
    low: 0.06,
    high: 0.06,
    grade: 'B',
    status: 'proposed-fit',
    source: `${GOSCHKE}; ${FORBES}`,
    dossier: '20 §4.4.2',
    label: 'Drop of n_pk from lean to FM ≥ 50 kg (0.25 → 0.19)',
  },
  {
    id: 'fasting.nPkFmRefKg',
    value: 10,
    unit: 'kg',
    low: 10,
    high: 10,
    grade: 'B',
    status: 'proposed-fit',
    source: GOSCHKE,
    dossier: '20 §4.4.2',
    label: 'n_pk adiposity ramp start (FM)',
  },
  {
    id: 'fasting.nPkFmSpanKg',
    value: 40,
    unit: 'kg',
    low: 40,
    high: 40,
    grade: 'B',
    status: 'proposed-fit',
    source: GOSCHKE,
    dossier: '20 §4.4.2',
    label: 'n_pk adiposity ramp width (FM)',
  },
  {
    id: 'fasting.prLateBase',
    value: 0.04,
    unit: '1 (of TEE)',
    low: 0.04,
    high: 0.04,
    grade: 'B',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${HENRY}; ${GOSCHKE}; ${OWEN98}`,
    dossier: '20 §4.4.2',
    label: 'pr_late = 0.04 + 0.22·e^(−BF%/15): floor',
  },
  {
    id: 'fasting.prLateAmp',
    value: 0.22,
    unit: '1 (of TEE)',
    low: 0.22,
    high: 0.22,
    grade: 'B',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${HENRY}; ${GOSCHKE}; ${OWEN98}`,
    dossier: '20 §4.4.2',
    label: 'pr_late amplitude',
  },
  {
    id: 'fasting.prLateBfScale',
    value: 15,
    unit: '%BF',
    low: 15,
    high: 15,
    grade: 'B',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${HENRY}; ${GOSCHKE}; ${OWEN98}`,
    dossier: '20 §4.4.2',
    label: 'pr_late body-fat scale',
  },
  {
    id: 'fasting.prLateMult',
    value: 1,
    unit: '1',
    low: 0.75,
    high: 1.25,
    grade: 'B',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${HENRY}; ${GOSCHKE}; ${OWEN98}`,
    dossier: '20 §4B.2',
    label: 'pr_late uncertainty multiplier (×0.75 … ×1.25)',
    note: 'dossier grade B/C',
  },
  {
    id: 'fasting.sparingBhbOnset',
    value: 0.5,
    unit: 'mmol/L',
    low: 0.5,
    high: 0.5,
    grade: 'C',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${KOLNES}; ${GOSCHKE}`,
    dossier: '20 §4.4.2',
    label: 'S* = clamp((BHB − 0.5)/3.5, 0, 1): onset',
  },
  {
    id: 'fasting.sparingBhbSpan',
    value: 3.5,
    unit: 'mmol/L',
    low: 3.5,
    high: 3.5,
    grade: 'C',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${KOLNES}; ${GOSCHKE}`,
    dossier: '20 §4.4.2',
    label: 'S* span',
  },
  {
    id: 'fasting.tauN',
    value: 8,
    unit: 'd',
    low: 6,
    high: 14,
    grade: 'C',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${KOLNES}; ${GOSCHKE}`,
    dossier: '20 §4.4.2, §4B.2',
    label: 'Protein-sparing adaptation time constant τ_N (on)',
  },
  {
    id: 'fasting.tauNOff',
    value: 3,
    unit: 'd',
    low: 2,
    high: 5,
    grade: 'D',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${KOLNES}; ${GOSCHKE}`,
    dossier: '20 §4.4.2, §4.9, §4B.2',
    label: 'S_N decay after refeeding (carbohydrate ≥ 50 g/d)',
  },
  {
    id: 'fasting.tauNOffLowCarb',
    value: 7,
    unit: 'd',
    low: 4,
    high: 14,
    grade: 'D',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${KOLNES}; ${GOSCHKE}`,
    dossier: '20 §4.9, §4B.2',
    label: 'S_N decay after a low-carbohydrate refeed (< 50 g/d)',
  },
  {
    id: 'fasting.lowCarbOffG',
    value: 50,
    unit: 'g/24 h',
    low: 50,
    high: 50,
    grade: 'D',
    status: 'proposed-fit',
    source: `${BENEDICT}; ${KOLNES}`,
    dossier: '20 §4.9, §4B.1',
    label: 'Carbohydrate threshold selecting τ_N,off',
  },
  {
    id: 'fasting.riseStart',
    value: 0.8,
    unit: '1',
    low: 0.8,
    high: 0.8,
    grade: 'C',
    status: 'proposed-fit',
    source: `${GOSCHKE}; ${BENEDICT}`,
    dossier: '20 §4.4.2',
    label: 'N rise factor at fast start (0.8 + 0.2·min(1, t/2.5))',
  },
  {
    id: 'fasting.riseDays',
    value: 2.5,
    unit: 'd',
    low: 2.5,
    high: 2.5,
    grade: 'C',
    status: 'proposed-fit',
    source: `${GOSCHKE}; ${BENEDICT}`,
    dossier: '20 §4.4.2',
    label: 'N rise duration',
  },
  {
    id: 'fasting.hP',
    value: 1.6,
    unit: 'g water/g protein',
    low: 1.1,
    high: 3.0,
    grade: 'B',
    status: 'verified',
    source: HALL2010,
    dossier: '20 §4.4.2, §4.6.2, §4B.2',
    label: 'Water bound per g protein in lean tissue h_P',
    note: 'ruling R-FPROT (f_prot = 1/(1 + h_P)); composition converts fastProtOxGH to lean tissue',
  },
  {
    id: 'fasting.cCarb',
    value: 0.45,
    unit: '1 per 100 g/d',
    low: 0.3,
    high: 0.6,
    grade: 'C',
    status: 'proposed-fit',
    source: `${HALL2010}; ${VAZQUEZ}; ${SAPIR72}`,
    dossier: '20 §4.4.4, §4B.2',
    label: 'Carbohydrate N sparing C_carb = 1 − 0.45·clamp(CHO/100, 0, 1)',
  },
  {
    id: 'fasting.carbRefG',
    value: 100,
    unit: 'g/24 h',
    low: 100,
    high: 100,
    grade: 'C',
    status: 'proposed-fit',
    source: `${HALL2010}; ${VAZQUEZ}`,
    dossier: '20 §4.4.4',
    label: 'C_carb saturation carbohydrate',
  },
  {
    id: 'fasting.kKet',
    value: 0.3,
    unit: '1 per 1.5 mM exogenous BHB',
    low: 0.2,
    high: 0.4,
    grade: 'C',
    status: 'proposed-fit',
    source: `${SHERWIN81}; ${SHERWIN78}`,
    dossier: '20 §4.4.4, §4B.2',
    label: 'Exogenous-ketone N sparing K_ket = 1 − 0.3·clamp(BHB_exo/1.5, 0, 1)',
  },
  {
    id: 'fasting.ketExoRefMmolL',
    value: 1.5,
    unit: 'mmol/L',
    low: 1.5,
    high: 1.5,
    grade: 'C',
    status: 'proposed-fit',
    source: SHERWIN81,
    dossier: '20 §4.4.4',
    label: 'K_ket saturation (exogenous BHB)',
  },
  {
    id: 'fasting.kEx',
    value: 1.0,
    unit: '1',
    low: 0.9,
    high: 1.0,
    grade: 'D',
    status: 'proposed-fit',
    source: `${HALL2010}; ${LAURENS}`,
    dossier: '20 §4.4.4, §4B.2',
    label: 'Activity N modifier K_ex',
  },

  // ------------------------------------------------------------------ labile pool and refeeding (20 §4.9, §4B.1)
  {
    id: 'fasting.lMax',
    value: 0.75,
    unit: 'g protein/kg FFM0',
    low: 0.3,
    high: 1.5,
    grade: 'D',
    status: 'proposed-fit',
    source: `${FORBES}; ${TEMPLEMAN}; ${PIETZNER}`,
    dossier: '20 §4.9, §4B.2',
    label: 'Labile protein pool capacity L_max',
  },
  {
    id: 'fasting.tauRep',
    value: 2,
    unit: 'd',
    low: 1,
    high: 4,
    grade: 'D',
    status: 'proposed-fit',
    source: `${FORBES}; ${TEMPLEMAN}; ${PIETZNER}`,
    dossier: '20 §4.9, §4B.2',
    label: 'Labile pool repletion time constant τ_rep',
  },
  {
    id: 'fasting.repEnergyFrac',
    value: 0.9,
    unit: '1 (of maintenance)',
    low: 0.9,
    high: 0.9,
    grade: 'D',
    status: 'proposed-fit',
    source: PIETZNER,
    dossier: '20 §4.9, §4B.1',
    label: 'Repletion requires 24-h energy ≥ fraction of maintenance',
  },
  {
    id: 'fasting.repProteinGPerKg',
    value: 1.0,
    unit: 'g/kg BW/24 h',
    low: 1.0,
    high: 1.0,
    grade: 'D',
    status: 'proposed-fit',
    source: PIETZNER,
    dossier: '20 §4.9, §4B.1',
    label: 'Repletion requires 24-h protein ≥ g/kg body weight',
  },

  // ------------------------------------------------------------------ refeeding oedema (20 §4.5.2)
  {
    id: 'fasting.aOed',
    value: 0.08,
    unit: 'L per fast day > 3 d',
    low: 0.03,
    high: 0.15,
    grade: 'D',
    status: 'proposed-fit',
    source: `${DAI24}; ${GABRIEL}`,
    dossier: '20 §4.5.2, §4B.2',
    label: 'Refeeding oedema amplitude per fast day beyond 3 d',
  },
  {
    id: 'fasting.aOedCapL',
    value: 2.0,
    unit: 'L',
    low: 2.0,
    high: 2.0,
    grade: 'D',
    status: 'proposed-fit',
    source: `${DAI24}; ${GABRIEL}`,
    dossier: '20 §4.5.2, §4B.2',
    label: 'Refeeding oedema cap',
  },
  {
    id: 'fasting.oedMinFastD',
    value: 3,
    unit: 'd',
    low: 3,
    high: 3,
    grade: 'D',
    status: 'proposed-fit',
    source: `${DAI24}; ${GABRIEL}`,
    dossier: '20 §4.5.2',
    label: 'Oedema only after fasts longer than',
  },
  {
    id: 'fasting.oedRiseTauD',
    value: 2,
    unit: 'd',
    low: 2,
    high: 2,
    grade: 'D',
    status: 'proposed-fit',
    source: DAI24,
    dossier: '20 §4.5.2',
    label: 'E_oed = A·(1 − e^(−t/2 d))·e^(−t/10 d): rise τ',
  },
  {
    id: 'fasting.oedDecayTauD',
    value: 10,
    unit: 'd',
    low: 10,
    high: 10,
    grade: 'D',
    status: 'proposed-fit',
    source: DAI24,
    dossier: '20 §4.5.2',
    label: 'Oedema decay τ',
  },
  {
    id: 'fasting.oedLowMult',
    value: 0.3,
    unit: '1',
    low: 0.3,
    high: 0.3,
    grade: 'D',
    status: 'proposed-fit',
    source: `${GABRIEL}; ${COMMISSATI}`,
    dossier: '20 §4.5.2',
    label: 'Oedema × 0.3 for salt-free or < 50 g carbohydrate refeeds',
  },
  {
    id: 'fasting.oedLowCarbG',
    value: 50,
    unit: 'g/24 h',
    low: 50,
    high: 50,
    grade: 'D',
    status: 'proposed-fit',
    source: `${GABRIEL}; ${COMMISSATI}`,
    dossier: '20 §4.5.2',
    label: 'Low-carbohydrate refeed threshold for the oedema factor',
  },
  {
    id: 'fasting.oedLowNaMg',
    value: 1500,
    unit: 'mg/d',
    low: 1500,
    high: 1500,
    grade: 'D',
    status: 'proposed-fit',
    source: `${GABRIEL}; ${COMMISSATI}`,
    dossier: '20 §4.5.2',
    label: 'Salt-free refeed: sodium below (the refeed condition is sodium of 1.5 g/d or more)',
  },

  // ------------------------------------------------------------------ BHB reference curve (calibration target for ketones, 20 §4.3.4)
  {
    id: 'fasting.bhbRefB1',
    value: 2.2,
    unit: 'mmol/L',
    low: 1.54,
    high: 2.86,
    grade: 'B',
    status: 'proposed-fit',
    source: `${BROWNING}; ${MCDOUGAL}; ${KOLNES}; ${DAI24}`,
    dossier: '20 §4.3.4, §4B.2',
    draw: 'fixed',
    label: 'BHB_ref early logistic amplitude B1 (calibration only)',
    note: 'target for the ketones retune (R-KET); not engine physics',
  },
  {
    id: 'fasting.bhbRefB2',
    value: 3.7,
    unit: 'mmol/L',
    low: 2.59,
    high: 4.81,
    grade: 'B',
    status: 'proposed-fit',
    source: `${KOLNES}; ${DAI24}`,
    dossier: '20 §4.3.4, §4B.2',
    draw: 'fixed',
    label: 'BHB_ref slow amplitude B2 (calibration only)',
  },
  {
    id: 'fasting.bhbRefTau2H',
    value: 170,
    unit: 'h',
    low: 119,
    high: 221,
    grade: 'B',
    status: 'proposed-fit',
    source: `${KOLNES}; ${DAI24}`,
    dossier: '20 §4.3.4, §4B.2',
    draw: 'fixed',
    label: 'BHB_ref slow time constant τ2 (calibration only)',
  },
];
