/**
 * Intake v2 copy (design/screens/onboarding-intake-v2.md §6; voice: DESIGN_DIRECTION §10). Plain, specific, second
 * person; questions use concrete nouns, times and counts. Never research-file names, section signs or rule ids.
 * Engraved labels are authored lowercase.
 */

export const CHAPTER_NAME = {
  activity: 'A normal day',
  training: 'Training and equipment',
  food: 'Food and kitchen',
  markers: 'Blood markers',
  devices: 'Devices and data',
} as const;

/** Lowercase short names for the progress scale and summaries. */
export const CHAPTER_SHORT = {
  activity: 'a normal day',
  training: 'training',
  food: 'food',
  markers: 'blood markers',
  devices: 'devices',
} as const;

export const CHAPTER_INTRO = {
  activity: 'A few questions about a normal week. They set how much energy you use outside training — the number every plan is built on.',
  training: "What you'd be willing to do, and with what. Plans use what you already have first, and say plainly if something would help.",
  food: "What you eat, any rules you keep, and how you cook. Recipes only ever use what you've said yes to.",
  markers: 'Optional. If you have recent blood test results, some of them change what a plan may do.',
  devices:
    'If you wear a ring or watch, or use a smart scale, Vitals can use its data. You choose, stream by stream, what comes in and who sees it. Nothing leaves your devices unless you set up sync or talk to the Coach.',
} as const;

export const TURN = {
  loading: 'Loading…',
  why: 'why we ask',
  ifSkip: (text: string) => `if you skip: ${text}`,
  later: 'Ask me later',
  laterKey: 'L',
  back: 'Back',
  next: 'Next',
  nextNeedsAnswer: 'Choose an answer first',
  because: 'because you said:',
  questionOf: (n: number, total: number) => `question ${n} of ${total}`,
  /** The action bar once a chapter is complete (it read "question 3 of 2"). */
  answeredOf: (done: number, total: number) => `${done} of ${total} answered`,
  more: (n: number) => `${n} more question${n === 1 ? '' : 's'} in this chapter`,
  answersTitle: 'Your answers',
  answersCount: (done: number, total: number) => `${done} of ${total}`,
  continuing: (n: number, total: number) => `Continuing at question ${n} of ${total}.`,
  movedTo: (n: number, total: number, answer: string | null) => `Question ${n} of ${total}${answer ? `, answered: ${answer}` : ''}.`,
  notUsedBecause: (why: string) => `not used: you said ${why}`,
  saveFailed: "Couldn't save this answer. Try again.",
  tryAgain: 'Try again',
  changing: 'changing an answer',
  save: 'Save',
  answerNow: 'Answer',
  change: 'Change',
  changeLabel: (q: string, a: string) => `Change: ${q}, ${a}`,
  cancel: 'Cancel',
  done: 'Done',
  doneCount: (n: number) => `Done (${n})`,
  defaultTag: 'default',
  usingLater: (text: string) => `using ${text} · asked later`,
  notUsed: 'not used',
  saved: (q: string, a: string) => `Saved: ${q}, ${a}.`,
  skippedSaved: (q: string) => `Asked later: ${q}`,
  otherPlaceholder: 'type it',
  add: 'Add',
  remove: (what: string) => `Remove ${what}`,
  exact: 'exact number',
} as const;

export const BAR = {
  skipPart: 'Skip this part',
  count: (pos: number, total: number) => `${Math.min(pos, total)} of ${total}`,
  progressLabel: 'Setup progress',
  progressText: (chapter: string, pos: number, total: number) => `${chapter}, ${Math.min(pos, total)} of ${total}`,
  skippedToast: (chapter: string) => `Skipped "${chapter}". Plans use the defaults.`,
  progressFull: (chapter: string, pos: number, total: number, chaptersDone: number, chapters: number) =>
    `${chapter}, question ${Math.min(pos, total)} of ${total}; ${chaptersDone} of ${chapters} chapters done`,
  receiptTitle: (chapter: string) => `${chapter} · done`,
  receiptCounts: (answered: number, later: number) => `${answered} answered${later ? ` · ${later} asked later` : ''}`,
  receiptLead: 'Plans use these answers from now on. You can change any of them here or in Body › Your setup.',
  nextChapter: (name: string) => `Next: ${name}`,
  reviewLater: (n: number) => `Review asked-later (${n})`,
  undo: 'Undo',
  next: 'Next part',
  toSummary: "See what we'll use",
  back: 'Back',
  backToBody: 'Your body',
  chatInstead: 'Answer by chatting instead',
  chatDraft: (chapter: string) => `Ask me the questions about ${chapter.toLowerCase()} here, one at a time.`,
  storage: "This browser isn't saving data. Your answers won't be kept after this tab closes.",
} as const;

/* --------------------------------------------------------------------------------------------- chapter 1 */

export const A = {
  work: {
    prompt: 'Do you work or study outside the home most weeks?',
    short: 'work or study outside home',
    skip: 'not known',
    options: { yes: 'yes', no: 'no — retired, at home, caring for family', varies: 'it varies' },
  },
  job: {
    prompt: 'What do you mostly do on a workday, at work or study?',
    short: 'on a work day',
    skip: 'a mix (most common)',
    why: 'Your job sets about a third of the energy you use outside training. People describe their work best by example, so pick the card that sounds most like yours.',
    options: {
      desk: { label: 'sitting at a desk or driving', examples: 'office, driving, call centre, seated shop counter', short: 'desk or driving' },
      mixed: { label: 'a mix of sitting and moving', examples: 'lab, teaching, field sales, managing a floor', short: 'a mix of sitting and moving' },
      onFeet: { label: 'on my feet most of the time', examples: 'retail, hospitality, nursing, salon, security', short: 'on my feet' },
      manualModerate: { label: 'physical work: lifting, carrying', examples: 'trades, warehouse, cleaning, delivery', short: 'lifting and carrying' },
      manualHeavy: { label: 'heavy physical work', examples: 'construction, farm work, loading, removals', short: 'heavy physical work' },
    },
  },
  workTime: {
    prompt: 'How many days a week do you go to work or study, and how many hours is a usual day there?',
    promptVaries: 'On average, how many days a week, and about how long?',
    short: 'work days',
    skip: '5 days × 8 h',
    days: 'days',
    hours: 'hours',
    daysName: 'work days a week',
    receipt: (d: number, h: number) => `${d} days × ${h} h`,
  },
  commute: {
    prompt: 'How do you usually get to work or study on a workday?',
    short: 'getting there',
    skip: 'ride, 0 min',
    options: {
      ride: 'ride (car, two-wheeler, auto, bus, train, metro)',
      walk: 'walk part of it',
      cycle: 'cycle',
      home: 'I work from home',
    },
    receipt: { ride: 'ride', walk: 'walk part of it', cycle: 'cycle', home: 'from home' },
  },
  commuteMin: {
    prompt: 'On a workday, how many minutes do you walk or cycle to work and back, in total?',
    short: 'minutes on foot or bike',
    skip: 'about 20 min',
    name: 'minutes a day, both ways',
    unit: 'min',
    deviceNote: 'Your watch or ring already counts these steps, so walking minutes are not added again.',
    receipt: (n: number) => `${n} min a day`,
  },
  stepsKnown: {
    prompt: 'Do you know how many steps you walk a day?',
    short: 'daily steps',
    skip: "no — we'll work them out from your answers",
    why: 'Steps from a watch or ring are within about 10 % of the truth; phone counts and guesses are much looser, so we widen the range.',
    options: { wrist: 'yes, from a watch or ring', phone: 'yes, from my phone', roughly: 'roughly', no: 'no' },
    receipt: { wrist: 'from a watch or ring', phone: 'from my phone', roughly: 'roughly', no: 'not known' },
  },
  stepsNumber: {
    prompt: 'How many steps a day does your watch, ring or phone show, on average over the last 2–4 weeks?',
    short: 'steps a day',
    skip: 'worked out from your answers',
    name: 'steps a day',
    split: 'work days and days off differ',
    workday: 'on a work day',
    offDay: 'on a day off',
    importLater: "I'll import it",
    importNote: 'The devices part can import it and update this number.',
    receiptMean: (n: string) => `about ${n} a day`,
    receiptSplit: (w: string, o: string) => `${w} on work days · ${o} on days off`,
    receiptImport: 'will import',
  },
  phoneCarried: {
    prompt: 'Your phone counts your steps: is it in your pocket or hand most of the day?',
    short: 'phone with you',
    skip: 'mostly',
    options: { mostly: 'mostly', notReally: 'not really' },
  },
  stepsRough: {
    prompt: 'Roughly how many steps do you walk on a usual day?',
    short: 'steps, roughly',
    skip: 'about 7 000',
    name: 'steps a day, roughly',
    receipt: (n: string) => `about ${n} a day`,
  },
  offDay: {
    prompt: 'On a day off from work or study, how do you spend most of the day?',
    short: 'on a day off',
    skip: 'a bit of both',
    options: { mostlyHome: 'at home, taking it easy', mixed: 'a bit of both', outAndAbout: 'out and about, on my feet' },
  },
  home: {
    prompt: 'At home, how much are you on your feet — cooking, cleaning, washing, children, caring?',
    short: 'on your feet at home',
    skip: 'some',
    options: { little: 'a little (under 1 h)', some: 'some (1–2 h)', aLot: 'a lot (3 h or more)' },
  },
  sport: {
    prompt: "Any sport or active hobby that isn't your planned training?",
    examples: 'cricket, badminton, football, dancing, hiking, gardening',
    short: 'sport and hobbies',
    skip: 'none',
    why: 'Sport you already play is part of your normal week. Planned training is counted separately, so nothing is counted twice.',
    none: 'none',
    addRow: 'Add one',
    name: 'what',
    rowName: (i: number) => `sport or hobby ${i}`,
    namePlaceholder: 'e.g. badminton',
    minutes: 'minutes a week',
    intensity: { light: 'light', moderate: 'moderate', vigorous: 'hard' },
    looksLikeTraining: 'That sounds like training — count it there instead?',
    moveToTraining: 'Move to training',
    keepHere: 'Keep it here',
    moved: (what: string) => `"${what}" is counted as training. Tell us how often below.`,
    receiptNone: 'none',
    receiptRow: (label: string, min: number, intensity: string) => `${label} ${min} min/wk (${intensity})`,
  },
  trainNow: {
    prompt: 'Do you exercise on purpose now (gym, sport practice, runs, classes)? How many times a week?',
    short: 'training now',
    skip: 'not now',
    options: { none: 'not now', '1-2': '1–2 times a week', '3-4': '3–4', '5+': '5 or more' },
    receipt: { none: 'not now', '1-2': '1–2 times a week', '3-4': '3–4 times a week', '5+': '5 or more a week' },
  },
  trainMix: {
    prompt: 'When you exercise now, is it mostly lifting weights, mostly cardio, or a mix?',
    short: 'mostly',
    skip: 'mixed',
    options: { lifting: 'lifting', mixed: 'mixed', cardio: 'mostly cardio' },
  },
  sleep: {
    prompt: 'On a usual night, what time do you go to sleep and wake up?',
    short: 'sleep',
    skip: '23:00–07:00',
    why: "Plans place meals and training around your sleep. It doesn't change your maintenance.",
    other: 'other',
    rangeLabel: 'bed and wake time',
    thumbs: ['bed', 'wake'] as [string, string],
  },
  sleepQuality: {
    prompt: 'On a usual night, how well do you sleep?',
    short: 'sleep quality',
    skip: 'fair',
    options: { poor: 'poor', fair: 'fair', good: 'good' },
  },
  measuredEver: {
    prompt: 'Have you ever had your resting energy or your maintenance calories measured, for example in a clinic, a lab or with a scan?',
    short: 'measured before',
    skip: 'no',
    why: 'A resting value measured with a breath test replaces the estimate from your size and age, which narrows your range. Other kinds of figures are shown next to the estimate.',
    options: { no: 'no', rmr: 'yes, my resting energy (lying still)', tdee: 'yes, my maintenance (a whole day)' },
    receipt: { no: 'no', rmr: 'yes, resting energy', tdee: 'yes, maintenance' },
  },
  measured: {
    prompt: 'What was your measured figure, and how was it measured?',
    short: 'measured figure',
    skip: 'not used',
    figure: 'figure',
    figureName: 'measured figure',
    unitLabel: 'unit',
    units: { kcal: 'kcal a day', kJ: 'kJ a day' },
    how: 'how it was measured',
    methods: {
      metabolic_cart: 'breath test with a mask or hood',
      dxa_based: 'calculated from a DXA scan',
      smart_scale: 'a smart-scale reading',
      calculator: 'an online or app calculator',
      tracking: 'weeks of logging what I ate while my weight stayed the same',
    },
    methodsShort: { metabolic_cart: 'breath test', dxa_based: 'DXA scan', smart_scale: 'smart scale', calculator: 'calculator', tracking: 'logged intake' },
    when: 'when (month and year)',
    month: 'month',
    year: 'year',
    save: 'Save',
    outOfRange: (v: string, unit: string) => `Is ${v} ${unit} right? That is outside what Vitals accepts for a day.`,
    future: 'That month is in the future.',
    needMethod: 'Choose how it was measured',
    needValue: 'Enter the figure',
    kind: { rmr: 'resting', tdee: 'maintenance' },
    /** What the plan does with it (the binding of the method; the engine decides the numbers). */
    use: {
      usedRmr: 'used as your resting energy',
      shownEstimate: "shown, not used: this method estimates, it doesn't measure",
      observation: 'kept as a check: your weigh-ins and logs measure maintenance once a plan starts',
      tdeeMeasured: 'kept as a check next to the estimate',
    },
    line: (value: string, unit: string, kind: string, method: string, date: string | null, use: string) => `Your measurement: ${value} ${unit} ${kind} · ${method}${date ? ` · ${date}` : ''} · ${use}`,
  },
} as const;

/* --------------------------------------------------------------------------------------------- maintenance */

export const DRIVER_LABEL = {
  rmr: 'resting metabolism',
  dailyLiving: 'everyday living',
  steps: 'steps',
  work: 'work beyond sitting',
  home: 'home',
  commute: 'commute',
  recreation: 'sport and hobbies',
  training: 'training',
  digestion: 'digesting food',
} as const;

export const MAINT = {
  title: 'Your maintenance',
  label: 'maintenance',
  headline: (kcal: string, lo: string, hi: string, unit: string) => `about ${kcal} ${unit} a day — likely ${lo}–${hi}`,
  rail: (kcal: string, lo: string, hi: string) => `maintenance ≈ ${kcal} · likely ${lo}–${hi}`,
  railQuiet: 'maintenance: set from your answers',
  openDrivers: 'What drives it',
  quietHeadline: 'Set from your answers — open to see the numbers.',
  showNumbers: 'show numbers',
  hideNumbers: 'hide numbers',
  barLabel: (parts: string) => `Maintenance split into: ${parts}.`,
  tableCaption: 'What your maintenance is made of',
  colPart: 'part',
  colKcal: 'kcal a day',
  colFrom: 'from',
  assumed: 'assumed — you skipped this',
  dashedNote: 'Dashed = this part uses a default (you skipped the question).',
  unknown: {
    steps: (n: string, u = 'kcal') => `Biggest unknown: your steps are a guess. A 2–4-week average from a watch or phone would narrow this by about ±${n} ${u}.`,
    work: (n: string, u = 'kcal') => `Biggest unknown: your work day. Picking the card closest to your job would narrow this by about ±${n} ${u}.`,
    rmr: (n: string, u = 'kcal') => `Biggest unknown: your resting metabolism is estimated from size and age. A measured value would narrow this by about ±${n} ${u}.`,
    home: (n: string, u = 'kcal') => `Biggest unknown: time on your feet at home. Answering it would narrow this by about ±${n} ${u}.`,
    commute: (n: string, u = 'kcal') => `Biggest unknown: your commute. Answering it would narrow this by about ±${n} ${u}.`,
    recreation: (n: string, u = 'kcal') => `Biggest unknown: your sport and hobbies. Minutes a week would narrow this by about ±${n} ${u}.`,
    training: (n: string, u = 'kcal') => `Biggest unknown: your current training. Answering it would narrow this by about ±${n} ${u}.`,
  },
  fix: { steps: 'Add steps', work: 'Answer it', rmr: 'Answer it', home: 'Answer it', commute: 'Answer it', recreation: 'Answer it', training: 'Answer it' },
  comparison: (level: string) => `Similar to people described as "${level}".`,
  level: { inactive: 'inactive', lowActive: 'low active', active: 'active', veryActive: 'very active' },
  calibration: "This is a starting estimate. Once you follow a plan, your weigh-ins and logs correct it — usually within 3–4 weeks.",
  palHigh: "Your answers add up to a very active week. That's possible but rare — check the work and sport answers.",
  palCapped: 'Your answers add up to more than most people sustain, so the estimate is capped.',
  continue: 'Looks right — continue',
  needsBody: 'Add your weight on Your body for a personal number; this uses typical values until then.',
  from: {
    rmr: { measured: 'your measured resting rate', ffm: 'your lean mass', equation: 'your size, age and sex' },
    dailyLiving: 'sitting, standing and moving about the house',
    steps: (n: string, src: string) => `about ${n} a day, ${src}`,
    stepsSource: { wrist: 'from a watch or ring', phone: 'from your phone', estimate: 'your rough number', unknown: 'worked out from your answers', default: 'a typical number' },
    work: (d: number, h: number) => `${d} days × ${h} h`,
    workNone: 'not working outside home',
    home: { little: 'a little on your feet', some: 'some time on your feet', aLot: 'a lot on your feet' },
    commute: 'cycling or walking to work',
    recreation: 'sport and hobbies you listed',
    training: (n: number) => `${n} session${n === 1 ? '' : 's'} a week`,
    digestion: 'about a tenth of what you eat',
  },
} as const;

/* --------------------------------------------------------------------------------------------- chapter 2 */

export const T = {
  experience: {
    prompt: 'How long have you exercised regularly (at least twice a week), in total?',
    short: 'trained regularly',
    skip: 'under 1 year (beginner limits apply)',
    options: { never: 'never', lt1: 'under 1 year', '1to3': '1–3 years', gt3: '3 years or more' },
  },
  willing: {
    prompt: 'Which kinds of exercise would you do as part of a plan?',
    short: 'would do',
    skip: 'all fine',
    help: 'Only the exceptions need a tap. "no" means plans never use it.',
    rowLabel: (family: string) => `Would you do ${family}?`,
    keys: { no: 'no', fine: 'fine', like: 'like' },
    families: {
      lifting: 'lifting weights',
      bodyweight: 'bodyweight',
      indian: 'Indian traditional (dand, baithak, mudgar, gada)',
      yoga: 'yoga',
      walking: 'walking',
      running: 'running',
      cycling: 'cycling',
      swimming: 'swimming',
      sports: 'sports',
      dance: 'dance',
      martial: 'martial arts or kushti',
      intervals: 'hard intervals',
    },
    receiptAll: 'all fine',
    receipt: (no: string[], like: string[]) => [no.length ? `not ${no.join(', ')}` : '', like.length ? `likes ${like.join(', ')}` : ''].filter(Boolean).join(' · ') || 'all fine',
  },
  where: {
    prompt: 'Where can you exercise: at home, a gym, a park or somewhere else?',
    short: 'where',
    skip: 'home',
    options: {
      home: 'home',
      gym: 'a gym',
      park: 'a park with bars',
      akhara: 'an akhara',
      pool: 'a pool',
      stairs: 'stairs in my building',
      court: 'a ground or court',
      walkRoute: 'a safe walking route',
    },
  },
  whereDays: {
    prompt: 'On which days can you use the places you picked (gym, park, pool…)?',
    short: 'which days',
    skip: 'any day',
    place: (p: string) => `days for ${p}`,
  },
  kit: {
    prompt: 'What exercise equipment do you have at home?',
    lead: 'Start from a kit, then adjust.',
    short: 'equipment',
    skip: 'nothing yet',
    kits: {
      none: 'nothing yet (bodyweight)',
      home: 'a few home things',
      bands: 'bands and a pull-up bar',
      dumbbells: 'dumbbells or a kettlebell',
      indian: 'Indian traditional set',
      gym: 'a full gym',
    },
    kitExamples: {
      home: 'chair, backpack, water jugs, mat',
      indian: 'mudgar, jori, gada',
    },
    groups: { weights: 'weights', bands: 'bands and bars', cardio: 'cardio', indian: 'Indian', home: 'at home' },
    somethingElse: 'something else',
    somethingElsePlaceholder: 'e.g. a wooden wheel, a sandbag I made',
    customNote: 'Kept as you wrote it; plans work out what it trains.',
    receiptNone: 'nothing yet',
    receipt: (names: string[], more: number) => `${names.join(', ')}${more > 0 ? ` +${more}` : ''}`,
  },
  weights: {
    prompt: 'How heavy are the weights you have (dumbbells, kettlebells, plates)?',
    short: 'weights',
    skip: 'not sure (plans use "reps to near failure" instead of kg)',
    notSure: 'not sure',
    item: (name: string) => `weights for ${name}`,
    receipt: (parts: string[]) => parts.join(' · '),
  },
  time: {
    prompt: 'How many days a week, and how many minutes each, can you give to exercise?',
    short: 'time',
    skip: '3 × 30 min, any time',
    days: 'days a week',
    minutes: 'minutes per session',
    best: 'best time',
    bestOptions: { morning: 'morning', midday: 'midday', evening: 'evening', any: 'any time' },
    receipt: (d: number, m: number, t: string) => `${d} × ${m} min · ${t}`,
  },
  injuries: {
    prompt: 'Any pain or injury we should work around?',
    short: 'pain or injury',
    skip: 'none',
    options: { shoulder: 'shoulder', elbow: 'elbow', wrist: 'wrist', lumbar: 'low back', cervical: 'neck', knee: 'knee', ankle: 'ankle', hip: 'hip', none: 'none' },
    cleared: (part: string) => `Has a clinician cleared your ${part} for normal training?`,
    yes: 'yes',
    no: 'no',
    effect: {
      shoulder: "We'll leave out overhead pressing and hanging work for your shoulder.",
      elbow: "We'll leave out heavy gripping and pressing that loads the elbow.",
      wrist: "We'll leave out work that loads a bent wrist, such as push-ups on flat hands.",
      lumbar: "We'll leave out heavy hinging and loaded bending for your low back.",
      cervical: "We'll leave out work that loads the neck, such as headstands and bridges.",
      knee: "We'll leave out jumping and deep loaded knee bends.",
      ankle: "We'll leave out jumping and running for your ankle.",
      hip: 'hip: noted — tell the Coach what hurts.',
    },
    clearedNote: 'If a clinician clears it, you can switch this off in Your setup.',
    safetyNote: 'Heart and pregnancy answers from your safety questions already apply.',
    receiptCleared: 'cleared',
  },
  conditions: {
    prompt: 'Do you have any of these conditions that change which exercises are safe?',
    short: 'conditions',
    skip: 'none',
    options: {
      hypertension: "blood pressure that isn't under control",
      glaucoma: 'glaucoma',
      osteoporosis: 'osteoporosis',
      pelvic_floor: 'pelvic-floor problems',
      none: 'none',
    },
    effect: {
      hypertension: "We'll leave out upside-down positions, long hard holds and breath-holding lifts.",
      glaucoma: "We'll leave out upside-down positions.",
      osteoporosis: "We'll leave out loaded bending of the spine and jumping until a clinician clears it.",
      pelvic_floor: "We'll leave out jumping.",
    },
  },
  wontDo: {
    prompt: "Is there any kind of exercise you won't do, or can't do where you live?",
    short: "won't do",
    skip: 'nothing',
    options: { jumping: 'jumping', floor: 'floor work', overhead: 'lifting overhead', running: 'running', noNoise: 'no noise (shared walls)', smallSpace: 'very small space', none: 'nothing' },
    otherLabel: 'anything else',
  },
  buy: {
    prompt: 'If a plan worked better with a small exercise equipment purchase, would you buy it?',
    short: 'small purchases',
    skip: 'no (plans never require purchases)',
    optionsIn: { no: 'no', t1: 'up to ₹1 000', t2: 'up to ₹5 000', t3: 'more' },
    optionsOther: { no: 'no', t1: 'up to $15', t2: 'up to $60', t3: 'more' },
  },
  log: {
    prompt: 'How do you want to log workouts?',
    short: 'logging',
    skip: 'quick sets × reps',
    options: { coach: 'just tell the Coach', quick: 'quick sets × reps', detailed: 'detailed (weight, reps left in the tank)' },
  },
} as const;

/** Friendly names for catalogue equipment ids (fallback: the catalogue's own name). */
export const EQUIPMENT_LABEL: Readonly<Record<string, string>> = {
  dumbbell: 'dumbbells',
  kettlebell: 'kettlebell',
  barbell: 'barbell and plates',
  sandbag: 'sandbag',
  weighted_vest: 'weighted vest',
  band_mini: 'mini band',
  band_tube: 'tube band',
  band_loop_long: 'long loop band',
  pullup_bar: 'pull-up bar',
  dip_bars: 'dip bars',
  suspension_trainer: 'rings or suspension trainer',
  ab_wheel: 'ab wheel',
  treadmill: 'treadmill',
  stationary_bike: 'exercise bike',
  bicycle: 'bicycle',
  rower: 'rower',
  elliptical: 'cross-trainer',
  jump_rope: 'skipping rope',
  mudgar_heavy: 'mudgar',
  mudgar_pair: 'mudgar pair (jori)',
  indian_clubs: 'Indian clubs',
  gada: 'gada',
  steel_mace: 'steel mace',
  sumtola: 'sumtola',
  gar_nal: 'gar nal',
  rope_mallakhamb: 'mallakhamb or rope',
  chair: 'sturdy chair',
  table: 'table',
  stairs: 'stairs',
  backpack: 'backpack',
  water_jug: 'water jugs',
  bucket: 'bucket',
  towel: 'towel',
  floor_mat: 'mat',
  squat_rack: 'squat rack',
  bench: 'bench',
  plates: 'plates',
  door_anchor: 'door anchor',
};

/* --------------------------------------------------------------------------------------------- chapter 3 */

export const F = {
  eat: {
    prompt: 'Which of these do you eat?',
    lead: 'Start from one, then adjust.',
    short: 'you eat',
    skip: 'nothing is assumed — recipes pause until you answer',
    presets: { vegetarian: 'vegetarian (with dairy)', eggetarian: 'eggetarian', vegan: 'vegan', jain: 'Jain', pescatarian: 'pescatarian', everything: 'everything' },
    foods: { dairy: 'dairy', eggs: 'eggs', fish: 'fish', shellfish: 'shellfish', chicken: 'chicken', mutton: 'mutton or goat', beef: 'beef', pork: 'pork' },
    receiptNothing: 'no animal foods',
  },
  dairy: {
    prompt: 'Do you avoid any dairy foods, such as milk, curd or paneer?',
    short: 'dairy',
    skip: 'as ticked above',
    options: { none: 'vegan — no dairy', ghee_only: 'ghee only', yes: 'all dairy is fine' },
  },
  eggs: {
    prompt: 'You eat eggs: as eggs (boiled, omelette), or only when baked into food like cake?',
    short: 'eggs',
    skip: 'eggs as eggs',
    options: { yes: 'eggs as eggs', baked_only: 'only inside baked food' },
  },
  allergies: {
    prompt: 'Do you have any food allergies?',
    short: 'allergies',
    skip: 'not answered — recipes pause until you answer ("none" counts only when picked)',
    options: {
      'gluten-cereals': 'gluten cereals',
      crustacean: 'crustaceans',
      mollusc: 'molluscs',
      milk: 'milk',
      egg: 'egg',
      fish: 'fish',
      peanut: 'peanut',
      'tree-nut': 'tree nuts',
      soy: 'soy',
      sesame: 'sesame',
      mustard: 'mustard',
      celery: 'celery',
      lupin: 'lupin',
      sulphite: 'sulphites',
      none: 'none',
    },
    otherLabel: 'other allergy',
    hard: 'Recipes will never include these, not even as a garnish.',
  },
  traces: {
    prompt: "For your food allergies, should even traces (for example 'may contain') be avoided?",
    short: 'traces',
    skip: 'strict — traces count too',
    options: { strict: 'strict — traces count too', normal: 'normal' },
  },
  rules: {
    prompt: 'Do you follow any of these religious or food rules?',
    short: 'rules',
    skip: 'not answered — recipes pause until you answer ("none" counts only when picked)',
    options: { jain: 'Jain', noOnionGarlic: 'no onion or garlic', halal: 'halal', kosher: 'kosher', hinduFasting: 'Hindu fasting days', ramadan: 'Ramadan', lent: 'Lent', none: 'none' },
    hard: 'Recipes will never break these.',
  },
  jain: {
    prompt: 'Which Jain rules do you keep?',
    short: 'Jain rules',
    skip: 'no onion or garlic',
    help: 'Observance varies, so each one is separate.',
    options: {
      noRootVeg: 'no root vegetables',
      noOnionGarlic: 'no onion or garlic',
      noHoney: 'no honey',
      noAfterSunset: 'no eating after sunset',
      noFermented: 'no fermented food',
      noMushroom: 'no mushrooms',
      greens: 'no green leafy vegetables on certain days',
    },
  },
  jainGreensDays: {
    prompt: 'On which days do you avoid green leafy vegetables?',
    short: 'days without greens',
    skip: 'none',
  },
  fasting: {
    prompt: 'Which days or periods do you fast?',
    short: 'fasting days',
    skip: 'none set',
    periods: { Ekadashi: 'Ekadashi', Navratri: 'Navratri', Shravan: 'Shravan', custom: 'other' },
  },
  fastingFood: {
    prompt: 'On your fasting days, what do you eat?',
    short: 'on fasting days',
    skip: 'vrat foods',
    options: { vrat_foods: 'vrat foods', fruit_milk: 'fruit and milk only', nothing: 'nothing' },
  },
  ramadanNote: 'Your fasting window goes to the planner: meals become suhoor and iftar during Ramadan.',
  meatDays: {
    prompt: 'Are there days of the week when you skip meat or eggs?',
    short: 'days without meat or eggs',
    skip: 'none',
  },
  cuisine: {
    prompt: 'Which cuisines do you cook or eat most often?',
    short: 'cuisines',
    skip: 'set by your region',
    help: 'Tap in order: the first tap is what you eat most often.',
    options: {
      north_indian: 'north Indian',
      south_indian: 'south Indian',
      gujarati: 'Gujarati',
      bengali: 'Bengali',
      maharashtrian: 'Maharashtrian',
      punjabi: 'Punjabi',
      kerala: 'Kerala',
      goan: 'Goan',
      indo_chinese: 'Indo-Chinese',
      mediterranean: 'Mediterranean',
      american: 'American',
      british: 'British',
      mexican: 'Mexican',
      east_asian: 'East Asian',
      middle_eastern: 'Middle Eastern',
      other: 'other',
    },
    rank: (n: number) => `${n}`,
  },
  cooks: {
    prompt: 'Who cooks most of your meals?',
    short: 'who cooks',
    skip: 'I do',
    options: { self: 'I do', family: 'family', paid_cook: 'a paid cook', tiffin: 'tiffin or mess', eatOut: 'I mostly eat out', mixed: 'a mix' },
  },
  household: {
    prompt: 'At home, what does a normal lunch and dinner look like?',
    short: 'normal meals',
    skip: 'plans start from typical home food',
    placeholder: 'e.g. 3 rotis, dal, sabzi, rice at dinner',
    note: 'Plans adjust portions and add-ons, not the dishes.',
  },
  kitchen: {
    prompt: 'What cooking equipment do you have in your kitchen?',
    short: 'kitchen',
    skip: 'the usual for your region',
    options: {
      pressure_cooker: 'pressure cooker',
      tawa: 'tawa',
      kadhai: 'kadhai',
      gas_2burner: 'gas',
      induction: 'induction',
      mixer_grinder: 'mixer-grinder',
      idli_steamer: 'idli steamer',
      microwave: 'microwave',
      otg_oven: 'OTG oven',
      oven: 'oven',
      air_fryer: 'air fryer',
      rice_cooker: 'rice cooker',
      instant_pot: 'Instant Pot',
      slow_cooker: 'slow cooker',
      blender: 'blender',
      grill: 'grill',
      fridge: 'fridge',
      freezer: 'freezer',
      kitchen_scale: 'kitchen scale',
    },
  },
  time: {
    prompt: 'On a weekday, how many minutes can you spend making a main meal?',
    short: 'cooking time',
    skip: '10–20 min',
    options: { lt10: 'under 10 min', '10to20': '10–20', '20to40': '20–40', gt40: '40+' },
    receipt: { lt10: 'under 10 min', '10to20': '10–20 min', '20to40': '20–40 min', gt40: '40+ min' },
  },
  alcohol: {
    prompt: 'Do you drink alcohol, even now and then?',
    short: 'alcohol',
    skip: 'not asked',
    why: 'Plans count it like any other energy. No judgement either way.',
    options: { no: 'no', sometimes: 'now and then', weekly: 'most weeks' },
  },
  drinks: {
    prompt: 'About how many alcoholic drinks do you have in a week?',
    short: 'drinks a week',
    skip: 'about 4',
    name: 'drinks a week',
  },
  supplements: {
    prompt: 'Would you rather get everything from food, or are you open to supplements?',
    short: 'supplements',
    skip: 'food first',
    options: { food_first: 'food first', open: 'open to supplements', taking: 'I already take some' },
    foodFirstNote: 'No products are ever suggested. Safety notes (such as B12 for vegetarians) still appear as "consider testing — ask a doctor".',
  },
  taking: {
    prompt: 'Which supplements do you take now, and how much of each?',
    short: 'taking',
    skip: 'none listed',
    dose: (name: string) => `dose of ${name}`,
    when: 'when',
    times: { morning: 'morning', midday: 'midday', evening: 'evening', night: 'night' },
  },
  staples: {
    prompt: 'Which grains and cooking fats do you use most often?',
    short: 'staples',
    skip: 'set by your cuisine',
    grain: { rice: 'rice', wheat_roti: 'wheat roti', millet: 'millet', bread: 'bread', pasta: 'pasta', oats: 'oats' },
    fat: { mustard: 'mustard oil', groundnut: 'groundnut oil', coconut: 'coconut oil', ghee: 'ghee', olive: 'olive oil', sunflower: 'sunflower oil', butter: 'butter' },
  },
  budget: {
    prompt: 'How tight is your food budget for the week?',
    short: 'budget',
    skip: 'normal',
    options: { tight: 'tight', normal: 'normal', flexible: 'flexible' },
  },
  eatingOut: {
    prompt: 'How many meals a week do you eat out or order in?',
    short: 'eating out',
    skip: 'about 2',
    name: 'meals out a week',
  },
  pantry: {
    prompt: 'Which of these foods do you have in your kitchen right now?',
    short: 'in the kitchen',
    skip: 'asked when you plan a day',
    help: 'Salt and everyday spices are assumed.',
    options: {
      atta: 'atta',
      rice: 'rice',
      poha: 'poha',
      rava: 'rava',
      besan: 'besan',
      dal: 'dals',
      rajma: 'rajma',
      chole: 'chole',
      oats: 'oats',
      bread: 'bread',
      pasta: 'pasta',
      eggs: 'eggs',
      milk: 'milk',
      curd: 'curd',
      paneer: 'paneer',
    },
  },
  medical: (items: string) => `From your safety answers: ${items}.`,
  medicalWords: {
    coeliac: 'no gluten',
    'CKD-protein-limit': 'protein as your clinician advises',
    'warfarin-vitK-consistency': 'steady vitamin K',
    'MAOI-tyramine': 'low tyramine',
    'low-sodium': 'low sodium',
    diabetes: 'carbohydrate spread through the day',
  },
} as const;

/** Weekday names indexed by the catalogue's `Weekday` (0 = Sunday); shown Monday first. */
export const WEEKDAY = {
  short: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  long: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  order: [1, 2, 3, 4, 5, 6, 0],
} as const;

/* --------------------------------------------------------------------------------------------- chapter 4 */

export const D = {
  has: {
    prompt: 'Do you wear or use any of these?',
    short: 'devices',
    skip: 'none (all streams stay off)',
    options: { ring: 'ring', watch: 'watch', band: 'fitness band', scale: 'smart scale', chestStrap: 'chest strap', phoneOnly: 'just my phone', none: 'none' },
  },
  which: {
    prompt: 'Which brand and model is each of your devices?',
    short: 'models',
    skip: 'not sure',
    device: (d: string) => `which ${d}`,
    search: 'search brands',
    notSure: 'not sure',
  },
  platform: {
    prompt: 'Which kind of phone do you use?',
    short: 'phone',
    skip: 'not sure',
    options: { android: 'Android', ios: 'iPhone', desktop: 'computer only' },
  },
  route: {
    prompt: "How will each device's data reach Vitals?",
    short: 'how data arrives',
    later: 'Later',
    settings: 'Set up any of these later in Settings › Devices and streams. Nothing connects from here.',
    settingsLead: 'Set up any of these later in ',
    settingsLink: 'Settings › Devices and streams',
    settingsTail: '. Nothing connects from here.',
    healthConnect: (brand: string) => `${brand} writes to Health Connect. Vitals can't read Health Connect from a web page, so you export a file from it (or, later, a small helper app sends it).`,
    direct: 'Connect directly. Sync happens while Vitals is open; close the ring\'s own app first.',
    noBluetooth: 'Direct connection needs Chrome or Edge on Android or a computer.',
    iphone: 'Export from Apple Health, or use a Shortcut that saves a file each day.',
    file: (brand: string) => `Export a file from the ${brand} app and import it.`,
    scale: 'Export your weigh-ins from the scale app as a file and import it.',
    importFile: 'Import a file',
    connect: 'Connect ring',
    howTo: 'How to',
  },
  matrix: {
    prompt: 'For each kind of data your device records, what may Vitals do with it?',
    short: 'streams',
    skip: 'everything stays off (recommended is not applied on skip)',
    cols: { imported: 'bring in', scores: 'my scores', engine: 'my plan', coach: 'Coach sees' },
    coach: { hidden: 'hidden', daily: 'daily', 'daily+series': 'daily + detail' },
    streams: {
      sleep_sessions: 'sleep',
      heart_rate: 'heart rate',
      hrv: 'HRV',
      spo2: 'SpO2',
      steps: 'steps',
      workouts: 'workouts',
      weight: 'weight',
      body_fat: 'body fat',
      skin_temp: 'skin temperature',
      vendor_scores: 'vendor scores',
    },
    switchLabel: (col: 'imported' | 'scores' | 'engine', stream: string) =>
      col === 'imported' ? `Bring ${stream} into Vitals` : col === 'scores' ? `Use ${stream} in my scores` : `Use ${stream} in my plan`,
    coachLabel: (stream: string) => `What the Coach sees of ${stream}`,
    never: 'never',
    na: '—',
    neverWhy: {
      spo2: "No established mechanism links SpO2 to your plan, so it's shown and trended only.",
      vendor_scores: "Vendor scores are the vendor's opinion; Vitals computes its own from the raw data.",
    },
    suggested: 'suggested',
    recommended: 'Use recommended',
    coachDaily: 'Coach can see daily summaries',
    none: 'No streams — pick a device above to choose.',
    caption: 'Choose what each stream does',
  },
  privacy: [
    'Your device data stays on your own devices, and on your own server if you pair one. No one else holds it.',
    'A ring you connect through Vitals shares its data with your plan, your scores and the Coach from the start. You can turn that off in one tap, or for each stream. Data from files and other apps stays off until you turn it on.',
    "The Coach only sees a stream you let it see ('daily' or 'daily + detail'), and only when you talk to it. It never sees vendor scores unless you allow them, and they're labelled as the vendor's opinion.",
    'Ring and watch indexes are estimates, not measurements. Vitals computes its own scores from the raw data and shows how sure each one is.',
  ],
} as const;

export const BRANDS = ['Oura', 'Apple Watch', 'Garmin', 'Samsung', 'Fitbit / Google', 'WHOOP', 'Polar', 'Amazfit / Zepp', 'Colmi', 'J-Style ring', 'Ultrahuman', 'RingConn', 'Withings', 'Polar H10', 'other'] as const;

/* --------------------------------------------------------------------------------------------- summary */

export const SUMMARY = {
  title: "What we'll use",
  picture: 'Your picture so far',
  lead: "Here's what Vitals will work from.",
  change: 'change',
  changeLabel: (chapter: string) => `Change ${chapter}`,
  askedLater: 'asked later',
  askedLaterValue: (n: number) => (n === 0 ? 'nothing' : `${n} question${n === 1 ? '' : 's'}`),
  answerNow: 'Answer now',
  answer: 'Answer',
  notAnswered: 'not answered yet',
  continue: 'Looks right — continue',
  backToBody: 'Back to Your body',
  activity: (parts: string[]) => parts.join(' · '),
  foodUnset: 'not answered — recipes are paused',
  devicesNone: 'no devices · every stream off',
  coachNothing: 'Coach sees nothing yet',
  coachSome: (n: number) => `Coach sees ${n} stream${n === 1 ? '' : 's'}`,
  streamsIn: (names: string) => `${names} in`,
} as const;

/* --------------------------------------------------------------------------------------------- Body page */

export const BODY = {
  normalDay: 'a normal day',
  edit: 'Edit a normal day',
  start: 'Answer a few questions about a normal day',
  notAnswered: 'not answered — maintenance uses typical activity',
  reminder: (n: number) => `${n} question${n === 1 ? '' : 's'} asked later`,
  reminderLabel: (n: number) => `${n} question${n === 1 ? '' : 's'} asked later — answer now`,
  setupTitle: 'Your setup',
  setupLead: 'Answer any part, in any order, and change any answer later.',
  chapterStatus: { done: 'answered', partial: (n: number, t: number) => `${n} of ${t}`, todo: 'not started' },
  startChapter: 'start',
  answerNow: 'answer now',
  maintTitle: 'Maintenance',
  maintCaption: 'what drives it',
  measuredTitle: 'Measured before?',
  answersTitle: 'A normal day: your answers',
} as const;
