/**
 * User-facing copy shared by Living screens (design/screens/living-mode.md). Plain, specific, second person; no internal
 * references (spec names, section signs, package ids) — `__tests__/copy.test.ts` scans every `copy.ts` under
 * `src/features/living`. Never moralising: a gap is "not logged", never "failed"; no streaks, no exclamation marks.
 */

export const GUARD_COPY = {
  noPlan: 'Start a plan to use Today.',
} as const;

/** Mode strip and return key (COMPONENTS §13.17; IA §3.4). */
export const STRIP_COPY = {
  running: (name: string) => `${name} is running`,
  scheduled: (name: string) => `${name} starts soon`,
  paused: (name: string) => `${name} is paused`,
  dayOf: (day: number, of: number) => `day ${day} of ${of}`,
  safe: 'Changes here don’t touch it until you replace it.',
  back: 'Back to Today',
  returnKey: 'today',
  planningTools: 'planning',
  planningToolsMenu: 'Planning tools',
} as const;

export const TODAY_COPY = {
  title: 'Today',
  menu: 'Today menu',
  menuItems: {
    replanRest: 'Re-plan the rest (same goals)',
    replanScratch: 'Re-plan from scratch',
    checkIn: 'Check in now',
    away: 'I’m busy or away…',
    fast: 'Log a fast…',
    pause: 'Pause plan',
    resume: 'Resume plan',
    end: 'End plan…',
    details: 'Plan details',
    planning: 'Planning tools',
  },
  planFace: 'Today’s plan',
  markDay: 'Mark day as planned',
  dayMarked: 'Day marked as planned',
  intentions: (weighIn: string | null, missed: string | null) => [weighIn ? `Weigh in at ${weighIn} before breakfast` : null, missed].filter(Boolean).join(' · '),
  missed: { nextDay: 'missed a session? do it tomorrow', skip: 'missed a session? skip it', shorter: 'missed a session? do a shorter one' },
  untimed: 'any time',
  howHard: 'how hard was today?',
  howHardTitle: 'How hard was today?',
  howHardScale: '1 easy · 3 OK · 5 very hard',
  soFar: 'So far',
  soFarWord: 'so far',
  basedOn: (n: number, of: number) => `based on ${n} of ${of} items`,
  notEnough: 'not enough logged',
  eaten: 'eaten',
  protein: 'protein',
  daysLogged: (n: number) => `${n} of the last 7 days logged`,
  forecast: 'Against the forecast',
  trend: (kg: string) => `trend ${kg} kg`,
  expected: (range: string) => `expected today ${range}`,
  goalDate: (range: string) => `goal date likely ${range}`,
  goalShift: (days: number, sd: number) => `moved by ${days > 0 ? '+' : '−'}${Math.abs(days)} days (±${sd})`,
  forecastFailed: 'Forecast not updated',
  tryAgain: 'Try again',
  unusualWeighIn: (delta: string) => `This weigh-in is unusual (${delta} kg). Salt, travel, a late meal or illness? It’s kept but weighs less.`,
  noTrend: 'Your trend starts after about a week of weigh-ins.',
  drift: { ahead: 'ahead', onTrack: 'on track', behind: 'behind' },
  signals: 'Body signals',
  showNumbers: 'show numbers',
  hideNumbers: 'hide numbers',
  rowSheet: { asPlanned: 'as planned', partly: 'partly', skipped: 'skipped', else: 'something else' },
  tickName: (label: string) => `Mark ${label} as planned`,
  ticked: (label: string) => `${label} marked as planned. Undo available.`,
  undo: 'Undo',
  weighIn: 'weigh in',
  weighInName: 'weight',
  notices: { more: (n: number) => `+${n} more` },
  scheduled: (name: string, date: string) => `${name} starts ${date}.`,
  beforeDay1: 'Before day 1',
  firstWeighIn: (time: string) => `First weigh-in tomorrow at ${time}, after the bathroom, before eating.`,
  changeStart: 'Change start date',
  discardPlan: 'Discard plan',
  previewDay: 'A preview of day 1',
  paused: (date: string) => `Paused since ${date}.`,
  pausedBody: 'Your usual days until you resume; what you log still counts.',
  resume: 'Resume',
  welcomeBack: 'Welcome back. Nothing to catch up on.',
  welcomeBackBody: 'Today’s plan is below.',
  backfill: (n: number) => `Fill the ${n} missed day${n === 1 ? '' : 's'} in as planned?`,
  backfillYes: 'Yes, as planned',
  backfillNo: 'Leave them empty',
  complete: (name: string) => `${name} is complete.`,
  keepResult: 'Keep the result',
  planAgain: 'Plan again',
  pastDay: 'this day’s plan as it was',
  futureDay: 'Preview · the plan may still change',
  checkInCard: (weekday: string, n: number) => `Weekly check-in · ${weekday} · ${n} weigh-in${n === 1 ? '' : 's'} this week`,
  checkIn: 'Check in',
  endTitle: (name: string) => `End ${name}?`,
  endBody: 'It ends today. Your logs and versions are kept, and you can restore it for 7 days.',
  endType: 'Type end to confirm.',
  endKey: 'End plan',
  pauseTitle: 'Pause the plan',
  pauseBody: 'Paused days prescribe your usual day. What you log still counts.',
  pauseKey: 'Pause plan',
  replanning: (days: number) => `Re-planning the remaining ${days} days…`,
  replanReady: 'A proposal is waiting on Today.',
  replanDidntFinish: 'The re-plan didn’t finish. Try again.',
  awayTitle: 'Busy or away',
  awayBody: 'Tell the plan about the days. It fits the rest around them and shows you the change before anything moves.',
  awayKind: 'what’s happening',
  awayKinds: { busy: 'busy', travel: 'travelling', illness: 'unwell', noTraining: 'no training', socialMeal: 'a meal out' },
  awayFrom: 'from',
  awayTo: 'to',
  awayOn: 'on',
  awayNote: 'note (optional)',
  awayNoteHelp: 'Only you see this.',
  awayPushBack: 'Push the plan back by these days instead',
  awayPushBackHelp: (days: number) => `Your usual days on those dates; the plan ends ${days} day${days === 1 ? '' : 's'} later.`,
  awayKey: 'Tell the plan',
  awayWorking: 'Fitting the plan around those days…',
  awayDidntFinish: 'That didn’t go through. Try again.',
  fastTitle: 'Log a fast',
  fastBody: 'A fast you did, on any day. It runs from the last thing you ate to the first thing you ate after it.',
  fastStart: 'last ate (fast started)',
  fastEnd: 'first ate (fast ended)',
  fastLength: (length: string) => `A fast of ${length}.`,
  fastEndBeforeStart: 'The end has to be after the start.',
  fastFuture: 'The end can’t be later than now.',
  fastTooLong: (maxH: number) => `A fast logged here can be up to ${maxH} hours.`,
  fastMissing: 'Enter a date and time.',
  fastKey: 'Log fast',
  fastLogged: (length: string) => `Fast of ${length} logged.`,
  cancel: 'Cancel',
} as const;

export const START_COPY = {
  title: (rung: string) => `Start ${rung}`,
  name: 'Plan name',
  defaultName: (rung: string, month: string) => `${rung} plan · ${month}`,
  startDate: 'Start date',
  startChoices: { today: 'today', tomorrow: 'tomorrow', nextMonday: 'next Monday', pick: 'pick a date' },
  checkInDay: 'Weekly check-in',
  weighInTime: 'Weigh-in time',
  trainingDays: 'Training days',
  ifMissed: 'If I miss a session',
  missedChoices: { nextDay: 'do it the next day', skip: 'skip it', shorter: 'do a shorter one' },
  beforeDay1: 'Before day 1',
  nothingToBuy: 'Nothing to buy.',
  groceries: 'Groceries for the first 3 days are on Food once the plan starts.',
  start: 'Start plan',
  replace: 'Replace active plan…',
  replaceTitle: (name: string) => `Replace ${name}?`,
  replaceBody: 'It ends today and is kept in your history; you can restore it for 7 days.',
  replaceType: 'Type replace to confirm.',
  replaceKey: 'Replace plan',
  startsToast: (name: string, when: string) => `${name} starts ${when}`,
  undo: 'Undo',
  failed: 'The plan couldn’t be started.',
  starting: 'Starting the plan…',
  entry: 'Start this plan',
} as const;
