/**
 * User-facing copy for the Food screen (design/screens/living-mode.md, Food). Plain, specific, second person; never
 * moralising (a gap is "not logged", never "failed"); no streaks, no exclamation marks, no internal references.
 * `src/features/living/__tests__/copy.test.ts` scans this module.
 */

const cap = (s: string) => (s ? s[0]!.toUpperCase() + s.slice(1) : s);
const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const FOOD_COPY = {
  title: 'Food',
  menu: 'Food menu',
  menuItems: {
    kitchen: 'Use what’s in my kitchen',
    pantry: 'Pantry',
    noBenefit: 'Things that won’t help',
  },
  dateStrip: 'Day',
  preview: 'Preview · the plan may still change',
  previewHelp: 'You can plan recipes for this day now and log it when it comes.',
  pastDay: 'this day’s plan as it was · you can still log what you ate',
  noPlanDay: 'There’s no plan for this day.',
  showNumbers: 'show numbers',
  hideNumbers: 'hide numbers',

  targets: {
    title: 'Targets',
    caption: 'today’s prescription',
    kcal: (v: string) => `${v} kcal`,
    protein: (v: string) => `protein ${v} g`,
    carbs: (v: string) => `carbs ${v} g`,
    fat: (v: string) => `fat ${v} g`,
    fibre: (v: string) => `fibre ${v} g`,
    eaten: 'eaten',
    nothingYet: 'nothing logged yet',
    quietEaten: (word: string) => `eaten: ${word}`,
    quietNote: 'Amounts are hidden in quiet mode. Portions and dishes stay.',
    bars: { energy: 'energy', protein: 'protein', carbs: 'carbs', fat: 'fat', fibre: 'fibre' },
    of: 'of',
    target: 'target',
    left: (n: string, unit: string) => `${n} ${unit} left`,
    over: (n: string, unit: string) => `+${n} ${unit} over`,
    likely: (range: string, unit: string) => `likely ${range} ${unit}`,
    likelyShort: (range: string) => `likely ${range}`,
    barLabel: (what: string, eaten: string, target: string, unit: string, range: string | null) =>
      `${what}: eaten about ${eaten} of ${target} ${unit}${range ? ` (likely ${range})` : ''}`,
    barNone: (what: string, target: string, unit: string) => `${what}: nothing logged yet of ${target} ${unit}`,
    ofTarget: (target: string) => `of ${target}`,
  },

  meals: {
    title: 'Meals',
    planDay: 'Plan my day',
    planAgain: 'Plan again',
    running: 'Planning recipes for the open meals…',
    progress: { waiting: 'waiting', working: 'planning…', done: 'ready', error: 'no recipe' },
    progressLabel: 'Recipe progress',
    noProvider: 'Connect an AI provider to get recipes.',
    setUpProvider: 'Set up a provider',
    noDiet: 'Tell us what you eat to get recipes',
    noDietReason: 'Tell us what you eat to get recipes.',
    noDietLink: 'Tell us what you eat',
    nothingOpen: 'Every meal here is planned or logged.',
    pastReason: 'Past days can be logged, not planned.',
    fastDay: 'fast day — water, tea, coffee; electrolytes if over 24 h',
    hiddenByFast: (n: number) => `${plural(n, 'meal is', 'meals are')} outside today’s eating window and not shown.`,
    other: 'Other food',
    logOther: 'Log other food',
    familyNote: 'Someone else cooks: meals show portions and add-ons rather than dishes.',
  },

  slot: {
    numbers: (kcal: string, protein: string) => `${kcal} kcal · ${protein} g protein`,
    carbsFat: (carbs: string, fat: string) => `${carbs} g carbs · ${fat} g fat`,
    moreName: (slot: string) => `More for ${slot}`,
    openItem: 'Recipe and targets',
    plain: (p: string, c: string, f: string) => `about ${p} g protein, ${c} g carbs, ${f} g fat`,
    example: (ex: string) => `for example ${ex}`,
    plainQuiet: (ex: string) => `For example ${ex}.`,
    accepted: 'accepted',
    suggested: 'suggested',
    accept: 'Accept',
    acceptName: (dish: string, slot: string) => `Accept ${dish} for ${slot}`,
    swap: 'Swap',
    swapName: (slot: string) => `Swap the ${slot} recipe`,
    ateThis: 'As planned',
    ateThisName: (slot: string) => `I ate this: ${slot} as planned`,
    ateElse: 'I ate something else',
    ateElseName: (slot: string) => `I ate something else: ${slot}`,
    addMore: 'Add more',
    addMoreName: (slot: string) => `Add more food to ${slot}`,
    logged: 'logged',
    markedAsPlanned: 'marked as planned',
    open: (slot: string) => `Open ${slot} details`,
    failed: 'Couldn’t make a recipe this time.',
    tryAgain: 'Try again',
    tryAgainName: (slot: string) => `Try again: ${slot} recipe`,
    dontSuggest: (dish: string) => `Don’t suggest ${dish} again?`,
    dontSuggestKey: 'Don’t suggest',
    itsFine: 'It’s fine',
    closestSide: 'Add a protein-rich side, such as 150 g curd?',
    closestQuiet: 'closest fit',
    minutes: (n: number) => `${n} min`,
    notEstimated: 'amount not estimated yet',
    estimated: 'estimated composition',
    familyEat: (portions: string) => `Eat ${portions}`,
  },

  toasts: {
    loggedAsPlanned: (slot: string) => `${cap(slot)} logged as planned`,
    logged: (slot: string) => `${cap(slot)} logged`,
    loggedOther: 'Food logged',
    accepted: (slot: string) => `${cap(slot)} planned · groceries updated`,
    unplanned: (slot: string) => `${cap(slot)} recipe removed from the plan`,
    taken: (name: string) => `${cap(name)} marked as taken`,
    copied: 'Grocery list copied',
    copyFailed: 'Couldn’t copy the list here. Use Print instead.',
    undo: 'Undo',
    notSaved: 'That wasn’t saved. Try again.',
  },

  recipe: {
    servings: (n: number) => plural(n, 'serving', 'servings'),
    servingsLabel: 'makes',
    active: (n: number) => `${n} min active`,
    passive: (n: number) => `${n} min waiting`,
    cuisine: 'cuisine',
    time: 'time',
    equipment: 'equipment',
    ingredients: 'ingredients',
    steps: 'steps',
    perServing: 'per serving',
    why: 'why this fits',
    energy: 'energy',
    protein: 'protein',
    carbs: 'carbs',
    fat: 'fat',
    fibre: 'fibre',
    numbersHidden: 'Amounts per serving are hidden in quiet mode.',
    remove: 'Remove from the plan',
    slotTitle: (slot: string) => `${cap(slot)} targets`,
    noRecipe: 'No recipe yet. Any meal with these amounts fits; a different dish with the same nutrients counts the same.',
    targetRows: { energy: 'energy', protein: 'protein', carbs: 'carbs', fat: 'fat' },
  },

  logger: {
    title: (slot: string | null) => (slot ? `What did you eat for ${slot}?` : 'What did you eat?'),
    search: 'Search foods',
    searchHelp: 'Try dal, paneer, rice or curd.',
    noResults: 'Nothing found. Describe it below instead.',
    add: (name: string) => `Add ${name}`,
    remove: (name: string) => `Remove ${name}`,
    picked: 'what you ate',
    unit: (name: string) => `Unit for ${name}`,
    grams: 'grams',
    howMany: (name: string) => `How many for ${name}`,
    gramsOf: (name: string) => `Grams of ${name}`,
    describe: 'Or describe it',
    describeHelp: 'For example: 2 idlis with sambar.',
    kcal: 'Energy, if you know it',
    protein: 'Protein, if you know it',
    recents: 'recent',
    sameAs: (slot: string) => `same as yesterday’s ${slot}`,
    yesterday: (label: string) => `yesterday: ${label}`,
    log: (slot: string | null) => (slot ? `Log ${slot}` : 'Log it'),
    needSomething: 'Pick a food or describe what you ate.',
    coach: 'Tell the Coach instead',
    estimated: 'estimated composition',
    estimatedNote: 'These food values are estimates; ranges are wider.',
    about: (kcal: string) => `≈ ${kcal} kcal`,
    portion: (count: string, label: string) => `${count} × ${label}`,
  },

  groceries: {
    title: 'Groceries',
    caption: { today: 'today', '3days': 'next 3 days', week: 'next 7 days' },
    horizon: { today: 'today', '3days': '3 days', week: 'week' },
    horizonLabel: 'Groceries for',
    count: (n: number) => plural(n, 'item', 'items'),
    empty: 'Accept a recipe and its ingredients show up here.',
    emptyNoProvider: 'Groceries come from the recipes you accept.',
    aisles: { vegetables: 'vegetables', dairy: 'dairy', staples: 'staples', protein: 'protein', spices: 'spices' },
    have: 'have it',
    atHome: 'at home',
    toBuy: (n: number) => (n === 0 ? 'nothing left to buy' : `${n} to buy`),
    atHomeCount: (n: number) => `${n} at home`,
    boughtCount: (n: number) => `${n} bought`,
    haveName: (name: string) => `Already have ${name}`,
    share: 'Share',
    print: 'Print',
    budgetQ: 'Roughly what’s your food budget?',
    budget: { tight: 'tight', normal: 'normal', flexible: 'flexible' },
    later: 'ask me later',
    budgetSet: (tier: string) => `budget: ${tier}`,
    actionBar: (n: number) => `Groceries · ${plural(n, 'item', 'items')}`,
    shareTitle: 'Groceries',
    shareHeader: (range: string) => `Groceries · ${range}`,
    shareHave: 'already have',
  },

  supplements: {
    title: 'Supplements',
    taken: 'taken',
    takenName: (name: string) => `Mark ${name} as taken`,
    undoTakenName: (name: string) => `Undo ${name} taken`,
    anyTime: 'any time',
    at: (time: string) => `at ${time}`,
    youTake: (dose: string) => `you take ${dose}`,
    planSuggests: (dose: string) => `plan suggests ${dose}`,
    none: 'No supplements in your plan.',
    yours: 'yours',
    foodFirst: 'food first',
    open: 'options for your goals',
    stanceNote: 'You chose food first, so no products are shown.',
    stanceLink: 'Change this in your setup',
    b12: 'Vegetarian diets are often low in vitamin B12 — consider a test; ask a doctor.',
    foodFirstLines: {
      protein: 'Short of protein at a meal? Add 200 g curd or 100 g paneer.',
      fibre: 'Fibre: dal, chana, rajma, oats or vegetables at each meal.',
    },
    thirdParty: 'Choose a product with third-party batch testing (for example Informed Sport or NSF). Vitals can’t check brands.',
    hiddenForSafety: (n: number) => `${plural(n, 'option is', 'options are')} not shown because of your safety answers — ask your doctor.`,
    dose: 'dose',
    when: 'when',
    why: 'why for your goals',
    caution: 'good to know',
    foodFirstAlt: 'food first',
    noBenefitKey: 'What won’t help',
    takingChanges: 'Supplements you take change the plan only through a proposal you can review.',
  },

  /** Plain-language cards (the catalogue keeps the evidence and sources). Keyed by catalogue id. */
  supplementCards: {
    creatine_monohydrate: {
      name: 'creatine',
      dose: '3–5 g a day',
      when: 'any time, every day, with a meal',
      why: 'does help muscle with training',
      caution: 'adds 0.5–1.5 kg of water on the scale — your trend accounts for it',
      foodFirst: 'Food can’t practically supply this amount.',
    },
    whey_protein: {
      name: 'whey protein',
      dose: '20–40 g protein when a meal is short',
      when: 'with the meal that is short of protein',
      why: 'does help keep muscle while you lose fat, when your protein would otherwise fall short',
      caution: 'only useful to close a gap to your protein target',
      foodFirst: 'Curd, paneer, eggs, or dal with soy chunks.',
      foodFirstNoEggs: 'Curd, paneer, or dal with soy chunks.',
    },
    plant_protein: {
      name: 'plant protein powder',
      dose: '25–40 g protein when a meal is short',
      when: 'with the meal that is short of protein',
      why: 'works like whey when the serving is a little larger',
      caution: 'only useful to close a gap to your protein target',
      foodFirst: 'Soy chunks, tofu, dal with grains.',
    },
    psyllium: {
      name: 'psyllium husk (isabgol)',
      dose: '5 g, 1–3 times a day',
      when: 'with a large glass of water, before or with a meal',
      why: 'helps you reach your fibre target and stay full',
      caution: 'start low and add slowly to avoid bloating; always with enough water',
      foodFirst: 'Oats, dal, chana, rajma, vegetables and fruit.',
    },
    caffeine: {
      name: 'caffeine',
      dose: 'about 3 mg per kg before training, at most 400 mg a day',
      when: '30–60 minutes before training, not late in the day',
      why: 'does help training performance; it is not a fat-loss aid',
      caution: 'late doses shorten sleep',
      foodFirst: 'A cup of brewed coffee has roughly 80–110 mg.',
    },
    vitamin_b12: {
      name: 'vitamin B12',
      dose: 'a low daily dose, or one or two higher doses a week',
      when: 'any time',
      why: 'prevents a shortfall that is common without meat or fish',
      caution: 'get tested if you have symptoms; ask a doctor',
      foodFirst: 'Milk, curd, paneer, eggs, fish, fortified foods.',
    },
  } as Record<string, { name: string; dose: string; when: string; why: string; caution: string; foodFirst: string }>,

  noBenefit: {
    title: 'Things that won’t help your goals',
    intro: 'Often sold for fat loss or muscle. The evidence says they won’t move your goals.',
  },

  /** Plain reasons per catalogue id (the catalogue keeps the evidence and sources). */
  noBenefitReasons: {
    bcaa: 'No extra muscle benefit once your daily protein is enough.',
    hmb: 'No gain in muscle or strength with training in younger adults.',
    green_tea_extract: 'Fat loss too small to matter, and high doses can harm the liver.',
    garcinia: 'Fat loss too small to matter, with more stomach upset.',
    cla_chitosan_glucomannan: 'None reached a meaningful amount of weight loss as pills.',
    l_carnitine: 'A small effect that shrinks in longer trials.',
    fat_burners: 'Mostly less than 2 kg, with stimulant side effects.',
    exogenous_ketones: 'No fat-loss benefit, and they can make endurance a little worse.',
    collagen_for_muscle: 'An incomplete protein: it doesn’t replace whey or soy for muscle.',
    nmn_nr: 'No effect on blood sugar, cholesterol or muscle overall.',
    resveratrol: 'Can blunt fitness gains from training.',
    antioxidant_megadoses: 'High doses around training can blunt how you adapt to it.',
  } as Record<string, string>,

  pantry: {
    title: 'Pantry',
    caption: 'already have',
    intro: 'What you mark here is left off the grocery list.',
    empty: 'Nothing marked yet.',
    add: 'Add an item',
    addKey: 'Add',
    addHelp: 'For example: rice, atta, curd.',
    edit: 'Edit',
    editName: 'Edit pantry',
    remove: (name: string) => `Remove ${name} from the pantry`,
    count: (n: number) => plural(n, 'item', 'items'),
  },

  kitchen: {
    title: 'Use what’s in my kitchen',
    intro: 'Recipes for today’s open meals from what you already have.',
    needPantry: 'Mark what you have in your pantry first.',
    run: 'Plan from my kitchen',
    impossible: 'Your kitchen doesn’t cover today’s protein. Add 2 items from the shop?',
    notToday: 'This works for today and the days ahead.',
  },

  ledger: {
    label: 'This week',
    line: (parts: string[]) => `This week: ${parts.join(' · ')}.`,
    asPlanned: (n: number) => `${plural(n, 'meal', 'meals')} as planned`,
    typed: (n: number) => `${n} typed by you`,
    coach: (n: number) => `${n} estimated by the Coach`,
    other: (n: number) => `${n} from other sources`,
    none: 'This week: no meals logged yet.',
    mostlyCoach: 'Most of this week’s food was estimated from photos and text, so the weekly check-in treats it as less certain.',
  },

  /** Example foods for plain targets, picked by the slot's macro balance. */
  examples: {
    snack: 'roasted chana and a katori of curd',
    protein: 'paneer bhurji, a roti and salad',
    carbs: 'dal, rice and curd',
    fat: 'eggs or paneer with vegetables',
    balanced: 'two rotis, dal and a katori of sabzi',
  },
  /** The same examples where the person's diet rules out what the defaults name (no eggs; no dairy). */
  examplesByDiet: {
    vegetarian: { fat: 'paneer or nuts with vegetables' },
    vegan: {
      snack: 'roasted chana and a handful of peanuts',
      protein: 'tofu bhurji, a roti and salad',
      carbs: 'dal, rice and sabzi',
      fat: 'tofu or nuts with vegetables',
    },
  },

  provider: {
    none: 'Connect an AI provider to get recipes.',
    failed: 'Couldn’t make a recipe this time.',
  },
} as const;

export { cap as capitalise };
