/** Settings › Agents copy. Plain and short, like the rest of Settings. */
export const AGENTS_COPY = {
  intro: 'AI agents can use Vitals tools: read your day, log meals and measurements, and suggest plan changes.',
  rules: 'Agents never get destructive actions, such as ending a plan. Plan changes arrive as proposals you apply yourself.',
  webmcpLabel: 'agents in this browser',
  webmcpHelp: 'Agents built into this browser can use Vitals tools while this tab is open.',
  webmcpUnsupported: "This browser can't share tools with agents yet (WebMCP).",
  serverHeading: 'agents on your other computers',
  serverIntro: 'Agents such as Codex, OpenCode, Claude Code or ChatGPT can use Vitals through your server, even when no Vitals tab is open. Plan changes still wait for you.',
  serverNotPaired: 'Agents on other computers reach Vitals through your server. Pair this device with your server first.',
  pairServer: 'Pair a server',
  addressKey: 'address',
  copy: 'Copy',
  copied: 'Copied',
  make: 'Make an agent key',
  clientLabel: 'agent',
  clients: { codex: 'Codex', opencode: 'OpenCode', claude: 'Claude Code', 'chatgpt-desktop': 'ChatGPT desktop app', other: 'Another agent' },
  nameLabel: 'name',
  nameHelp: 'Which agent and where, e.g. Codex on laptop.',
  scopeLabel: 'what it may do',
  scopes: {
    read: 'Read only: it can look at your plan, days and logs.',
    log: 'Read and log: it can also log meals, measurements and notes, with undo.',
    edit: 'Read, log and suggest plan changes: plan changes arrive as proposals you apply yourself.',
  },
  create: 'Make key',
  cancel: 'Cancel',
  shownOnceTitle: 'Your agent key',
  shownOnce: 'Shown once. Copy it now: closing this hides it for good. Anyone with this key can use Vitals as this agent.',
  keyLabel: 'key',
  envHint: 'The steps read the key from the environment variable VITALS_TOKEN. Set it to the key above on that computer.',
  recipesTitle: 'set it up',
  done: 'Done',
  keysHeading: 'keys',
  keysNone: 'No agent keys yet.',
  made: (date: string) => `made ${date}`,
  used: (when: string) => `used ${when}`,
  neverUsed: 'never used',
  revoke: 'Revoke',
  revokeName: (label: string) => `Revoke ${label}`,
  revokeTitle: (label: string) => `Revoke ${label}?`,
  revokeBody: 'That agent can no longer use Vitals.',
  unreachable: (when: string) => `Can't reach your server · last checked ${when}`,
  indicator: 'An agent is using Vitals',
  stop: 'Stop',
  stopLabel: 'Stop agents: turn off agent access on this device',
  directHeading: 'direct plan changes',
  directHelp: 'Plan changes from agents wait for you as proposals. Turn this on only for an agent you trust: its plan changes then apply at once, and you can still undo them.',
  directLabel: (name: string) => (name === 'webmcp' ? 'agents in this browser' : name),
  saveFailed: "Couldn't save that setting.",
} as const;

/** Settings › Agents › Connect your AI tools (desktop app only, SUITE_SPEC §15.6). */
export const CONNECT_TOOLS_COPY = {
  title: 'Connect your AI tools',
  intro: 'Let AI apps on this computer use Vitals. Each one asks you first, and nothing changes until you say yes.',
  found: 'found',
  notFound: 'not found on this computer',
  added: 'Vitals added',
  add: 'Add Vitals',
  addName: (label: string) => `Add Vitals to ${label}`,
  remove: 'Remove',
  removeName: (label: string) => `Remove Vitals from ${label}`,
  addTitle: (label: string) => `Add Vitals to ${label}?`,
  fileLabel: 'file that changes',
  linesLabel: 'what is added',
  canLabel: (label: string) => `what ${label} can do`,
  can: 'Read your data, log food and activity, and propose changes you approve. It cannot delete anything.',
  viaServer: 'It reaches Vitals through your server, with its own agent key that stays in this app.',
  viaApp: 'It reaches Vitals through this app, which starts in the background when needed.',
  confirmAdd: 'Add Vitals',
  cancel: 'Cancel',
  removeTitle: (label: string) => `Remove Vitals from ${label}?`,
  removeBody: (label: string) => `${label} can no longer use Vitals.`,
  confirmRemove: 'Remove',
  agentLabel: (label: string) => `Vitals desktop app · ${label}`,
  keyFailed: (label: string, why: string) => `Vitals was added to ${label}, but its key for your server could not be made (${why}). It uses this app instead.`,
  oldKeyLeft: (label: string, why: string) => `Vitals was added to ${label}, but an old key for it may still work on your server (${why}). Check the keys list above.`,
  keyLeft: (label: string, why: string) => `Vitals was removed from ${label}, but its key still works on your server (${why}). Revoke it in the keys list above.`,
  keysNotKept: 'This computer has no keyring, so Vitals forgets the server keys when it quits. After a restart, remove and add the AI tool again to use your server.',
  loadFailed: "Couldn't look for AI apps on this computer.",
} as const;
