/** Settings › Agents copy. Plain and short, like the rest of Settings. */
export const AGENTS_COPY = {
  intro: 'AI agents can use Vitals tools: read your day, log meals and measurements, and suggest plan changes.',
  rules: 'Agents never get destructive actions, such as ending a plan. Plan changes arrive as proposals you apply yourself.',
  webmcpLabel: 'agents in this browser',
  webmcpHelp: 'Agents built into this browser can use Vitals tools while this tab is open.',
  webmcpUnsupported: "This browser can't share tools with agents yet (WebMCP).",
  serverHeading: 'agents on your other computers',
  serverIntro: 'Agents such as Codex, OpenCode, Claude Code or ChatGPT can use Vitals through your server, even when no Vitals tab is open. Plan changes still wait for you.',
  serverNotPaired: 'Agents on other computers reach Vitals through your server. Pair this device with your server first.',
  pairServer: 'Pair a server',
  addressKey: 'address',
  copy: 'Copy',
  copied: 'Copied',
  make: 'Make an agent key',
  clientLabel: 'agent',
  clients: { codex: 'Codex', opencode: 'OpenCode', claude: 'Claude Code', 'chatgpt-desktop': 'ChatGPT desktop app', other: 'Another agent' },
  nameLabel: 'name',
  nameHelp: 'Which agent and where, e.g. Codex on laptop.',
  scopeLabel: 'what it may do',
  scopes: {
    read: 'Read only: it can look at your plan, days and logs.',
    log: 'Read and log: it can also log meals, measurements and notes, with undo.',
    edit: 'Read, log and suggest plan changes: plan changes arrive as proposals you apply yourself.',
  },
  create: 'Make key',
  cancel: 'Cancel',
  shownOnceTitle: 'Your agent key',
  shownOnce: 'Shown once. Copy it now: closing this hides it for good. Anyone with this key can use Vitals as this agent.',
  keyLabel: 'key',
  envHint: 'The steps read the key from the environment variable VITALS_TOKEN. Set it to the key above on that computer.',
  recipesTitle: 'set it up',
  done: 'Done',
  keysHeading: 'keys',
  keysNone: 'No agent keys yet.',
  made: (date: string) => `made ${date}`,
  used: (when: string) => `used ${when}`,
  neverUsed: 'never used',
  revoke: 'Revoke',
  revokeName: (label: string) => `Revoke ${label}`,
  revokeTitle: (label: string) => `Revoke ${label}?`,
  revokeBody: 'That agent can no longer use Vitals.',
  unreachable: (when: string) => `Can't reach your server · last checked ${when}`,
  indicator: 'An agent is using Vitals',
  stop: 'Stop',
  stopLabel: 'Stop agents: turn off agent access on this device',
  directHeading: 'direct plan changes',
  directHelp: 'Plan changes from agents wait for you as proposals. Turn this on only for an agent you trust: its plan changes then apply at once, and you can still undo them.',
  directLabel: (name: string) => (name === 'webmcp' ? 'agents in this browser' : name),
  saveFailed: "Couldn't save that setting.",
} as const;
