/**
 * Train screen copy (design/screens/living-mode.md, Train). Plain, specific, second person; a gap is "not logged",
 * never a failure; no streaks, no exclamation marks; no internal references (scanned by the living copy test).
 */

const cap = (s: string): string => (s ? `${s[0]!.toUpperCase()}${s.slice(1)}` : s);

export const TRAIN_COPY = {
  title: 'Train',
  titleWithDate: (day: string) => `Train · ${day}`,
  viewLabel: 'Train view',
  views: { today: 'today', week: 'week' },
  dateStrip: 'Day',

  preview: 'Preview · the plan may still change',
  past: (day: string) => `Logging for ${day}. What you add here still counts.`,
  paused: 'Paused · this is your usual day. What you log still counts.',
  outsidePlan: 'This day is outside the plan.',
  noPlan: 'Start a plan to use Train.',
  showNumbers: 'show numbers',
  hideNumbers: 'hide numbers',

  restTitle: (dayWord: string) => `${dayWord} training`,
  restDay: (steps: string | null) => (steps ? `Rest day. Steps target ${steps}.` : 'Rest day.'),
  restMobility: 'From the plan today',

  /** Session nouns: "lift", "walk", … */
  noun: { resistance: 'lift', walk: 'walk', run: 'run', cycle: 'ride', swim: 'swim', row: 'row', hiit: 'intervals', other: 'cardio' } as Readonly<Record<string, string>>,
  sessionTitle: (noun: string, minutes: number, place: string | null) => `${cap(noun)} · ${minutes} min${place ? ` · ${place}` : ''}`,
  place: { home: 'home', gym: 'gym', park: 'park', other: 'out' } as Readonly<Record<string, string>>,
  withEquipment: (phrase: string) => `with your ${phrase}`,
  noEquipment: 'no equipment needed',
  energyName: 'energy',
  energyHidden: 'energy hidden',
  target: (dayWord: string, what: string) => `${dayWord} ${what}`,
  todayWord: 'today’s',
  dayWord: (weekday: string) => `${weekday}’s`,

  start: 'Start session',
  stop: 'Stop timer',
  elapsed: (noun: string, clock: string) => `${noun} · ${clock} elapsed`,
  elapsedShort: (clock: string) => `${clock} elapsed`,

  logStyle: 'Log style',
  logStyles: { quick: 'quick', detailed: 'detailed', duration: 'duration' },

  exercises: 'Exercises',
  rx: {
    sets: (n: number, reps: number) => `${n} × ${reps}`,
    holds: (n: number, sec: number) => `${n} × ${sec} s hold`,
    work: (n: number, sec: number) => `${n} × ${sec} s`,
    rounds: (n: number) => `${n} rounds`,
    load: (kg: number) => `at ${kg} kg`,
    rest: (sec: number) => `rest ${sec} s`,
    tank: (n: number) => `leave ${n} rep${n === 1 ? '' : 's'} in the tank`,
    minutes: (m: number) => `${m} min`,
    speed: (kmh: number) => `at ${kmh} km/h`,
    kcal: (kcal: string) => `≈ ${kcal} kcal`,
  },
  tickName: (name: string) => `Mark ${name} as done as planned`,
  swap: 'Swap',
  swapName: (name: string) => `Swap ${name}`,
  skip: 'skip',
  skipName: (name: string) => `Skip ${name}`,
  instead: (name: string) => `instead of ${name}`,
  undoSwap: 'Undo swap',
  undoSwapName: (name: string) => `Undo the swap for ${name}`,
  everyWeekday: (weekday: string) => `Use this swap on every ${weekday}`,
  state: { done: 'done', partial: 'partly done', skipped: 'skipped', open: 'to do' },

  chips: (name: string) => `Sets of ${name}`,
  chip: (k: number, amount: string) => `set ${k}, ${amount}`,
  chipReps: (reps: number) => `${reps} reps`,
  chipSec: (sec: number) => `${sec} s`,
  setLabel: (k: number) => `set ${k}`,
  setWord: 'set',
  kg: 'kg',
  reps: 'reps',
  repsLeft: 'reps left',
  minutes: 'minutes',
  speed: 'speed',
  incline: 'incline',
  addSet: 'Add a set',
  removeSet: 'Remove the last set',

  sessionDone: 'Session done',
  somethingElse: 'I did something else',
  skipped: 'Skipped',
  skippedName: (noun: string) => `Mark ${noun} as skipped`,
  review: (done: number, total: number, counted: string) => `${done} of ${total} exercise${total === 1 ? '' : 's'} · counted ${counted}`,
  reviewNote: 'Exercises you didn’t tick count as done as planned.',
  save: 'Save',
  back: 'Back',
  saving: 'Saving…',

  saved: {
    full: (target: string, pct: number) => `Counts as ${target} · ${pct} %`,
    partial: (fix: string) => `Partly · ${fix}`,
    different: (credited: string, target: string) => `Different work — credited to ${credited}; ${target} is still open.`,
    also: (regions: string) => `also trained: ${regions}`,
    skipped: (target: string) => `${cap(target)} is marked as skipped.`,
  },
  logged: {
    done: 'Logged as planned',
    partial: (counted: string) => `Logged · partly · counted ${counted}`,
    skipped: 'Logged as skipped',
  },
  change: 'Change what you did',
  toast: {
    logged: (noun: string) => `${cap(noun)} logged`,
    skipped: (noun: string) => `${cap(noun)} marked as skipped`,
    undo: 'Undo',
    proposal: (pct: number) => `It keeps ${pct} % of the prescribed stimulus. A proposal is waiting on Today; nothing changes until you apply it.`,
    bought: 'Added. Using it would change your sessions — that comes as a proposal.',
  },
  cantSave: 'That couldn’t be saved. Try again.',

  swapSheet: {
    title: (name: string) => `Swap ${name}`,
    todayOnly: (dayWord: string) => `A swap applies to ${dayWord} session only.`,
    none: 'Nothing on your equipment matches this exercise. Something else still counts by what it trains.',
    showAll: 'show all',
    needs: (what: string, plural: boolean) => `needs ${what} (you don’t have ${plural ? 'them' : 'one'})`,
    use: (name: string) => `Use ${name}`,
    useShort: 'Use',
    somethingElse: 'Something else…',
    askCoach: 'Ask the Coach for options',
    coachDraft: (name: string) => `Options to swap ${name} today?`,
  },

  else: {
    title: 'What did you do instead?',
    titleItem: (name: string) => `Instead of ${name}`,
    field: 'What did you do?',
    help: 'Search the catalogue or describe it, for example “wooden wheel rollouts 3 × 10”.',
    results: 'Matching exercises',
    ready: 'on your equipment',
    needsKit: 'needs equipment you didn’t list',
    asTyped: (text: string) => `Use “${text}” as you typed it`,
    picked: 'What you did',
    newItem: 'New to your catalogue. It is counted by the muscles it most likely works, and you can correct it later.',
    sets: 'sets',
    reps: 'reps',
    minutes: 'minutes',
    save: 'Save',
    pickFirst: 'Pick or type what you did first.',
    noMatch: 'No match in the catalogue. Use it as you typed it; it still counts.',
  },

  equipment: {
    title: 'Your equipment',
    edit: 'Edit',
    editName: 'Edit your equipment',
    none: 'You haven’t told us what you have yet. Sessions use your body weight.',
    tell: 'Tell us what you have',
    places: 'places and days',
    everyDay: 'every day',
    wouldHelp: 'Would help',
    nothing: 'Nothing to buy for this plan.',
    needed: 'needed for this plan',
    adds: (what: string) => `adds ${what} work`,
    shorter: 'makes the sessions shorter or closer to the plan',
    free: 'use what you have',
    bought: 'Bought it',
    boughtName: (name: string) => `Bought ${name}`,
    noted: 'noted',
    tierName: (tier: number) => (tier <= 0 ? 'free' : `price ${'₹'.repeat(Math.min(4, tier))}`),
  },

  week: {
    title: 'This week',
    titleOf: (monday: string) => `Week of ${monday}`,
    rest: 'rest day',
    outside: 'outside the plan',
    status: { done: 'done', partial: 'partly', skipped: 'skipped', unknown: 'not logged', planned: 'planned' },
    openDay: (day: string, what: string) => `${day}: ${what}`,
  },

  injury: (parts: string) => `Exercises that don’t suit your ${parts} are left out (your setup).`,
  injuryWords: {
    shoulder: 'shoulder',
    elbow: 'elbow',
    wrist: 'wrist',
    lumbar: 'lower back',
    cervical: 'neck',
    knee: 'knee',
    ankle: 'ankle',
    hip: 'hip',
    hypertension: 'blood pressure',
    glaucoma: 'eyes',
    osteoporosis: 'bones',
    pregnancy: 'pregnancy',
    pelvic_floor: 'pelvic floor',
    cardiac_unscreened: 'heart',
  } as Readonly<Record<string, string>>,
  weekdaysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as readonly string[],
} as const;
