/** Copy for the ring views on Progress and the score details. Plain words, lowercase engraved labels. */
import type { NightStage } from './ringData';

export const RING_COPY = {
  stage: { deep: 'deep', light: 'light', rem: 'REM', awake: 'awake', unknown: 'unknown' } satisfies Record<NightStage, string>,
  stageHelp: { unknown: 'the ring could not tell the stage' },
  night: 'Last night',
  nightOf: (day: string) => `Night to ${day}`,
  bedWake: (bed: string, wake: string) => `in bed ${bed} · up ${wake}`,
  asleep: (h: string) => `asleep ${h}`,
  uncovered: (m: number) => `${m} min with no stage recorded`,
  provisional: 'stages may still change: the ring had not finished this night',
  noNight: 'No night with stages recorded yet. Import your ring history or sync the ring.',
  stagesCaption: 'stages',
  minutesCol: 'minutes',
  stageCol: 'stage',
  earlier: '‹ earlier',
  later: 'later ›',
  nightNav: 'Choose a night',
  hrDay: 'Heart rate through the day',
  hrDayEmpty: 'No heart-rate readings for this day.',
  resting: (bpm: number) => `resting ${bpm} bpm`,
  nightVitals: 'Overnight readings',
  spo2: 'blood oxygen',
  skinTemp: 'skin temperature',
  spo2Empty: 'No blood-oxygen readings for this night.',
  tempEmpty: 'No skin-temperature readings for this night.',
  loading: 'loading readings…',
  failed: 'Readings could not be read just now.',
  readings: (n: number) => `${n} reading${n === 1 ? '' : 's'}`,
  gapNote: 'breaks in the line are times with no readings',
  steps: 'Steps',
  stepsRange: { '7d': '7 days', '28d': '28 days' } as Record<'7d' | '28d', string>,
  stepsRangeLabel: 'Steps range',
  today: (n: string) => `today so far ${n} steps`,
  todayNone: 'no steps recorded today yet',
  activeToday: (m: number) => `${m} active min`,
  noDayData: 'no data',
  stepsEmpty: 'No steps recorded in this range.',
  stepsSummary: (days: number, withData: number, avg: string) => `${withData} of ${days} days recorded · average ${avg} steps on recorded days`,
  activeSummary: (avg: number) => `average ${avg} active min`,
  workouts: 'Workouts',
  workoutsEmpty: 'No workouts recorded in the last 90 days. Workouts come from your ring history import.',
  workoutCols: { date: 'date', type: 'type', duration: 'duration', avgHr: 'avg HR', maxHr: 'max HR', distance: 'distance' },
  activitySection: 'Activity',
  dash: '—',
} as const;

const TYPE_WORDS: Record<string, string> = {
  walking: 'walk', running: 'run', biking: 'cycle', strength_training: 'gym', hiking: 'hike', yoga: 'yoga', dancing: 'dance',
  squash: 'squash', other: 'other',
};
export const workoutTypeWord = (t: string): string => TYPE_WORDS[t] ?? t.replace(/_/g, ' ');
